# Generated by Django 5.1.5 on 2025-12-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_points_system_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsadmin',
            name='name',
        ),
    ]
