# Generated by Django migration
from django.db import migrations


def create_rewards(apps, schema_editor):
    """Create sample rewards in the catalog."""
    RewardsCatalog = apps.get_model('points', 'RewardsCatalog')
    rewards = [
        {
            'code': 'STICKER',
            'name': 'Sticker Pack',
            'description': 'MLAI branded sticker pack',
            'cost_points': 10,
            'fulfillment': 'manual',
            'is_active': True,
        },
        {
            'code': 'COFFEE',
            'name': 'Free Coffee',
            'description': 'One free coffee at the coworking space',
            'cost_points': 20,
            'fulfillment': 'manual',
            'is_active': True,
        },
        {
            'code': 'TSHIRT',
            'name': 'MLAI T-Shirt',
            'description': 'MLAI branded t-shirt',
            'cost_points': 100,
            'fulfillment': 'manual',
            'is_active': True,
        },
    ]
    for reward_data in rewards:
        RewardsCatalog.objects.get_or_create(
            code=reward_data['code'],
            defaults=reward_data
        )


def remove_rewards(apps, schema_editor):
    """Remove the seeded rewards."""
    RewardsCatalog = apps.get_model('points', 'RewardsCatalog')
    RewardsCatalog.objects.filter(code__in=['STICKER', 'COFFEE', 'TSHIRT']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_remove_pointsadmin_name'),
    ]

    operations = [
        migrations.RunPython(create_rewards, remove_rewards),
    ]
