# Generated by Django 5.1.5 on 2025-12-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_populate_comprehensive_rate_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsadmin',
            name='weekly_allowance',
            field=models.IntegerField(default=100, help_text='Max points this admin can award per week'),
        ),
    ]
