# Generated by Django 4.2.16 on 2026-06-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_runs', '0001_split_content_factory_apps'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentfactoryrun',
            index=models.Index(fields=['domain', 'workflow', '-updated_at'], name='cf_run_domain_wf_updated_idx'),
        ),
    ]
