# Generated by Django 4.2.16 on 2026-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_runs', '0002_contentfactoryrun_cf_run_domain_wf_updated_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfactoryrun',
            name='last_event_emitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
