# Generated by Django 4.2.16 on 2026-06-28 07:29

from django.db import migrations, models
import django.db.models.deletion


def _normalize_domain(domain):
    """Inlined copy of integrations.utils.normalize_domain (migrations must not
    import app code, which can drift)."""
    if not domain:
        return ""
    domain = domain.strip().lower()
    if domain.startswith("https://"):
        domain = domain[8:]
    elif domain.startswith("http://"):
        domain = domain[7:]
    if domain.startswith("www."):
        domain = domain[4:]
    if "/" in domain:
        domain = domain.split("/")[0]
    return domain


def backfill_run_organizations(apps, schema_editor):
    ContentFactoryRun = apps.get_model("workflow_runs", "ContentFactoryRun")
    Organization = apps.get_model("organizations", "Organization")

    org_id_by_domain = {
        _normalize_domain(org.domain): org.id
        for org in Organization.objects.all().only("id", "domain")
    }
    if not org_id_by_domain:
        return

    to_update = []
    runs = (
        ContentFactoryRun.objects.filter(organization__isnull=True)
        .exclude(domain="")
        .only("id", "domain")
    )
    for run in runs.iterator():
        org_id = org_id_by_domain.get(_normalize_domain(run.domain))
        if org_id is not None:
            run.organization_id = org_id
            to_update.append(run)
        if len(to_update) >= 500:
            ContentFactoryRun.objects.bulk_update(to_update, ["organization"])
            to_update = []
    if to_update:
        ContentFactoryRun.objects.bulk_update(to_update, ["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('workflow_runs', '0003_contentfactoryrun_last_event_emitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfactoryrun',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_factory_runs', to='organizations.organization'),
        ),
        migrations.RunPython(backfill_run_organizations, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='contentfactoryrun',
            index=models.Index(fields=['organization', 'workflow', '-updated_at'], name='cf_run_org_wf_updated_idx'),
        ),
    ]
