# Generated by Django 4.2.16 on 2026-04-28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ("run_date", models.CharField(db_index=True, max_length=32)),
                ("status", models.CharField(db_index=True, default="queued", max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("full_list_url", models.URLField(blank=True, max_length=1500, null=True)),
                ("slack_posted_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_count", models.IntegerField(default=0)),
                ("matched_count", models.IntegerField(default=0)),
                ("deduped_count", models.IntegerField(default=0)),
                ("ranked_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeekJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_date", models.CharField(db_index=True, max_length=32)),
                ("source_name", models.CharField(default="SEEK", max_length=255)),
                ("keyword", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("company_name", models.CharField(blank=True, max_length=255, null=True)),
                ("company_logo_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("company_domain", models.CharField(blank=True, max_length=255, null=True)),
                ("company_stage", models.CharField(blank=True, max_length=255, null=True)),
                ("company_size", models.CharField(blank=True, max_length=255, null=True)),
                ("company_quality_score", models.FloatField(default=0.0)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("job_url", models.URLField(max_length=1500)),
                ("posted_text", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("run_date", "job_url"), name="jobs_seek_jobs_run_url_unique"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceRunLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=64)),
                ("fetched_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        db_column="run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_logs",
                        to="jobs.jobrun",
                        to_field="run_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_date", models.CharField(db_index=True, max_length=32)),
                ("title", models.CharField(max_length=500)),
                ("company_name", models.CharField(blank=True, max_length=255, null=True)),
                ("company_logo_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("company_domain", models.CharField(blank=True, max_length=255, null=True)),
                ("company_stage", models.CharField(blank=True, max_length=255, null=True)),
                ("company_size", models.CharField(blank=True, max_length=255, null=True)),
                ("company_quality_score", models.FloatField(default=0.0)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("remote_region", models.CharField(blank=True, max_length=255, null=True)),
                ("remote_eligibility", models.CharField(blank=True, max_length=255, null=True)),
                ("remote_eligibility_score", models.FloatField(default=0.0)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("job_url", models.URLField(max_length=1500)),
                ("apply_url", models.URLField(blank=True, max_length=1500, null=True)),
                ("source_name", models.CharField(db_index=True, max_length=255)),
                ("source_type", models.CharField(blank=True, max_length=255, null=True)),
                ("date_posted", models.DateTimeField(blank=True, null=True)),
                ("date_scraped", models.DateTimeField(default=django.utils.timezone.now)),
                ("posted_text", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("ai_score", models.FloatField(default=0.0)),
                ("startup_score", models.FloatField(default=0.0)),
                ("australia_score", models.FloatField(default=0.0)),
                ("remote_score", models.FloatField(default=0.0)),
                ("recency_score", models.FloatField(default=0.0)),
                ("source_score", models.FloatField(default=0.0)),
                ("quality_score", models.FloatField(default=0.0)),
                ("ranking_score", models.FloatField(default=0.0)),
                ("bucket", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("why_selected", models.TextField(blank=True, null=True)),
                ("dedupe_key", models.CharField(db_index=True, max_length=1500)),
                ("is_top_pick", models.BooleanField(default=False)),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        db_column="run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.jobrun",
                        to_field="run_id",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("run", "dedupe_key"), name="jobs_job_listing_run_dedupe_unique"),
                ],
            },
        ),
    ]
