# Generated by Django 4.2.16 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="collect_live",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="max_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="per_keyword_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="post_to_notion",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="post_to_slack",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="source_names",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="trigger_source",
            field=models.CharField(default="manual_api", max_length=64),
        ),
    ]
