# Generated by Django 5.1.5 on 2025-11-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_first_name_user_last_name'),
    ]

    def split_names(apps, schema_editor):
        User = apps.get_model('core', 'User')
        for user in User.objects.all():
            if user.full_name:
                parts = user.full_name.strip().split(' ', 1)
                user.first_name = parts[0]
                if len(parts) > 1:
                    user.last_name = parts[1]
                user.save()

    operations = [
        migrations.RunPython(split_names),
    ]
