# Generated by Django 5.1.5 on 2025-11-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_split_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
