# Generated by Django 5.1.5 on 2025-11-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
