# Generated by Django 5.1.5 on 2025-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='is_obscured',
            field=models.BooleanField(default=True, help_text='If set to True, submission scores will be hidden from users.'),
        ),
    ]
