# Generated by Django 5.1.5 on 2025-12-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_slack_id_alter_globalsettings_is_obscured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_factory_organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationContentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_template', models.TextField(blank=True, null=True)),
                ('design_guide', models.TextField(blank=True, null=True)),
                ('github_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('github_token_encrypted', models.TextField(blank=True, null=True)),
                ('article_path_pattern', models.CharField(default='app/articles/content/{category}/{slug}.tsx', max_length=255)),
                ('registry_path', models.CharField(default='app/articles/registry.ts', max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_config', to='core.organization')),
            ],
            options={
                'db_table': 'content_factory_org_config',
            },
        ),
    ]
