# Generated by Django 4.2.16 on 2025-12-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organization_organizationcontentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='scan_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
