# Generated by Django 4.2.16 on 2025-12-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organizationcontentconfig_scan_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='resource_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
