# Generated by Django 4.2.16 on 2026-01-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organizationcontentconfig_resource_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_data', models.JSONField(default=dict)),
                ('total_components', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('generated_count', models.IntegerField(default=0)),
                ('generation_status', models.CharField(blank=True, max_length=20, null=True)),
                ('design_guide_path', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_pr_url', models.URLField(blank=True, null=True)),
                ('storage_branch_url', models.URLField(blank=True, null=True)),
                ('failed_components', models.JSONField(default=list)),
                ('last_scan_commit', models.CharField(blank=True, max_length=40, null=True)),
                ('last_scan_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component_mapping', to='core.organization')),
            ],
            options={
                'db_table': 'content_factory_component_mapping',
            },
        ),
        migrations.CreateModel(
            name='GeneratedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('generated', 'Generated'), ('adapted', 'Adapted')], max_length=20)),
                ('original_path', models.CharField(blank=True, max_length=500, null=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('matched_component', models.CharField(blank=True, max_length=100, null=True)),
                ('adaptation_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_components', to='core.organization')),
            ],
            options={
                'db_table': 'content_factory_generated_component',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
