# Generated by Django 4.2.16 on 2026-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_component_library_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='company_context',
            field=models.TextField(blank=True, help_text='Auto-generated company overview for article generation context', null=True),
        ),
    ]
