# Generated by Django 4.2.16 on 2026-01-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_company_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='competitors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
