# Generated by Django 4.2.16 on 2026-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organization_competitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='seed_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Seed keywords for content research'),
        ),
    ]
