# Generated by Django 4.2.16 on 2026-01-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_seed_keywords_to_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFactoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slack_user_id', models.CharField(db_index=True, max_length=50)),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('researching', 'Researching'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('generating', 'Generating'), ('completed', 'Completed'), ('error', 'Error')], default='queued', max_length=30)),
                ('selected_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('selection_reason', models.TextField(blank=True, null=True)),
                ('selection_data', models.JSONField(blank=True, default=dict)),
                ('article_url', models.URLField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_factory_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
