# Generated by Django 4.2.16 on 2026-01-15 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_content_factory_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfactoryjob',
            name='request_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Original request parameters for retry'),
        ),
        migrations.AlterField(
            model_name='contentfactoryjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('researching', 'Researching'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('generating', 'Generating'), ('completed', 'Completed'), ('error', 'Error'), ('auth_required', 'Auth Required')], default='queued', max_length=30),
        ),
        migrations.CreateModel(
            name='WrittenArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('article_url', models.URLField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, null=True)),
                ('primary_keyword', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.contentfactoryjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_articles', to='core.organization')),
            ],
            options={
                'db_table': 'seo_written_article',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clustering_threshold', models.FloatField(default=0.85)),
                ('total_keywords', models.IntegerField(default=0)),
                ('unclustered_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_maps', to='core.organization')),
            ],
            options={
                'db_table': 'seo_topic_map',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemanticCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField(help_text='Local ID within the topic map')),
                ('pillar_keyword', models.CharField(db_index=True, max_length=500)),
                ('average_similarity', models.FloatField(default=0.0)),
                ('total_volume', models.IntegerField(default=0)),
                ('avg_difficulty', models.FloatField(default=0.0)),
                ('avg_velocity', models.FloatField(default=0.0)),
                ('topic_tier', models.CharField(choices=[('tier_1_blue_ocean', 'Blue Ocean'), ('tier_2_authority', 'Authority Builder'), ('tier_3_long_tail', 'Long Tail Gem'), ('tier_4_discard', 'Discard')], default='tier_4_discard', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_clusters', to='core.organization')),
            ],
            options={
                'db_table': 'seo_semantic_cluster',
                'ordering': ['-total_volume'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed_keywords_used', models.JSONField(default=list)),
                ('competitors_analyzed', models.JSONField(default=list)),
                ('keywords_discovered', models.IntegerField(default=0)),
                ('keywords_updated', models.IntegerField(default=0)),
                ('clusters_created', models.IntegerField(default=0)),
                ('geo_config', models.JSONField(blank=True, default=dict, help_text='GEO flags/thresholds used in this session')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_sessions', to='core.organization')),
            ],
            options={
                'db_table': 'seo_research_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchedKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(db_index=True, max_length=500)),
                ('keyword_normalized', models.CharField(db_index=True, help_text='Lowercase, trimmed version for deduplication', max_length=500)),
                ('volume', models.IntegerField(default=0, help_text='Monthly search volume')),
                ('difficulty', models.IntegerField(default=50, help_text='SEO difficulty 0-100')),
                ('intent', models.CharField(default='informational', max_length=50)),
                ('tier', models.CharField(choices=[('tier_1_blue_ocean', 'Blue Ocean'), ('tier_2_authority', 'Authority Builder'), ('tier_3_long_tail', 'Long Tail Gem'), ('tier_4_discard', 'Discard')], default='tier_4_discard', max_length=30)),
                ('opportunity_index', models.FloatField(db_index=True, default=0.0)),
                ('source', models.CharField(choices=[('seed', 'Seed Keyword'), ('competitor', 'Competitor Analysis'), ('related', 'Related/Semantic'), ('paa', 'People Also Ask')], default='seed', max_length=20)),
                ('source_detail', models.CharField(blank=True, help_text='E.g., competitor domain or seed keyword', max_length=255, null=True)),
                ('competitor_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('written', 'Written'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metrics_updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researched_keywords', to='core.organization')),
                ('written_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_keywords', to='core.writtenarticle')),
            ],
            options={
                'db_table': 'seo_researched_keyword',
                'ordering': ['-opportunity_index'],
            },
        ),
        migrations.CreateModel(
            name='PAQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_normalized', models.CharField(db_index=True, help_text='Lowercase version for dedup', max_length=500)),
                ('answer_snippet', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('depth', models.IntegerField(default=1)),
                ('has_ai_overview', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paa_questions', to='core.researchedkeyword')),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='core.paquestion')),
            ],
            options={
                'db_table': 'seo_paa_question',
                'ordering': ['depth', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KeywordVelocity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('absolute_volume', models.IntegerField(default=0)),
                ('velocity_score', models.FloatField(default=0.0, help_text='-1.0 to 1.0+')),
                ('trend_status', models.CharField(choices=[('breakout', 'Breakout'), ('rising', 'Rising'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('daily_volumes', models.JSONField(blank=True, default=list, help_text='Raw daily volume data from Glimpse/pytrends')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_snapshots', to='core.researchedkeyword')),
            ],
            options={
                'db_table': 'seo_keyword_velocity',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_pillar', models.BooleanField(default=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_keywords', to='core.semanticcluster')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='core.researchedkeyword')),
            ],
            options={
                'db_table': 'seo_cluster_membership',
            },
        ),
        migrations.CreateModel(
            name='AISaturation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_overview_present', models.BooleanField(default=False)),
                ('ai_overview_quality', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('partial', 'Partial'), ('none', 'None')], default='none', max_length=20)),
                ('featured_snippet_present', models.BooleanField(default=False)),
                ('video_carousel_present', models.BooleanField(default=False)),
                ('knowledge_panel_present', models.BooleanField(default=False)),
                ('saturation_score', models.FloatField(default=0.0, help_text='0.0 (no AI) to 1.0 (fully saturated)')),
                ('hostility_score', models.FloatField(default=0.0)),
                ('hostility_recommendation', models.CharField(choices=[('high_priority', 'High Priority'), ('pivot_angle', 'Pivot Angle'), ('low_priority', 'Low Priority')], default='high_priority', max_length=20)),
                ('organic_positions_above_fold', models.IntegerField(default=0)),
                ('serp_features', models.JSONField(blank=True, default=list, help_text='List of SERP feature types present')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_saturation_snapshots', to='core.researchedkeyword')),
            ],
            options={
                'db_table': 'seo_ai_saturation',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='writtenarticle',
            index=models.Index(fields=['organization', 'primary_keyword'], name='seo_written_organiz_e80b8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='writtenarticle',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='semanticcluster',
            index=models.Index(fields=['organization', 'topic_tier'], name='seo_semanti_organiz_a6196c_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticcluster',
            index=models.Index(fields=['pillar_keyword'], name='seo_semanti_pillar__88e2cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semanticcluster',
            unique_together={('organization', 'cluster_id')},
        ),
        migrations.AddIndex(
            model_name='researchedkeyword',
            index=models.Index(fields=['organization', 'status'], name='seo_researc_organiz_4846da_idx'),
        ),
        migrations.AddIndex(
            model_name='researchedkeyword',
            index=models.Index(fields=['organization', 'tier'], name='seo_researc_organiz_cce2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='researchedkeyword',
            index=models.Index(fields=['organization', 'opportunity_index'], name='seo_researc_organiz_5d9bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='researchedkeyword',
            index=models.Index(fields=['organization', 'status', 'opportunity_index'], name='seo_researc_organiz_6443e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='researchedkeyword',
            unique_together={('organization', 'keyword_normalized')},
        ),
        migrations.AddIndex(
            model_name='paquestion',
            index=models.Index(fields=['keyword', 'depth'], name='seo_paa_que_keyword_4783b1_idx'),
        ),
        migrations.AddIndex(
            model_name='paquestion',
            index=models.Index(fields=['question_normalized'], name='seo_paa_que_questio_041c04_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordvelocity',
            index=models.Index(fields=['keyword', 'captured_at'], name='seo_keyword_keyword_b0c1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='clustermembership',
            index=models.Index(fields=['cluster', 'is_pillar'], name='seo_cluster_cluster_b7f7da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clustermembership',
            unique_together={('keyword', 'cluster')},
        ),
        migrations.AddIndex(
            model_name='aisaturation',
            index=models.Index(fields=['keyword', 'captured_at'], name='seo_ai_satu_keyword_9db7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='aisaturation',
            index=models.Index(fields=['saturation_score'], name='seo_ai_satu_saturat_99c400_idx'),
        ),
    ]
