# Generated by Django 4.2.16 on 2026-02-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_installed_packages_to_orgconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='github_installation_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='github_refresh_token_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='github_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='github_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='github_user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
