# Generated by Django 4.2.16 on 2026-02-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_org_github_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='articles_scaffold_pr_url',
            field=models.URLField(blank=True, help_text='PR URL from the articles scaffolding operation', null=True),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='articles_scaffolded',
            field=models.BooleanField(default=False, help_text='Whether the articles directory has been scaffolded in the GitHub repo'),
        ),
    ]
