# Generated by Django 4.2.16 on 2026-02-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_articles_scaffolded'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisaturation',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paquestion',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
