# Generated by Django 4.2.16 on 2026-02-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_domain_on_paa_and_aisaturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='articles_scaffold_preview_url',
            field=models.URLField(blank=True, help_text='Cloudflare Pages preview URL from the articles scaffolding operation', null=True),
        ),
    ]
