# Generated by Django 4.2.16 on 2026-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_org_config_repo_execution_contract_and_job_pr_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfactoryrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('awaiting_delivery_mode', 'Awaiting Delivery Mode'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('awaiting_approval', 'Awaiting Approval'), ('approval_required', 'Approval Required'), ('denied', 'Denied')], db_index=True, default='queued', max_length=40),
        ),
        migrations.AlterField(
            model_name='contentfactoryrunstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentfactoryrunstepattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
