# Generated by Django 4.2.16 on 2026-05-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_split_content_factory_apps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_team",
        ),
    ]
