# Generated by Django 4.2.16 on 2026-08-02 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


def canonicalize_user_emails(apps, schema_editor):
    User = apps.get_model('core', 'User')
    seen = {}
    updates = []
    for user in User.objects.only('id', 'email').iterator():
        canonical = str(user.email or '').strip().lower()
        prior_id = seen.get(canonical)
        if prior_id is not None:
            raise RuntimeError(
                'Cannot add case-insensitive email uniqueness: '
                f'user IDs {prior_id} and {user.id} share a canonical email.'
            )
        seen[canonical] = user.id
        if canonical != user.email:
            user.email = canonical
            updates.append(user)
    if updates:
        User.objects.bulk_update(updates, ['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_rebrand_hospital_as_healthhack'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(canonicalize_user_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='core_user_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='passwordresetchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_reset_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresetchallenge',
            index=models.Index(fields=['user', 'created_at'], name='password_reset_user_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetchallenge',
            index=models.Index(fields=['expires_at'], name='password_reset_expiry_idx'),
        ),
    ]
