# Generated by Django 4.2.16 on 2026-08-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_passwordresetemaildelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackFounderAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_slack_account_link', to=settings.AUTH_USER_MODEL)),
                ('slack_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_founder_account_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_slackfounderaccountlink',
            },
        ),
        migrations.CreateModel(
            name='SlackFounderLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_founder_link_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_slackfounderlinkrequest',
                'indexes': [models.Index(fields=['slack_user', 'expires_at'], name='core_sflr_user_exp_idx')],
            },
        ),
    ]
