from django.urls import path

from .views import (
    OrgMemoryActorContextView,
    OrgMemoryPilotAccessProbeView,
)
from .drive_webhook_views import DriveChangesWebhookView
from .kernel_views import MemoryKernelHealthView
from .provider_event_views import (
    GmailMemoryPushView,
    LinearMemoryWebhookView,
    NotionMemoryWebhookView,
    SlackMemoryWebhookView,
    XeroMemoryWebhookView,
)
from .query_views import (
    OrgMemoryAnswerView,
    OrgMemoryFeedbackView,
    OrgMemoryQueryTraceView,
    OrgMemorySearchView,
    OrgMemoryTimelineView,
)
from .publication_views import (
    OrgMemoryPublicationDetailView,
    OrgMemoryPublicationListCreateView,
    OrgMemoryPublicationRevokeView,
    OrgMemoryPublicationSubmitView,
)
from .action_views import (
    OrgMemoryActionApproveView,
    OrgMemoryActionDetailView,
    OrgMemoryActionExecuteView,
    OrgMemoryActionListCreateView,
    OrgMemoryActionRejectView,
    OrgMemoryActionReverseView,
)
from .review_views import (
    OrgMemoryDigestDetailView,
    OrgMemoryDigestListView,
    OrgMemoryReviewDashboardView,
    OrgMemoryReviewDetailView,
    OrgMemoryReviewEvidenceView,
    OrgMemoryReviewListView,
    OrgMemoryReviewReprocessView,
    OrgMemoryReviewResolveView,
    OrgMemorySummaryDetailView,
    OrgMemorySummaryListView,
)
from .source_views import (
    MemoryConnectionApproveView,
    MemoryConnectionBackfillView,
    MemoryConnectionDeleteView,
    MemoryConnectionDiscoverView,
    MemoryConnectionDryRunView,
    MemoryConnectionHealthView,
    MemoryConnectionListView,
    MemoryConnectionPauseView,
    MemoryConnectionPermissionRefreshView,
    MemoryConnectionPreviewView,
    MemoryConnectionReprocessView,
    MemoryConnectionResumeView,
    MemoryConnectionScopeView,
    MemoryConnectionSyncView,
    MemoryProviderConnectView,
    MemoryProviderListView,
)


urlpatterns = [
    path("webhooks/google-drive/changes", DriveChangesWebhookView.as_view(), name="org-memory-drive-changes-webhook"),
    path("webhooks/linear/events", LinearMemoryWebhookView.as_view(), name="org-memory-linear-webhook"),
    path("webhooks/slack/events", SlackMemoryWebhookView.as_view(), name="org-memory-slack-webhook"),
    path("webhooks/notion/events", NotionMemoryWebhookView.as_view(), name="org-memory-notion-webhook"),
    path("webhooks/xero/events", XeroMemoryWebhookView.as_view(), name="org-memory-xero-webhook"),
    path("webhooks/gmail/push", GmailMemoryPushView.as_view(), name="org-memory-gmail-push"),
    path("auth/context", OrgMemoryActorContextView.as_view(), name="org-memory-actor-context"),
    path(
        "pilot/access-check",
        OrgMemoryPilotAccessProbeView.as_view(),
        name="org-memory-pilot-access-check",
    ),
    path("answer", OrgMemoryAnswerView.as_view(), name="org-memory-answer"),
    path("search", OrgMemorySearchView.as_view(), name="org-memory-search"),
    path("feedback", OrgMemoryFeedbackView.as_view(), name="org-memory-feedback"),
    path("entities/<uuid:entity_id>/timeline", OrgMemoryTimelineView.as_view(), name="org-memory-entity-timeline"),
    path("queries/<uuid:query_id>/trace", OrgMemoryQueryTraceView.as_view(), name="org-memory-query-trace"),
    path("review-dashboard", OrgMemoryReviewDashboardView.as_view(), name="org-memory-review-dashboard"),
    path("reviews", OrgMemoryReviewListView.as_view(), name="org-memory-reviews"),
    path("reviews/<uuid:review_id>", OrgMemoryReviewDetailView.as_view(), name="org-memory-review-detail"),
    path("reviews/<uuid:review_id>/evidence", OrgMemoryReviewEvidenceView.as_view(), name="org-memory-review-evidence"),
    path("reviews/<uuid:review_id>/resolve", OrgMemoryReviewResolveView.as_view(), name="org-memory-review-resolve"),
    path("reviews/<uuid:review_id>/reprocess", OrgMemoryReviewReprocessView.as_view(), name="org-memory-review-reprocess"),
    path("review-items", OrgMemoryReviewListView.as_view(), name="org-memory-review-items"),
    path("review-items/<uuid:review_id>", OrgMemoryReviewDetailView.as_view(), name="org-memory-review-item-detail"),
    path("review-items/<uuid:review_id>/evidence", OrgMemoryReviewEvidenceView.as_view(), name="org-memory-review-item-evidence"),
    path("review-items/<uuid:review_id>/resolve", OrgMemoryReviewResolveView.as_view(), name="org-memory-review-item-resolve"),
    path("summaries", OrgMemorySummaryListView.as_view(), name="org-memory-summaries"),
    path("summaries/<uuid:summary_id>", OrgMemorySummaryDetailView.as_view(), name="org-memory-summary-detail"),
    path("digests", OrgMemoryDigestListView.as_view(), name="org-memory-digests"),
    path("digests/<uuid:digest_id>", OrgMemoryDigestDetailView.as_view(), name="org-memory-digest-detail"),
    path("publications", OrgMemoryPublicationListCreateView.as_view(), name="org-memory-publications"),
    path("publications/<uuid:publication_id>", OrgMemoryPublicationDetailView.as_view(), name="org-memory-publication-detail"),
    path("publications/<uuid:publication_id>/submit", OrgMemoryPublicationSubmitView.as_view(), name="org-memory-publication-submit"),
    path("publications/<uuid:publication_id>/revoke", OrgMemoryPublicationRevokeView.as_view(), name="org-memory-publication-revoke"),
    path("actions", OrgMemoryActionListCreateView.as_view(), name="org-memory-actions"),
    path("actions/<uuid:proposal_id>", OrgMemoryActionDetailView.as_view(), name="org-memory-action-detail"),
    path("actions/<uuid:proposal_id>/approve", OrgMemoryActionApproveView.as_view(), name="org-memory-action-approve"),
    path("actions/<uuid:proposal_id>/reject", OrgMemoryActionRejectView.as_view(), name="org-memory-action-reject"),
    path("actions/<uuid:proposal_id>/execute", OrgMemoryActionExecuteView.as_view(), name="org-memory-action-execute"),
    path("actions/<uuid:proposal_id>/reverse", OrgMemoryActionReverseView.as_view(), name="org-memory-action-reverse"),
    path("health", MemoryKernelHealthView.as_view(), name="org-memory-kernel-health"),
    path("connectors", MemoryProviderListView.as_view(), name="org-memory-connectors"),
    path("connectors/<str:provider>/connect", MemoryProviderConnectView.as_view(), name="org-memory-provider-connect"),
    path("connections", MemoryConnectionListView.as_view(), name="org-memory-connections"),
    path("connections/<uuid:configuration_id>/scopes", MemoryConnectionScopeView.as_view(), name="org-memory-connection-scopes"),
    path("connections/<uuid:configuration_id>/discover", MemoryConnectionDiscoverView.as_view(), name="org-memory-connection-discover"),
    path("connections/<uuid:configuration_id>/preview", MemoryConnectionPreviewView.as_view(), name="org-memory-connection-preview"),
    path("connections/<uuid:configuration_id>/dry-run", MemoryConnectionDryRunView.as_view(), name="org-memory-connection-dry-run"),
    path("connections/<uuid:configuration_id>/approve", MemoryConnectionApproveView.as_view(), name="org-memory-connection-approve"),
    path("connections/<uuid:configuration_id>/backfill", MemoryConnectionBackfillView.as_view(), name="org-memory-connection-backfill"),
    path("connections/<uuid:configuration_id>/sync", MemoryConnectionSyncView.as_view(), name="org-memory-connection-sync"),
    path("connections/<uuid:configuration_id>/pause", MemoryConnectionPauseView.as_view(), name="org-memory-connection-pause"),
    path("connections/<uuid:configuration_id>/resume", MemoryConnectionResumeView.as_view(), name="org-memory-connection-resume"),
    path("connections/<uuid:configuration_id>/reprocess", MemoryConnectionReprocessView.as_view(), name="org-memory-connection-reprocess"),
    path("connections/<uuid:configuration_id>/refresh-permissions", MemoryConnectionPermissionRefreshView.as_view(), name="org-memory-connection-refresh-permissions"),
    path("connections/<uuid:configuration_id>/health", MemoryConnectionHealthView.as_view(), name="org-memory-connection-health"),
    path("connections/<uuid:configuration_id>", MemoryConnectionDeleteView.as_view(), name="org-memory-connection-delete"),
]
