# Generated by Django 4.2.16 on 2026-08-01 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChatChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('audience', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('nonce_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_chat_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunityChatDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_membership_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_community_chat_devices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_chat_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunityChatInviteAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter_invite_id', models.CharField(max_length=128)),
                ('adapter_request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invite_audit', to='community_chat.communitychatchallenge')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invite_audits', to='community_chat.communitychatdevice')),
            ],
            options={
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['device', 'issued_at'], name='chat_invite_device_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='communitychatdevice',
            index=models.Index(fields=['user', 'status'], name='chat_device_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitychatdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'verified'))), fields=('public_key',), name='community_chat_unique_active_public_key'),
        ),
        migrations.AddIndex(
            model_name='communitychatchallenge',
            index=models.Index(fields=['user', 'public_key', 'created_at'], name='chat_challenge_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='communitychatchallenge',
            index=models.Index(fields=['expires_at'], name='chat_challenge_expiry_idx'),
        ),
    ]
