# Generated by Django 4.2.16 on 2026-08-17 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_chat', '0007_active_installation_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsageAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('last_report_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TokenUsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('session_id', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=128)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('cache_read_tokens', models.BigIntegerField(default=0)),
                ('cache_creation_tokens', models.BigIntegerField(default=0)),
                ('reasoning_tokens', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='community_chat.tokenusageaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'started_at'], name='token_usage_acct_time_idx'), models.Index(fields=['started_at'], name='token_usage_time_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tokenusagesession',
            constraint=models.UniqueConstraint(fields=('account', 'source', 'session_id', 'model'), name='token_usage_unique_session_model'),
        ),
        migrations.CreateModel(
            name='TokenUsageDailyBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('source', models.CharField(max_length=16)),
                ('session_id', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=128)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('cache_read_tokens', models.BigIntegerField(default=0)),
                ('cache_creation_tokens', models.BigIntegerField(default=0)),
                ('reasoning_tokens', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_buckets', to='community_chat.tokenusageaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['usage_date', 'account'], name='token_usage_day_acct_idx'), models.Index(fields=['account', 'usage_date'], name='token_usage_acct_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'usage_date', 'source', 'session_id', 'model'), name='token_usage_unique_daily_bucket')],
            },
        ),
    ]
