# Generated by Django 4.2.16 on 2026-09-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("roo", "0036_sanitize_coworking_operation_receipts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community_chat", "0008_token_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("community", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(blank=True, max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("event", "Event"), ("project", "Project")],
                        max_length=16,
                    ),
                ),
                ("action_key", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("purpose", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("learning", models.CharField(blank=True, max_length=500)),
                ("source", models.JSONField(default=dict)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("reward_microroo", models.PositiveBigIntegerField()),
                ("reward_max_microroo", models.PositiveBigIntegerField()),
                ("recommended_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("audience", models.CharField(default="community", max_length=16)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guided_volunteer_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerRecognition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("community", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("outcome_key", models.CharField(max_length=255)),
                ("action_key", models.CharField(max_length=64)),
                ("source", models.JSONField(default=dict)),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                ("evidence", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("version", models.PositiveIntegerField(default=1)),
                ("reward_microroo", models.PositiveBigIntegerField(default=0)),
                ("review_history", models.JSONField(default=list)),
                (
                    "ledger",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_recognition",
                        to="roo.ledger",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognitions",
                        to="community_chat.volunteeropportunity",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_review_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_recognitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("community", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("purpose", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("source", models.JSONField(default=dict)),
                ("published", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="volunteeropportunity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="community_chat.volunteerproject",
            ),
        ),
        migrations.AddField(
            model_name="volunteeropportunity",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_volunteer_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="VolunteerMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("community", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level_key", models.CharField(max_length=64)),
                ("reached_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ledger",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_milestone",
                        to="roo.ledger",
                    ),
                ),
                (
                    "recognition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones",
                        to="community_chat.volunteerrecognition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerMemberState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("community", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "historical_microroo",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("historical_ledger_cutoff", models.PositiveBigIntegerField(default=0)),
                ("reconciliation_note", models.TextField(blank=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciled_volunteer_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("community", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=200)),
                ("checked_in_at", models.DateTimeField()),
                ("source_id", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("audit_history", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_volunteer_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerSourceReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("community", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(max_length=255)),
                ("origin", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=32)),
                ("source", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error", models.CharField(blank=True, max_length=120)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_source_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recognition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_receipts",
                        to="community_chat.volunteerrecognition",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer_received_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["community", "kind", "status"],
                        name="vol_source_processing_idx",
                    ),
                    models.Index(
                        fields=["actor", "occurred_at"], name="vol_source_actor_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="volunteersourcereceipt",
            constraint=models.UniqueConstraint(
                fields=("community", "source_key"), name="vol_source_origin_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerrecognition",
            index=models.Index(
                fields=["community", "user", "status", "created_at"],
                name="vol_recognition_member_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerrecognition",
            index=models.Index(
                fields=["reviewer", "status"], name="vol_review_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteerrecognition",
            constraint=models.UniqueConstraint(
                fields=("community", "user", "outcome_key"),
                name="vol_recognition_outcome_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="volunteerproject",
            index=models.Index(
                fields=["community", "published"], name="vol_project_public_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="volunteeropportunity",
            index=models.Index(
                fields=["community", "status", "event_id"],
                name="vol_opportunity_feed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteeropportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("kind", "event"), models.Q(("event_id", ""), _negated=True)
                ),
                fields=("community", "event_id"),
                name="vol_one_opportunity_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteeropportunity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("reward_max_microroo__gte", models.F("reward_microroo"))
                ),
                name="vol_reward_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteermilestone",
            constraint=models.UniqueConstraint(
                fields=("community", "user", "level_key"),
                name="vol_milestone_once_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteermemberstate",
            constraint=models.UniqueConstraint(
                fields=("community", "user"), name="vol_member_community_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteerattendance",
            constraint=models.UniqueConstraint(
                fields=("community", "user", "event_id"),
                name="vol_attendance_event_unique",
            ),
        ),
    ]
