# Generated by Django 4.2.16 on 2026-09-20 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_chat', '0010_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='roo_chat', max_length=32)),
                ('disclosure_version', models.CharField(max_length=80)),
                ('provider_digest', models.CharField(max_length=64)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('shared_mlai_account', 'Shared MLAI account'), ('chat_data', 'Chat data')], max_length=24)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_attention', 'Needs attention')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_version', models.CharField(max_length=80)),
                ('outcome_summary', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='aiconsentrecord',
            constraint=models.UniqueConstraint(fields=('user', 'purpose'), name='chat_ai_consent_purpose'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['status', 'requested_at'], name='chat_deletion_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountdeletionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed'), _negated=True), fields=('user', 'scope'), name='chat_one_open_deletion_scope'),
        ),
    ]
