# Generated by Django 4.2.16 on 2026-09-21 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_chat', '0011_account_privacy_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMemberReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=80)),
                ('match', models.CharField(choices=[('exact', 'Exact name'), ('word', 'Whole word or phrase')], default='exact', max_length=8)),
                ('reason', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='communitychatemailcodechallenge',
            name='encrypted_signup_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='communitychatemailcodechallenge',
            name='onboarding_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommunityMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='incomplete', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('adult_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('marketing_opt_in', models.BooleanField(blank=True, null=True)),
                ('personalisation_skipped', models.BooleanField(default=False)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='chat_member_review_queue')],
            },
        ),
        migrations.CreateModel(
            name='CommunityMemberConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('adult_eligibility', '18+ eligibility'), ('terms', 'Terms'), ('code_of_conduct', 'Code of Conduct'), ('marketing_email', 'Marketing email')], max_length=32)),
                ('granted', models.BooleanField()),
                ('policy_version', models.CharField(max_length=80)),
                ('source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='chat_member_consent_history')],
            },
        ),
    ]
