# Generated by Django 4.2.16 on 2026-09-21 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community_chat', '0012_member_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_attention', 'Needs attention')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='community_chat.accountdeletionrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='chat_deletion_task_queue_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='accountdeletiontask',
            constraint=models.UniqueConstraint(fields=('request', 'target'), name='chat_deletion_task_target_uniq'),
        ),
    ]
