# Generated by Django 4.2.16 on 2026-10-05 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community_chat", "0013_account_deletion_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Superadmin"), ("admin", "Admin")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_role_appointment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="chatrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "owner")),
                fields=("role",),
                name="chat_single_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatrole",
            constraint=models.CheckConstraint(
                check=models.Q(("role__in", ("owner", "admin"))), name="chat_valid_role"
            ),
        ),
    ]
