# Generated by Django 4.2.16 on 2026-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_chat', '0014_chat_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusageaccount',
            name='insights_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenusageaccount',
            name='insights_reports',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
