# Generated by Django 4.2.16 on 2026-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Organization',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                        ('competitors', models.JSONField(blank=True, default=list)),
                        ('seed_keywords', models.JSONField(blank=True, default=list, help_text='Seed keywords for content research')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'content_factory_organization',
                    },
                ),
            ],
        ),
    ]
