# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup_updates", "0002_move_legacy_contenttypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackthreadartifact",
            name="classified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slackthreadartifact",
            name="extraction_hints",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="slackthreadartifact",
            name="heuristic_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="slackthreadartifact",
            name="heuristic_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="slackthreadartifact",
            name="needs_extraction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slackthreadartifact",
            name="relevance_label",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("relevant", "Relevant"),
                    ("irrelevant", "Irrelevant"),
                    ("ambiguous", "Ambiguous"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="slackthreadartifact",
            name="relevance_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="slackthreadartifact",
            name="relevance_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name="slackthreadartifact",
            index=models.Index(
                fields=["organization", "relevance_label", "latest_message_at"],
                name="slack_thr_org_rel_latest_idx",
            ),
        ),
    ]
