# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0016_split_startup_updates_app"),
        ("organizations", "0002_organization_company_linkedin_url"),
        ("startup_updates", "0003_slackthreadartifact_relevance_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinearProjectArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("linear_project_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("status_name", models.CharField(blank=True, default="", max_length=100)),
                ("status_type", models.CharField(blank=True, default="", max_length=100)),
                ("health", models.CharField(blank=True, default="", max_length=100)),
                ("progress", models.FloatField(blank=True, null=True)),
                ("scope", models.FloatField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("lead_name", models.CharField(blank=True, default="", max_length=255)),
                ("lead_email", models.CharField(blank=True, default="", max_length=255)),
                ("team_names", models.JSONField(blank=True, default=list)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True, default="", max_length=1024)),
                ("source_record_ids", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("heuristic_score", models.IntegerField(default=0)),
                ("heuristic_reasons", models.JSONField(blank=True, default=list)),
                (
                    "relevance_label",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("relevant", "Relevant"),
                            ("irrelevant", "Irrelevant"),
                            ("ambiguous", "Ambiguous"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("relevance_score", models.FloatField(default=0.0)),
                ("relevance_reason", models.TextField(blank=True, default="")),
                ("needs_extraction", models.BooleanField(default=False)),
                ("extraction_hints", models.JSONField(blank=True, default=dict)),
                ("classified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("hydrated", "Hydrated"),
                            ("processed", "Processed"),
                            ("unsupported", "Unsupported"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_project_artifacts",
                        to="integrations.externalserviceconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_project_artifacts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "integrations_linearprojectartifact",
                "ordering": ["name", "linear_project_id"],
            },
        ),
        migrations.CreateModel(
            name="LinearProjectSelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("linear_project_id", models.CharField(max_length=100)),
                ("project_name", models.CharField(blank=True, default="", max_length=255)),
                ("project_status", models.CharField(blank=True, default="", max_length=100)),
                ("project_health", models.CharField(blank=True, default="", max_length=100)),
                ("selected", models.BooleanField(db_index=True, default=False)),
                ("sync_cursor", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_project_selections",
                        to="integrations.externalserviceconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_project_selections",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_project_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "integrations_linearprojectselection",
                "ordering": ["project_name", "linear_project_id"],
            },
        ),
        migrations.CreateModel(
            name="LinearIssueArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("linear_issue_id", models.CharField(max_length=100)),
                ("identifier", models.CharField(blank=True, default="", max_length=100)),
                ("title", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("state_name", models.CharField(blank=True, default="", max_length=100)),
                ("state_type", models.CharField(blank=True, default="", max_length=100)),
                ("priority", models.FloatField(blank=True, null=True)),
                ("priority_label", models.CharField(blank=True, default="", max_length=100)),
                ("assignee_name", models.CharField(blank=True, default="", max_length=255)),
                ("assignee_email", models.CharField(blank=True, default="", max_length=255)),
                ("team_key", models.CharField(blank=True, default="", max_length=50)),
                ("team_name", models.CharField(blank=True, default="", max_length=255)),
                ("label_names", models.JSONField(blank=True, default=list)),
                ("estimate", models.FloatField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at_linear", models.DateTimeField(blank=True, null=True)),
                ("updated_at_linear", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True, default="", max_length=1024)),
                ("source_record_id", models.CharField(blank=True, default="", max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_issue_artifacts",
                        to="integrations.externalserviceconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_issue_artifacts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="startup_updates.linearprojectartifact",
                    ),
                ),
            ],
            options={
                "db_table": "integrations_linearissueartifact",
                "ordering": ["-updated_at_linear", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LinearProjectUpdateArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("linear_project_update_id", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True, default="")),
                ("health", models.CharField(blank=True, default="", max_length=100)),
                ("author_name", models.CharField(blank=True, default="", max_length=255)),
                ("author_email", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.URLField(blank=True, default="", max_length=1024)),
                ("created_at_linear", models.DateTimeField(blank=True, null=True)),
                ("updated_at_linear", models.DateTimeField(blank=True, null=True)),
                ("source_record_id", models.CharField(blank=True, default="", max_length=255)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_project_update_artifacts",
                        to="integrations.externalserviceconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linear_project_update_artifacts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_updates",
                        to="startup_updates.linearprojectartifact",
                    ),
                ),
            ],
            options={
                "db_table": "integrations_linearprojectupdateartifact",
                "ordering": ["-updated_at_linear", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="linearprojectartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "connection", "linear_project_id"),
                name="linear_project_org_conn_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="linearprojectselection",
            constraint=models.UniqueConstraint(
                fields=("connection", "linear_project_id"),
                name="linear_project_sel_conn_project_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="linearissueartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "connection", "linear_issue_id"),
                name="linear_issue_org_conn_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="linearprojectupdateartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "connection", "linear_project_update_id"),
                name="linear_update_org_conn_id_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="linearprojectartifact",
            index=models.Index(fields=["organization", "extraction_status"], name="linear_proj_org_extract_idx"),
        ),
        migrations.AddIndex(
            model_name="linearprojectartifact",
            index=models.Index(fields=["organization", "status_type", "health"], name="linear_proj_org_state_idx"),
        ),
        migrations.AddIndex(
            model_name="linearprojectartifact",
            index=models.Index(fields=["organization", "relevance_label", "updated_at"], name="linear_proj_org_rel_upd_idx"),
        ),
        migrations.AddIndex(
            model_name="linearprojectselection",
            index=models.Index(fields=["user", "selected"], name="linear_sel_user_selected_idx"),
        ),
        migrations.AddIndex(
            model_name="linearprojectselection",
            index=models.Index(fields=["organization", "selected"], name="linear_sel_org_selected_idx"),
        ),
        migrations.AddIndex(
            model_name="linearissueartifact",
            index=models.Index(fields=["organization", "updated_at_linear"], name="linear_issue_org_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="linearissueartifact",
            index=models.Index(fields=["project", "updated_at_linear"], name="linear_issue_proj_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="linearissueartifact",
            index=models.Index(fields=["organization", "state_type"], name="linear_issue_org_state_idx"),
        ),
        migrations.AddIndex(
            model_name="linearprojectupdateartifact",
            index=models.Index(fields=["organization", "updated_at_linear"], name="linear_update_org_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="linearprojectupdateartifact",
            index=models.Index(fields=["project", "updated_at_linear"], name="linear_update_proj_updated_idx"),
        ),
    ]
