# Generated by Codex on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("startup_updates", "0003_gmailattachmentartifact_last_error"),
        ("startup_updates", "0004_linear_artifacts"),
    ]

    operations = []
