# Generated by Django 4.2.16 on 2026-05-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_updates', '0007_startupprofile_organization_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailmessageartifact',
            name='relevance_label',
            field=models.CharField(choices=[('pending', 'Pending'), ('update_worthy', 'Update Worthy'), ('relevant', 'Relevant'), ('background', 'Background'), ('irrelevant', 'Irrelevant'), ('ambiguous', 'Ambiguous')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='linearprojectartifact',
            name='relevance_label',
            field=models.CharField(choices=[('pending', 'Pending'), ('update_worthy', 'Update Worthy'), ('relevant', 'Relevant'), ('background', 'Background'), ('irrelevant', 'Irrelevant'), ('ambiguous', 'Ambiguous')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='slackthreadartifact',
            name='relevance_label',
            field=models.CharField(choices=[('pending', 'Pending'), ('update_worthy', 'Update Worthy'), ('relevant', 'Relevant'), ('background', 'Background'), ('irrelevant', 'Irrelevant'), ('ambiguous', 'Ambiguous')], db_index=True, default='pending', max_length=20),
        ),
    ]
