# Generated by Django 4.2.16 on 2026-06-09 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0018_google_analytics_provider_choice'),
        ('startup_updates', '0011_startupprofile_company_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsPropertySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=64)),
                ('property_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_id', models.CharField(blank=True, default='', max_length=64)),
                ('account_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('selected', models.BooleanField(db_index=True, default=False)),
                ('sync_cursor', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_analytics_property_selections', to='integrations.externalserviceconnection')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_analytics_property_selections', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_analytics_property_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_googleanalyticspropertyselection',
                'ordering': ['property_display_name', 'property_id'],
                'indexes': [models.Index(fields=['user', 'selected'], name='ga_prop_sel_user_selected_idx'), models.Index(fields=['organization', 'selected'], name='ga_prop_sel_org_selected_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='googleanalyticspropertyselection',
            constraint=models.UniqueConstraint(fields=('connection', 'property_id'), name='ga_prop_sel_conn_property_uniq'),
        ),
    ]
