# Generated by Django 4.2.16 on 2026-06-15 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0019_luma_provider_choice'),
        ('startup_updates', '0012_googleanalyticspropertyselection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LumaEventSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128)),
                ('event_name', models.CharField(blank=True, default='', max_length=255)),
                ('event_url', models.CharField(blank=True, default='', max_length=512)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('selected', models.BooleanField(db_index=True, default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luma_event_selections', to='integrations.externalserviceconnection')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luma_event_selections', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luma_event_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_lumaeventselection',
                'ordering': ['-start_at', 'event_name', 'event_id'],
                'indexes': [models.Index(fields=['user', 'selected'], name='luma_event_sel_user_sel_idx'), models.Index(fields=['organization', 'selected'], name='luma_event_sel_org_sel_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lumaeventselection',
            constraint=models.UniqueConstraint(fields=('connection', 'event_id'), name='luma_event_sel_conn_event_uniq'),
        ),
    ]
