# Generated by Django 4.2.16 on 2026-07-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_updates', '0013_luma_event_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyupdatedraft',
            name='ready_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
