# Generated by Django 4.2.16 on 2026-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_updates', '0015_backfill_monthly_update_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstartupbinding',
            name='monthly_updates_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='userstartupbinding',
            index=models.Index(fields=['monthly_updates_enabled'], name='startup_bind_monthly_idx'),
        ),
    ]
