# Generated by Codex on 2026-07-02

from django.db import migrations, models

import vibe_raising.audience_visibility


def backfill_existing_ready_updates(apps, schema_editor):
    MonthlyUpdateDraft = apps.get_model("startup_updates", "MonthlyUpdateDraft")
    MonthlyUpdateDraft.objects.filter(
        status="ready",
        published_at__isnull=True,
    ).update(published_at=models.F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("startup_updates", "0016_userstartupbinding_monthly_updates_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyupdatedraft",
            name="audience_visibility",
            field=models.JSONField(
                blank=True,
                default=vibe_raising.audience_visibility.default_audience_visibility,
            ),
        ),
        migrations.AddField(
            model_name="monthlyupdatedraft",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_existing_ready_updates, migrations.RunPython.noop),
    ]
