# Generated by Django 5.2.4 on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startup_updates", "0017_userstartupbinding_coworking_discount_eligible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyUpdateReminderDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reminder_kind", models.CharField(choices=[("seven_day", "Seven days before expiry"), ("one_day", "One day before expiry")], max_length=20)),
                ("reminder_date", models.DateField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sending", "Sending"), ("sent", "Sent"), ("drafted", "Queued as Customer.io draft"), ("unknown", "Delivery unknown"), ("suppressed", "Suppressed")], db_index=True, default="pending", max_length=20)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("template_id", models.CharField(max_length=255)),
                ("target_snapshot", models.JSONField(blank=True, default=list)),
                ("customerio_delivery_id", models.CharField(blank=True, default="", max_length=255)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_update_reminder_deliveries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "integrations_monthlyupdatereminderdelivery",
                "ordering": ["-reminder_date", "user_id", "reminder_kind"],
                "indexes": [models.Index(fields=["reminder_date", "status"], name="mon_rem_date_status_idx"), models.Index(fields=["user", "reminder_date"], name="mon_rem_user_date_idx")],
                "constraints": [models.UniqueConstraint(fields=("user", "reminder_kind", "reminder_date"), name="monthly_reminder_user_kind_date_uniq")],
            },
        ),
    ]
