# Generated by Django 4.2.16 on 2026-09-09 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_company_linkedin_url'),
        ('startup_updates', '0021_linear_project_member_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEvidenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='reporting_config_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='reporting_timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.CreateModel(
            name='MonthlyUpdateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('audience', models.CharField(default='private', max_length=16)),
                ('content_hash', models.CharField(max_length=64)),
                ('structured_memo', models.JSONField(default=dict)),
                ('rendered_markdown', models.TextField(blank=True, default='')),
                ('validation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='startup_updates.monthlyupdatedraft')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startup_updates.monthlyevidencesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyUpdateApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64)),
                ('audience_visibility', models.JSONField(default=list)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='startup_updates.monthlyupdaterevision')),
            ],
        ),
        migrations.AddField(
            model_name='monthlyupdatedraft',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='startup_updates.monthlyupdaterevision'),
        ),
        migrations.AddField(
            model_name='monthlyupdatedraft',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='startup_updates.monthlyupdaterevision'),
        ),
        migrations.AddConstraint(
            model_name='monthlyupdaterevision',
            constraint=models.UniqueConstraint(fields=('draft', 'number'), name='monthly_revision_draft_number'),
        ),
        migrations.AddConstraint(
            model_name='monthlyevidencesnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'content_hash'), name='monthly_snapshot_org_hash'),
        ),
    ]
