# Generated by Django 4.2.16 on 2026-09-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_updates', '0023_independent_update_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='progress_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
