from django.urls import path

from . import service_views as views

urlpatterns = [
    path('service/config/', views.ContentFactoryServiceConfigView.as_view(), name='content_factory_service_config'),
    path('service/config', views.ContentFactoryServiceConfigView.as_view(), name='content_factory_service_config_no_slash'),
    path('org/config/', views.ContentFactoryOrgConfigView.as_view(), name='content_factory_org_config'),
    path('org/config', views.ContentFactoryOrgConfigView.as_view(), name='content_factory_org_config_no_slash'),
    path('healing-records/', views.ContentFactoryHealingRecordView.as_view(), name='content_factory_healing_records'),
    path('healing-records', views.ContentFactoryHealingRecordView.as_view(), name='content_factory_healing_records_no_slash'),
    path('learning-entries/', views.ContentFactoryLearningEntryView.as_view(), name='content_factory_learning_entries'),
    path('learning-entries', views.ContentFactoryLearningEntryView.as_view(), name='content_factory_learning_entries_no_slash'),
    path('org/components/', views.ContentFactoryComponentsView.as_view(), name='content_factory_components'),
    path('org/components', views.ContentFactoryComponentsView.as_view(), name='content_factory_components_no_slash'),
    path('org/components/<str:name>/', views.ContentFactoryComponentDetailView.as_view(), name='content_factory_component_detail'),
    path('org/components/<str:name>', views.ContentFactoryComponentDetailView.as_view(), name='content_factory_component_detail_no_slash'),
    path('org/github-status/', views.ContentFactoryGitHubStatusView.as_view(), name='content_factory_github_status'),
    path('org/github-status', views.ContentFactoryGitHubStatusView.as_view(), name='content_factory_github_status_no_slash'),
    path('github/reconnect/', views.ContentFactoryGitHubReconnectView.as_view(), name='content_factory_github_reconnect'),
    path('github/reconnect', views.ContentFactoryGitHubReconnectView.as_view(), name='content_factory_github_reconnect_no_slash'),
    path('oauth/initiate/', views.ContentFactoryOAuthInitiateView.as_view(), name='content_factory_oauth_initiate'),
    path('oauth/initiate', views.ContentFactoryOAuthInitiateView.as_view(), name='content_factory_oauth_initiate_no_slash'),
    path('org/connect-github/', views.ContentFactoryConnectGitHubView.as_view(), name='content_factory_connect_github'),
    path('org/connect-github', views.ContentFactoryConnectGitHubView.as_view(), name='content_factory_connect_github_no_slash'),
    path('orgs/domains/', views.ContentFactoryOrgDomainsView.as_view(), name='content_factory_org_domains'),
    path('orgs/domains', views.ContentFactoryOrgDomainsView.as_view(), name='content_factory_org_domains_no_slash'),
    path('scheduled-discovery/replay/', views.ScheduledDiscoveryReplayView.as_view(), name='content_factory_scheduled_discovery_replay'),
    path('scheduled-discovery/replay', views.ScheduledDiscoveryReplayView.as_view(), name='content_factory_scheduled_discovery_replay_no_slash'),
    path('research-automations/', views.ResearchAutomationView.as_view(), name='content_factory_research_automations'),
    path('research-automations', views.ResearchAutomationView.as_view(), name='content_factory_research_automations_no_slash'),
    path('automation-actions/', views.ResearchAutomationActionView.as_view(), name='content_factory_automation_action'),
    path('automation-actions', views.ResearchAutomationActionView.as_view(), name='content_factory_automation_action_no_slash'),
    path('notification-channels/verify-email/', views.NotificationChannelEmailVerifyView.as_view(), name='content_factory_notification_channel_verify'),
    path('notification-channels/verify-email', views.NotificationChannelEmailVerifyView.as_view(), name='content_factory_notification_channel_verify_no_slash'),
    path('notification-webhooks/whatsapp/', views.ResearchAutomationWhatsAppWebhookView.as_view(), name='content_factory_whatsapp_webhook'),
    path('notification-webhooks/whatsapp', views.ResearchAutomationWhatsAppWebhookView.as_view(), name='content_factory_whatsapp_webhook_no_slash'),
    path('callback/', views.ContentFactoryCallbackView.as_view(), name='content_factory_callback'),
    path('callback', views.ContentFactoryCallbackView.as_view(), name='content_factory_callback_no_slash'),
    path('github/webhook/', views.ContentFactoryGitHubWebhookView.as_view(), name='content_factory_github_webhook'),
    path('github/webhook', views.ContentFactoryGitHubWebhookView.as_view(), name='content_factory_github_webhook_no_slash'),
    path('token/', views.ContentFactoryTokenView.as_view(), name='content_factory_token'),
    path('token', views.ContentFactoryTokenView.as_view(), name='content_factory_token_no_slash'),
    path('runs/<str:run_id>/', views.ContentFactoryRunView.as_view(), name='content_factory_run'),
    path('runs/<str:run_id>', views.ContentFactoryRunView.as_view(), name='content_factory_run_no_slash'),
    path('runs/<str:run_id>/valley-jobs/', views.ContentFactoryRunValleyJobView.as_view(), name='content_factory_run_valley_jobs'),
    path('runs/<str:run_id>/valley-jobs', views.ContentFactoryRunValleyJobView.as_view(), name='content_factory_run_valley_jobs_no_slash'),
    path('runs/<str:run_id>/preview/', views.ContentFactoryRunPreviewView.as_view(), name='content_factory_run_preview'),
    path('runs/<str:run_id>/preview', views.ContentFactoryRunPreviewView.as_view(), name='content_factory_run_preview_no_slash'),
    path('runs/<str:run_id>/artifacts/', views.ContentFactoryRunArtifactsView.as_view(), name='content_factory_run_artifacts'),
    path('runs/<str:run_id>/artifacts', views.ContentFactoryRunArtifactsView.as_view(), name='content_factory_run_artifacts_no_slash'),
    path('runs/<str:run_id>/<str:action>/', views.ContentFactoryRunControlView.as_view(), name='content_factory_run_control'),
    path('runs/<str:run_id>/<str:action>', views.ContentFactoryRunControlView.as_view(), name='content_factory_run_control_no_slash'),
]
