from django.urls import path

from .vibe_marketing_views import (
    VibeMarketingAutofillView,
    VibeMarketingArticleView,
    VibeMarketingArticleSystemSetupView,
    VibeMarketingArticleSystemRevisionsView,
    VibeMarketingAbnLookupView,
    VibeMarketingBaselineGoogleRefreshView,
    VibeMarketingBaselineSkipView,
    VibeMarketingBaselineView,
    VibeMarketingBootstrapView,
    VibeMarketingDailyReplayView,
    VibeMarketingDiscoveryView,
    VibeMarketingGitHubConnectView,
    VibeMarketingGitHubReposView,
    VibeMarketingLocationLookupView,
    VibeMarketingRunArtifactsView,
    VibeMarketingRunCommentDetailView,
    VibeMarketingRunCommentsAcceptRevisionView,
    VibeMarketingRunCommentsSubmitView,
    VibeMarketingRunCommentsView,
    VibeMarketingRunControlView,
    VibeMarketingRunLivePreviewProxyView,
    VibeMarketingRunLivePreviewResourceView,
    VibeMarketingRunLivePreviewView,
    VibeMarketingRunView,
    VibeMarketingScanView,
    VibeMarketingSettingsView,
    VibeMarketingTopicFeedbackRestoreView,
    VibeMarketingTopicFeedbackView,
)


urlpatterns = [
    path("bootstrap/", VibeMarketingBootstrapView.as_view(), name="vibe-marketing-bootstrap"),
    path("settings", VibeMarketingSettingsView.as_view(), name="vibe-marketing-settings-no-slash"),
    path("settings/", VibeMarketingSettingsView.as_view(), name="vibe-marketing-settings"),
    path("autofill", VibeMarketingAutofillView.as_view(), name="vibe-marketing-autofill-no-slash"),
    path("autofill/", VibeMarketingAutofillView.as_view(), name="vibe-marketing-autofill"),
    path("baseline", VibeMarketingBaselineView.as_view(), name="vibe-marketing-baseline-no-slash"),
    path("baseline/", VibeMarketingBaselineView.as_view(), name="vibe-marketing-baseline"),
    path("baseline/skip", VibeMarketingBaselineSkipView.as_view(), name="vibe-marketing-baseline-skip-no-slash"),
    path("baseline/skip/", VibeMarketingBaselineSkipView.as_view(), name="vibe-marketing-baseline-skip"),
    path("baseline/google-refresh", VibeMarketingBaselineGoogleRefreshView.as_view(), name="vibe-marketing-baseline-google-refresh-no-slash"),
    path("baseline/google-refresh/", VibeMarketingBaselineGoogleRefreshView.as_view(), name="vibe-marketing-baseline-google-refresh"),
    path("github/connect", VibeMarketingGitHubConnectView.as_view(), name="vibe-marketing-github-connect-no-slash"),
    path("github/connect/", VibeMarketingGitHubConnectView.as_view(), name="vibe-marketing-github-connect"),
    path("github/repos", VibeMarketingGitHubReposView.as_view(), name="vibe-marketing-github-repos-no-slash"),
    path("github/repos/", VibeMarketingGitHubReposView.as_view(), name="vibe-marketing-github-repos"),
    path("scan", VibeMarketingScanView.as_view(), name="vibe-marketing-scan-no-slash"),
    path("scan/", VibeMarketingScanView.as_view(), name="vibe-marketing-scan"),
    path("article-system-setup", VibeMarketingArticleSystemSetupView.as_view(), name="vibe-marketing-article-system-setup-no-slash"),
    path("article-system-setup/", VibeMarketingArticleSystemSetupView.as_view(), name="vibe-marketing-article-system-setup"),
    path("discovery", VibeMarketingDiscoveryView.as_view(), name="vibe-marketing-discovery-no-slash"),
    path("discovery/", VibeMarketingDiscoveryView.as_view(), name="vibe-marketing-discovery"),
    path("article", VibeMarketingArticleView.as_view(), name="vibe-marketing-article-no-slash"),
    path("article/", VibeMarketingArticleView.as_view(), name="vibe-marketing-article"),
    path("topic-feedback", VibeMarketingTopicFeedbackView.as_view(), name="vibe-marketing-topic-feedback-no-slash"),
    path("topic-feedback/", VibeMarketingTopicFeedbackView.as_view(), name="vibe-marketing-topic-feedback"),
    path(
        "topic-feedback/<uuid:feedback_id>/restore",
        VibeMarketingTopicFeedbackRestoreView.as_view(),
        name="vibe-marketing-topic-feedback-restore-no-slash",
    ),
    path(
        "topic-feedback/<uuid:feedback_id>/restore/",
        VibeMarketingTopicFeedbackRestoreView.as_view(),
        name="vibe-marketing-topic-feedback-restore",
    ),
    path("lookups/locations", VibeMarketingLocationLookupView.as_view(), name="vibe-marketing-location-lookup-no-slash"),
    path("lookups/locations/", VibeMarketingLocationLookupView.as_view(), name="vibe-marketing-location-lookup"),
    path("lookups/abns", VibeMarketingAbnLookupView.as_view(), name="vibe-marketing-abn-lookup-no-slash"),
    path("lookups/abns/", VibeMarketingAbnLookupView.as_view(), name="vibe-marketing-abn-lookup"),
    path("runs/<str:run_id>", VibeMarketingRunView.as_view(), name="vibe-marketing-run-no-slash"),
    path("runs/<str:run_id>/", VibeMarketingRunView.as_view(), name="vibe-marketing-run"),
    path("runs/<str:run_id>/artifacts", VibeMarketingRunArtifactsView.as_view(), name="vibe-marketing-run-artifacts-no-slash"),
    path("runs/<str:run_id>/artifacts/", VibeMarketingRunArtifactsView.as_view(), name="vibe-marketing-run-artifacts"),
    path("runs/<str:run_id>/live-preview", VibeMarketingRunLivePreviewView.as_view(), name="vibe-marketing-run-live-preview-no-slash"),
    path("runs/<str:run_id>/live-preview/", VibeMarketingRunLivePreviewView.as_view(), name="vibe-marketing-run-live-preview"),
    path("runs/<str:run_id>/live-preview/proxy/", VibeMarketingRunLivePreviewProxyView.as_view(), name="vibe-marketing-run-live-preview-proxy-root"),
    path("runs/<str:run_id>/live-preview/proxy/<path:proxy_path>", VibeMarketingRunLivePreviewProxyView.as_view(), name="vibe-marketing-run-live-preview-proxy"),
    path("runs/<str:run_id>/live-preview/resource", VibeMarketingRunLivePreviewResourceView.as_view(), name="vibe-marketing-run-live-preview-resource-no-slash"),
    path("runs/<str:run_id>/live-preview/resource/", VibeMarketingRunLivePreviewResourceView.as_view(), name="vibe-marketing-run-live-preview-resource"),
    path("runs/<str:run_id>/article-system-revisions", VibeMarketingArticleSystemRevisionsView.as_view(), name="vibe-marketing-run-article-system-revisions-no-slash"),
    path("runs/<str:run_id>/article-system-revisions/", VibeMarketingArticleSystemRevisionsView.as_view(), name="vibe-marketing-run-article-system-revisions"),
    path("runs/<str:run_id>/comments", VibeMarketingRunCommentsView.as_view(), name="vibe-marketing-run-comments-no-slash"),
    path("runs/<str:run_id>/comments/", VibeMarketingRunCommentsView.as_view(), name="vibe-marketing-run-comments"),
    path("runs/<str:run_id>/comments/submit", VibeMarketingRunCommentsSubmitView.as_view(), name="vibe-marketing-run-comments-submit-no-slash"),
    path("runs/<str:run_id>/comments/submit/", VibeMarketingRunCommentsSubmitView.as_view(), name="vibe-marketing-run-comments-submit"),
    path("runs/<str:run_id>/comments/accept-revision", VibeMarketingRunCommentsAcceptRevisionView.as_view(), name="vibe-marketing-run-comments-accept-revision-no-slash"),
    path("runs/<str:run_id>/comments/accept-revision/", VibeMarketingRunCommentsAcceptRevisionView.as_view(), name="vibe-marketing-run-comments-accept-revision"),
    path("runs/<str:run_id>/comments/<uuid:comment_id>", VibeMarketingRunCommentDetailView.as_view(), name="vibe-marketing-run-comment-detail-no-slash"),
    path("runs/<str:run_id>/comments/<uuid:comment_id>/", VibeMarketingRunCommentDetailView.as_view(), name="vibe-marketing-run-comment-detail"),
    path("runs/<str:run_id>/<str:action>", VibeMarketingRunControlView.as_view(), name="vibe-marketing-run-control-no-slash"),
    path("runs/<str:run_id>/<str:action>/", VibeMarketingRunControlView.as_view(), name="vibe-marketing-run-control"),
    path("daily/replay", VibeMarketingDailyReplayView.as_view(), name="vibe-marketing-daily-replay-no-slash"),
    path("daily/replay/", VibeMarketingDailyReplayView.as_view(), name="vibe-marketing-daily-replay"),
]
