#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

INSPECTION_FILE="${1:-$(inspection_file)}"
DB_ACCESS_MODE="${DB_ACCESS_MODE:-readonly}"
LOCAL_DB_PORT="${LOCAL_DB_TUNNEL_PORT:-15432}"
MLAI_PORT="${LOCAL_MLAI_PORT:-8000}"
CONTENT_FACTORY_PORT="${LOCAL_CONTENT_FACTORY_PORT:-8001}"

require_file "$INSPECTION_FILE"

MLAI_ROOT="$(local_live_db_repo_root)"
CONTENT_FACTORY_ROOT="$(content_factory_repo_root)"

python3 - "$INSPECTION_FILE" "$MLAI_ROOT" "$CONTENT_FACTORY_ROOT" "$DB_ACCESS_MODE" "$LOCAL_DB_PORT" "$MLAI_PORT" "$CONTENT_FACTORY_PORT" <<'PY'
import json
import secrets
import sys
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def apply_readonly(url: str) -> str:
    parts = urlsplit(url)
    query = parse_qsl(parts.query, keep_blank_values=True)
    if not any(
        key == "options" and "default_transaction_read_only" in value
        for key, value in query
    ):
        query.append(("options", "-c default_transaction_read_only=on"))
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment))


def replace_host(url: str, host: str, port: int) -> str:
    parts = urlsplit(url)
    userinfo = ""
    if parts.username:
        userinfo = parts.username
        if parts.password:
            userinfo = f"{userinfo}:{parts.password}"
        userinfo = f"{userinfo}@"
    new_netloc = f"{userinfo}{host}:{port}"
    return urlunsplit((parts.scheme, new_netloc, parts.path, parts.query, parts.fragment))


inspection = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
mlai_root = Path(sys.argv[2])
content_factory_root = Path(sys.argv[3])
db_access_mode = sys.argv[4]
local_db_port = int(sys.argv[5])
mlai_port = int(sys.argv[6])
content_factory_port = int(sys.argv[7])

mode = inspection.get("mode")
database_url = inspection.get("database_url") or ""
if mode not in {"external_live_db", "tunneled_live_db"}:
    raise SystemExit(f"Unsupported inspection mode: {mode!r}")
if not database_url:
    raise SystemExit("Inspection file does not contain DATABASE_URL")

mlai_env_path = mlai_root / ".env.local-docker"
content_factory_env_path = content_factory_root / ".env.local-docker"
existing_mlai = parse_env_file(mlai_env_path)
existing_content_factory = parse_env_file(content_factory_env_path)

local_mlai_api_key = (
    existing_mlai.get("ROO_API_KEY")
    or existing_mlai.get("INTERNAL_API_KEY")
    or existing_content_factory.get("MLAI_API_KEY")
    or existing_content_factory.get("MLAI_BACKEND_API_KEY")
    or secrets.token_hex(32)
)
local_content_factory_api_key = (
    existing_mlai.get("CONTENT_FACTORY_API_KEY")
    or existing_content_factory.get("CONTENT_FACTORY_API_KEY")
    or secrets.token_hex(32)
)

resolved_database_url = database_url
resolved_ssl = "True" if inspection.get("database_ssl_require") else "False"
if mode == "tunneled_live_db":
    resolved_database_url = replace_host(database_url, "host.docker.internal", local_db_port)
    resolved_ssl = "False"

if db_access_mode == "readonly":
    resolved_database_url = apply_readonly(resolved_database_url)
elif db_access_mode != "readwrite":
    raise SystemExit("DB_ACCESS_MODE must be either 'readonly' or 'readwrite'")

mlai_env_lines = [
    "# Generated by scripts/local-live-db/write-local-env.sh",
    f"LIVE_DB_MODE={mode}",
    f"DB_ACCESS_MODE={db_access_mode}",
    f"LIVE_DB_REMOTE={inspection.get('remote_host', '')}",
    f"DATABASE_URL={resolved_database_url}",
    f"DATABASE_SSL_REQUIRE={resolved_ssl}",
    "DEFAULT_FRONTEND_URL=http://localhost:3000",
    "MEDHACK_URL=http://localhost:3000",
    f"CONTENT_FACTORY_URL=http://host.docker.internal:{content_factory_port}",
    f"CONTENT_FACTORY_API_KEY={local_content_factory_api_key}",
    "VALLEY_HARNESS_URL=http://valley-api:8080",
    f"ROO_API_KEY={local_mlai_api_key}",
    f"INTERNAL_API_KEY={local_mlai_api_key}",
    "ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,host.docker.internal",
    f"CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:{mlai_port}",
    f"GOOGLE_OAUTH_REDIRECT_URI=http://localhost:{mlai_port}/integrations/callback/google",
    f"GITHUB_OAUTH_REDIRECT_URI=http://localhost:{mlai_port}/integrations/callback/github",
]

content_factory_env_lines = [
    "# Generated by ../mlai-backend/scripts/local-live-db/write-local-env.sh",
    f"MLAI_BACKEND_URL=http://host.docker.internal:{mlai_port}",
    f"MLAI_API_KEY={local_mlai_api_key}",
    f"MLAI_BACKEND_API_KEY={local_mlai_api_key}",
    f"CONTENT_FACTORY_API_KEY={local_content_factory_api_key}",
    f"CONTENT_FACTORY_URL=http://host.docker.internal:{content_factory_port}",
    "CONTENT_FACTORY_ALLOW_UNAUTH_LOCAL_DEV=false",
    "CELERY_BROKER_URL=redis://redis:6379/0",
    "CELERY_RESULT_BACKEND=redis://redis:6379/0",
    "RUN_ARTIFACT_ROOT=/tmp/content-factory-runs",
]

mlai_env_path.write_text("\n".join(mlai_env_lines) + "\n", encoding="utf-8")
content_factory_env_path.write_text("\n".join(content_factory_env_lines) + "\n", encoding="utf-8")

print(f"Wrote {mlai_env_path}")
print(f"Wrote {content_factory_env_path}")
print(f"Mode: {mode}")
print(f"DB access mode: {db_access_mode}")
PY
