"""
Django settings for medhack_backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import subprocess
from datetime import timedelta
from corsheaders.defaults import default_headers

import dj_database_url
from django.db.backends.signals import connection_created
load_dotenv()


def _env_is_true(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _resolve_app_env(*, debug: bool, raw_env: str = "") -> str:
    if raw_env:
        return raw_env
    return "local" if debug else "production"


def _resolve_app_release(base_dir: str) -> str:
    for env_name in (
        "APP_RELEASE",
        "GIT_SHA",
        "COMMIT_SHA",
        "RENDER_GIT_COMMIT",
        "SOURCE_VERSION",
        "VERCEL_GIT_COMMIT_SHA",
    ):
        raw = os.getenv(env_name, "").strip()
        if raw:
            return raw[:12]

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=base_dir,
            capture_output=True,
            text=True,
            check=False,
        )
    except Exception:
        return "unknown"

    if result.returncode == 0:
        value = (result.stdout or "").strip()
        if value:
            return value

    return "unknown"


def _env_list(name: str, default: list[str]) -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        return default
    return [item.strip() for item in raw.replace(",", " ").split() if item.strip()]


def _env_first(*names: str, default: str = "") -> str:
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vh##sgy=^gqeoyqjm0*%23zewxuw=&l&-dv6%%k*$sw7#+vzp+'

# SECURITY WARNING: don't run with debug turned on in production!
RAW_APP_ENV = os.getenv('APP_ENV', '').strip().lower()
DEBUG_DEFAULT = False if RAW_APP_ENV in {'production', 'prod'} else True
DEBUG = _env_is_true('DEBUG', DEBUG_DEFAULT)
APP_ENV = _resolve_app_env(debug=DEBUG, raw_env=RAW_APP_ENV)
APP_RELEASE = _resolve_app_release(BASE_DIR)
IS_LOCAL_ENV = APP_ENV in {'local', 'development', 'dev', 'test'}
IS_PRODUCTION_ENV = not IS_LOCAL_ENV

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')
ALLOWED_HOSTS.extend(['.localhost'])

# Disable trailing slash redirect for API endpoints
APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hospital',
    'organizations',
    'workflow_runs',
    'startup_updates',
    'content_factory',
    'founder_tools',
    'core',
    'esafety',
    'vibe_raising',
    'jobs',
    "rest_framework",
    "roo",

    "integrations",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.RequestLoggingMiddleware',
    'core.middleware.PointsEndpointTimeoutMiddleware',
]

ROOT_URLCONF = 'mlai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mlai.wsgi.application'

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:5173,https://mlai.au,https://www.mlai.au').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://localhost:5173,https://mlai.au,https://www.mlai.au').split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (*default_headers, "x-request-id")
CORS_EXPOSE_HEADERS = ["X-Request-ID"]


database_url = os.getenv('DATABASE_URL')
is_sqlite_database = (database_url or '').startswith('sqlite:')
database_conn_max_age = 0 if is_sqlite_database else 600
SQLITE_TIMEOUT_SECONDS = int(os.getenv('SQLITE_TIMEOUT_SECONDS', '30'))
SQLITE_BUSY_TIMEOUT_MS = int(os.getenv('SQLITE_BUSY_TIMEOUT_MS', str(SQLITE_TIMEOUT_SECONDS * 1000)))
SQLITE_ENABLE_WAL = _env_is_true('SQLITE_ENABLE_WAL', True)
SQLITE_LOCK_RETRY_AFTER_SECONDS = int(os.getenv('SQLITE_LOCK_RETRY_AFTER_SECONDS', '2'))

# Parse database configuration from $DATABASE_URL
default_config = dj_database_url.config(
    default=os.environ.get('DATABASE_URL'),
    conn_max_age=database_conn_max_age,
    ssl_require=os.getenv('DATABASE_SSL_REQUIRE', 'False') == 'True'
)

if default_config.get('ENGINE') == 'django.db.backends.sqlite3':
    sqlite_options = default_config.setdefault('OPTIONS', {})
    sqlite_options.setdefault('timeout', SQLITE_TIMEOUT_SECONDS)

DATABASES = {
    'default': default_config
}


def _configure_sqlite_connection(sender, connection, **kwargs):
    if connection.vendor != 'sqlite':
        return
    try:
        with connection.cursor() as cursor:
            cursor.execute(f'PRAGMA busy_timeout={SQLITE_BUSY_TIMEOUT_MS}')
            if SQLITE_ENABLE_WAL and connection.settings_dict.get('NAME') != ':memory:':
                cursor.execute('PRAGMA journal_mode=WAL')
            cursor.execute('PRAGMA synchronous=NORMAL')
    except Exception:
        # SQLite pragmas are local-development hardening only; never block app boot.
        return


connection_created.connect(_configure_sqlite_connection)

POINTS_STATEMENT_TIMEOUT_MS = int(os.getenv('POINTS_STATEMENT_TIMEOUT_MS', '12000'))
POINTS_LOCK_TIMEOUT_MS = int(os.getenv('POINTS_LOCK_TIMEOUT_MS', '5000'))
GMAIL_API_HTTP_TIMEOUT_SECONDS = float(os.getenv('GMAIL_API_HTTP_TIMEOUT_SECONDS', '4'))
GMAIL_METADATA_PAGE_MAX_RESULTS = int(os.getenv('GMAIL_METADATA_PAGE_MAX_RESULTS', '5'))


AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'hospital.authentication.CustomJWTAuthentication',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Rate limit for MedHack endpoints
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_COOKIE': 'access_token',  # Cookie name for access token
    'AUTH_COOKIE_REFRESH': 'refresh_token',  # Cookie name for refresh token
    'AUTH_COOKIE_SECURE': not DEBUG,  # Set to True in production with HTTPS
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

DJANGO_LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'vibe_raising': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'integrations': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'hospital.authentication': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
    },
}

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if IS_PRODUCTION_ENV:
    try:
        from .settings_prod import *
    except ImportError:
        pass

# App URLs
DEFAULT_FRONTEND_URL = os.getenv('DEFAULT_FRONTEND_URL') or (
    'http://localhost:5173' if IS_LOCAL_ENV else 'https://mlai.au'
)
DEFAULT_BACKEND_URL = os.getenv('DEFAULT_BACKEND_URL') or (
    'http://localhost:8000' if IS_LOCAL_ENV else 'https://api.mlai.au'
)
MEDHACK_URL = os.getenv('MEDHACK_URL') or DEFAULT_FRONTEND_URL
ESAFETY_URL = os.getenv('ESAFETY_URL') or DEFAULT_FRONTEND_URL
VIBE_RAISING_URL = os.getenv('VIBE_RAISING_URL') or DEFAULT_FRONTEND_URL
FOUNDER_TOOLS_URL = os.getenv('FOUNDER_TOOLS_URL') or VIBE_RAISING_URL
CONTENT_FACTORY_FRONTEND_URL = os.getenv('CONTENT_FACTORY_FRONTEND_URL') or DEFAULT_FRONTEND_URL
CONTENT_FACTORY_URL = os.getenv('CONTENT_FACTORY_URL') or (
    'http://localhost:8001' if IS_LOCAL_ENV else ''
)
CONTENT_FACTORY_PREVIEW_BASE_URL = os.getenv('CONTENT_FACTORY_PREVIEW_BASE_URL', '')
CONTENT_FACTORY_PREVIEW_LINK_TTL_SECONDS = int(
    os.getenv('CONTENT_FACTORY_PREVIEW_LINK_TTL_SECONDS', str(7 * 24 * 60 * 60))
)
CONTENT_FACTORY_LIVE_PREVIEW_START_READ_TIMEOUT_SECONDS = int(
    os.getenv('CONTENT_FACTORY_LIVE_PREVIEW_START_READ_TIMEOUT_SECONDS', '20')
)
CONTENT_FACTORY_API_KEY = os.getenv('CONTENT_FACTORY_API_KEY')
CONTENT_FACTORY_DEFAULT_ARTICLE_DELIVERY_MODE = os.getenv(
    'CONTENT_FACTORY_DEFAULT_ARTICLE_DELIVERY_MODE',
    'review_draft',
)
SCHEDULED_DISCOVERY_TIMEZONE = os.getenv('SCHEDULED_DISCOVERY_TIMEZONE', 'Australia/Melbourne')
SCHEDULED_DISCOVERY_CHANNEL_NAME = os.getenv('SCHEDULED_DISCOVERY_CHANNEL_NAME', 'vibe-marketing')
SCHEDULED_DISCOVERY_SLOT_MINUTES = int(os.getenv('SCHEDULED_DISCOVERY_SLOT_MINUTES', '15'))
SCHEDULED_DISCOVERY_MAX_TARGETS = int(os.getenv('SCHEDULED_DISCOVERY_MAX_TARGETS', '20'))
JOBS_PUBLIC_BASE_URL = os.getenv('JOBS_PUBLIC_BASE_URL', DEFAULT_BACKEND_URL)
JOBS_TRIGGER_TOKEN = os.getenv('JOBS_TRIGGER_TOKEN', '')
JOBS_SCHEDULER_ENABLED = _env_is_true('JOBS_SCHEDULER_ENABLED', True)
JOBS_SCHEDULE_TIMEZONE = os.getenv('JOBS_SCHEDULE_TIMEZONE', 'Australia/Melbourne')
JOBS_SCHEDULE_HOUR = int(os.getenv('JOBS_SCHEDULE_HOUR', '7'))
JOBS_SCHEDULE_MINUTE = int(os.getenv('JOBS_SCHEDULE_MINUTE', '0'))
JOBS_RETRY_ATTEMPTS = int(os.getenv('JOBS_RETRY_ATTEMPTS', '3'))
JOBS_RETRY_DELAY_SECONDS = int(os.getenv('JOBS_RETRY_DELAY_SECONDS', '300'))
JOBS_FAILURE_STOP_AFTER_DAYS = int(os.getenv('JOBS_FAILURE_STOP_AFTER_DAYS', '3'))
JOBS_SCHEDULER_POST_TO_SLACK = _env_is_true('JOBS_SCHEDULER_POST_TO_SLACK', True)
JOBS_SCHEDULER_POST_TO_NOTION = _env_is_true('JOBS_SCHEDULER_POST_TO_NOTION', True)
JOBS_SCHEDULER_MAX_PAGES = int(os.getenv('JOBS_SCHEDULER_MAX_PAGES', '1'))
JOBS_SCHEDULER_PER_KEYWORD_LIMIT = int(os.getenv('JOBS_SCHEDULER_PER_KEYWORD_LIMIT', '5'))
JOBS_SCRAPE_HEADLESS = _env_is_true('JOBS_SCRAPE_HEADLESS', True)
JOBS_SEEK_MAX_PAGES = int(os.getenv('JOBS_SEEK_MAX_PAGES', '3'))
JOBS_SEEK_PER_KEYWORD_LIMIT = int(os.getenv('JOBS_SEEK_PER_KEYWORD_LIMIT', '12'))
JOBS_FRESHNESS_HOURS = int(os.getenv('JOBS_FRESHNESS_HOURS', '72'))
JOBS_TOP_PICK_LIMIT = int(os.getenv('JOBS_TOP_PICK_LIMIT', '7'))
JOBS_NOTION_TOP_PICK_LIMIT = int(os.getenv('JOBS_NOTION_TOP_PICK_LIMIT', '7'))
JOBS_NOTION_API_TOKEN = os.getenv('JOBS_NOTION_API_TOKEN', '')
JOBS_NOTION_PARENT_PAGE_ID = os.getenv('JOBS_NOTION_PARENT_PAGE_ID', '')
JOBS_NOTION_API_VERSION = os.getenv('JOBS_NOTION_API_VERSION', '2022-06-28')
JOBS_SLACK_CHANNEL = os.getenv('JOBS_SLACK_CHANNEL', '#jobs')
JOBS_SLACK_WEBHOOK_URL = os.getenv('JOBS_SLACK_WEBHOOK_URL', '')
SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN', '')
JOBS_SLACK_BOT_TOKEN = os.getenv('JOBS_SLACK_BOT_TOKEN', '')
ADZUNA_APP_ID = os.getenv('ADZUNA_APP_ID', '')
ADZUNA_APP_KEY = os.getenv('ADZUNA_APP_KEY', '')
JOBS_LLM_JUDGE_ENABLED = _env_is_true('JOBS_LLM_JUDGE_ENABLED', False)
JOBS_LLM_JUDGE_API_KEY = os.getenv('JOBS_LLM_JUDGE_API_KEY', '')
JOBS_LLM_JUDGE_BASE_URL = os.getenv('JOBS_LLM_JUDGE_BASE_URL', 'https://api.openai.com/v1')
JOBS_LLM_JUDGE_MODEL = os.getenv('JOBS_LLM_JUDGE_MODEL', 'gpt-4o-mini')
VALLEY_HARNESS_URL = os.getenv('VALLEY_HARNESS_URL', '')
VALLEY_HARNESS_API_KEY = os.getenv('VALLEY_HARNESS_API_KEY', '')
SLACK_BRIDGE_BOT_TOKEN = os.getenv('SLACK_BRIDGE_BOT_TOKEN', '')
SLACK_BRIDGE_SIGNING_SECRET = os.getenv('SLACK_BRIDGE_SIGNING_SECRET', '')
SLACK_BRIDGE_BOT_USER_ID = os.getenv('SLACK_BRIDGE_BOT_USER_ID', '')
DISCORD_BRIDGE_BOT_TOKEN = os.getenv('DISCORD_BRIDGE_BOT_TOKEN', '')
DISCORD_BRIDGE_APPLICATION_ID = os.getenv('DISCORD_BRIDGE_APPLICATION_ID', '')
DISCORD_BRIDGE_PUBLIC_KEY = os.getenv('DISCORD_BRIDGE_PUBLIC_KEY', '')

# Google OAuth Settings
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET")
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get(
    "GOOGLE_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/google",
)

GOOGLE_OAUTH_SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]
GOOGLE_OAUTH_IDENTITY_SCOPES = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]
GOOGLE_WEBSITE_BASELINE_SCOPES = [
    "https://www.googleapis.com/auth/webmasters.readonly",
]
GOOGLE_PLACES_API_KEY = os.environ.get("GOOGLE_PLACES_API_KEY", "")
ABR_LOOKUP_AUTHENTICATION_GUID = os.environ.get("ABR_LOOKUP_AUTHENTICATION_GUID", "")

# Founder-authorized connector OAuth settings
STRIPE_CONNECT_CLIENT_ID = _env_first(
    "STRIPE_CONNECT_CLIENT_ID",
    "STRIPE_CONNECT_OAUTH_CLIENT_ID",
    "STRIPE_CLIENT_ID",
)
STRIPE_SECRET_KEY = _env_first(
    "STRIPE_SECRET_KEY",
    "STRIPE_API_SECRET_KEY",
    "STRIPE_API_KEY",
)
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_OAUTH_REDIRECT_URI = os.environ.get(
    "STRIPE_OAUTH_REDIRECT_URI",
    f"{DEFAULT_BACKEND_URL}/integrations/callback/stripe",
)
STRIPE_OAUTH_SCOPES = _env_list("STRIPE_OAUTH_SCOPES", ["read_only"])

XERO_CLIENT_ID = os.environ.get("XERO_CLIENT_ID", "")
XERO_CLIENT_SECRET = os.environ.get("XERO_CLIENT_SECRET", "")
XERO_OAUTH_REDIRECT_URI = os.environ.get(
    "XERO_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/xero",
)
XERO_OAUTH_SCOPES = _env_list(
    "XERO_OAUTH_SCOPES",
    [
        "offline_access",
        "accounting.invoices.read",
        "accounting.payments.read",
        "accounting.settings.read",
        "accounting.contacts.read",
    ],
)

NOTION_CLIENT_ID = os.environ.get("NOTION_CLIENT_ID", "")
NOTION_CLIENT_SECRET = os.environ.get("NOTION_CLIENT_SECRET", "")
NOTION_OAUTH_REDIRECT_URI = os.environ.get(
    "NOTION_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/notion",
)
NOTION_API_VERSION = os.environ.get("NOTION_API_VERSION", "2026-03-11")
NOTION_SYNC_PAGE_LIMIT = int(os.environ.get("NOTION_SYNC_PAGE_LIMIT", "20") or 20)

GOOGLE_DRIVE_OAUTH_REDIRECT_URI = os.environ.get(
    "GOOGLE_DRIVE_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/google-drive",
)
GOOGLE_DRIVE_OAUTH_SCOPES = _env_list(
    "GOOGLE_DRIVE_OAUTH_SCOPES",
    [
        "https://www.googleapis.com/auth/drive.readonly",
        "openid",
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile",
    ],
)

SLACK_CLIENT_ID = _env_first("FT_SLACK_CLIENT_ID", "SLACK_CLIENT_ID")
SLACK_CLIENT_SECRET = _env_first("FT_SLACK_CLIENT_SECRET", "SLACK_CLIENT_SECRET")
SLACK_OAUTH_REDIRECT_URI = _env_first(
    "FT_SLACK_OAUTH_REDIRECT_URI",
    "SLACK_OAUTH_REDIRECT_URI",
    default="http://localhost:8000/integrations/callback/slack",
)
SLACK_OAUTH_SCOPES = _env_list(
    "SLACK_OAUTH_SCOPES",
    [
        "channels:history",
        "channels:read",
        "groups:history",
        "groups:read",
        "team:read",
        "users:read",
    ],
)
SLACK_OAUTH_USER_SCOPES = _env_list("SLACK_OAUTH_USER_SCOPES", SLACK_OAUTH_SCOPES)
SLACK_OAUTH_BOT_SCOPES = _env_list("SLACK_OAUTH_BOT_SCOPES", [])
SLACK_SYNC_HISTORY_DAYS = int(os.environ.get("SLACK_SYNC_HISTORY_DAYS", "120") or 120)
SLACK_SYNC_HISTORY_PAGE_LIMIT = int(os.environ.get("SLACK_SYNC_HISTORY_PAGE_LIMIT", "100") or 100)
SLACK_SYNC_HISTORY_MAX_PAGES = int(os.environ.get("SLACK_SYNC_HISTORY_MAX_PAGES", "5") or 5)
SLACK_SYNC_REPLY_MAX_PAGES = int(os.environ.get("SLACK_SYNC_REPLY_MAX_PAGES", "3") or 3)
SLACK_SYNC_REPLY_PAGE_BUDGET = int(os.environ.get("SLACK_SYNC_REPLY_PAGE_BUDGET", "2") or 2)
SLACK_API_CONNECT_TIMEOUT_SECONDS = float(os.environ.get("SLACK_API_CONNECT_TIMEOUT_SECONDS", "3") or 3)
SLACK_API_READ_TIMEOUT_SECONDS = float(os.environ.get("SLACK_API_READ_TIMEOUT_SECONDS", "8") or 8)

LINEAR_API_KEY = os.environ.get("LINEAR_API_KEY", "")
LINEAR_CLIENT_ID = os.environ.get("LINEAR_CLIENT_ID", "")
LINEAR_CLIENT_SECRET = os.environ.get("LINEAR_CLIENT_SECRET", "")
LINEAR_OAUTH_REDIRECT_URI = os.environ.get(
    "LINEAR_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/linear",
)
LINEAR_OAUTH_SCOPES = _env_list("LINEAR_OAUTH_SCOPES", ["read"])
LINEAR_SYNC_PROJECT_PAGE_LIMIT = int(os.environ.get("LINEAR_SYNC_PROJECT_PAGE_LIMIT", "100") or 100)
LINEAR_SYNC_ISSUE_PAGE_LIMIT = int(os.environ.get("LINEAR_SYNC_ISSUE_PAGE_LIMIT", "50") or 50)
LINEAR_SYNC_UPDATE_PAGE_LIMIT = int(os.environ.get("LINEAR_SYNC_UPDATE_PAGE_LIMIT", "20") or 20)
LINEAR_API_CONNECT_TIMEOUT_SECONDS = float(os.environ.get("LINEAR_API_CONNECT_TIMEOUT_SECONDS", "3") or 3)
LINEAR_API_READ_TIMEOUT_SECONDS = float(os.environ.get("LINEAR_API_READ_TIMEOUT_SECONDS", "20") or 20)

BASIQ_API_KEY = os.environ.get("BASIQ_API_KEY", "")
BASIQ_API_BASE_URL = os.environ.get("BASIQ_API_BASE_URL", "https://au-api.basiq.io")
BASIQ_CONSENT_UI_URL = os.environ.get("BASIQ_CONSENT_UI_URL", "https://consent.basiq.io/home")
BASIQ_API_VERSION = os.environ.get("BASIQ_API_VERSION", "3.0")

# GitHub App Settings (for GitHub App installation flow)
GITHUB_APP_ID = os.environ.get("GITHUB_APP_ID")
GITHUB_OAUTH_CLIENT_ID = os.environ.get("GITHUB_OAUTH_CLIENT_ID")
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get("GITHUB_OAUTH_CLIENT_SECRET")
GITHUB_OAUTH_REDIRECT_URI = os.environ.get(
    "GITHUB_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/github",
)

# Points System Configuration
POINTS_BOOTSTRAP_ADMIN_SLACK_IDS = [s.strip() for s in os.getenv('POINTS_BOOTSTRAP_ADMIN_SLACK_IDS', '').split(',') if s.strip()]
DEFAULT_COWORKING_CAPACITY = int(os.getenv('DEFAULT_COWORKING_CAPACITY', '24'))
COWORKING_DAY_COST_POINTS = int(os.getenv('COWORKING_DAY_COST_POINTS', '1'))
COWORKING_REFUND_CUTOFF_HOURS = int(os.getenv('COWORKING_REFUND_CUTOFF_HOURS', '18'))  # 6pm prev day
COWORKING_BOOKING_ADVANCE_DAYS = int(os.environ.get('COWORKING_BOOKING_ADVANCE_DAYS', 30))

# Internal API Key for service-to-service auth (e.g. from Roo agent)
ROO_API_KEY = os.environ.get('ROO_API_KEY')
MLAI_API_KEY = os.environ.get('MLAI_API_KEY')
INTERNAL_API_KEY = os.environ.get('INTERNAL_API_KEY') or ROO_API_KEY or MLAI_API_KEY
LUMA_API_KEY = os.environ.get('LUMA_API_KEY')
LUMA_BASE_URL = os.environ.get('LUMA_BASE_URL', 'https://public-api.luma.com')

# MedHack Game Configuration
MEDHACK_ADMIN_IDS = [s.strip() for s in os.getenv('MEDHACK_ADMIN_IDS', '').split(',') if s.strip()]
