"""
Django settings for medhack_backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import json
import os
import subprocess
from datetime import timedelta
from corsheaders.defaults import default_headers

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.db.backends.signals import connection_created
load_dotenv()


def _env_is_true(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _resolve_app_env(*, debug: bool, raw_env: str = "") -> str:
    if raw_env:
        return raw_env
    return "local" if debug else "production"


def _resolve_app_release(base_dir: str) -> str:
    for env_name in (
        "APP_RELEASE",
        "GIT_SHA",
        "COMMIT_SHA",
        "RENDER_GIT_COMMIT",
        "SOURCE_VERSION",
        "VERCEL_GIT_COMMIT_SHA",
    ):
        raw = os.getenv(env_name, "").strip()
        if raw:
            return raw[:12]

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=base_dir,
            capture_output=True,
            text=True,
            check=False,
        )
    except Exception:
        return "unknown"

    if result.returncode == 0:
        value = (result.stdout or "").strip()
        if value:
            return value

    return "unknown"


def _env_list(name: str, default: list[str]) -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        return default
    return [item.strip() for item in raw.replace(",", " ").split() if item.strip()]


def _env_first(*names: str, default: str = "") -> str:
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return default


def _validate_health_hack_service_secrets(
    *,
    health_hack_key: str,
    roo_sim_patient_key: str,
    roo_api_key: str,
    is_production: bool,
) -> None:
    """Require strong, purpose-specific cross-service credentials in production."""

    if not is_production:
        return
    if len(health_hack_key) < 32:
        raise ImproperlyConfigured(
            'HEALTH_HACK_API_KEY must contain at least 32 characters in production.'
        )
    if len(roo_sim_patient_key) < 32:
        raise ImproperlyConfigured(
            'ROO_SIM_PATIENT_KEY must contain at least 32 characters in production.'
        )
    if len(roo_api_key) < 32:
        raise ImproperlyConfigured(
            'ROO_API_KEY must contain at least 32 characters in production.'
        )
    if len({health_hack_key, roo_sim_patient_key, roo_api_key}) != 3:
        raise ImproperlyConfigured(
            'HEALTH_HACK_API_KEY, ROO_SIM_PATIENT_KEY, and ROO_API_KEY must be '
            'distinct credentials.'
        )


def _validate_health_hack_ai_modes(*, rate_mode: str, budget_mode: str, is_production: bool):
    if rate_mode not in {'observe', 'enforce'}:
        raise ImproperlyConfigured('HEALTH_HACK_AI_RATE_LIMIT_MODE must be observe or enforce')
    if budget_mode not in {'observe', 'enforce'}:
        raise ImproperlyConfigured('HEALTH_HACK_AI_BUDGET_MODE must be observe or enforce')
    if is_production and budget_mode != 'enforce':
        raise ImproperlyConfigured(
            'HEALTH_HACK_AI_BUDGET_MODE must be enforce in production.'
        )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
RAW_APP_ENV = os.getenv('APP_ENV', '').strip().lower()
DEBUG_DEFAULT = False if RAW_APP_ENV in {'production', 'prod'} else True
DEBUG = _env_is_true('DEBUG', DEBUG_DEFAULT)
APP_ENV = _resolve_app_env(debug=DEBUG, raw_env=RAW_APP_ENV)
APP_RELEASE = _resolve_app_release(BASE_DIR)
IS_LOCAL_ENV = APP_ENV in {'local', 'development', 'dev', 'test'}
IS_PRODUCTION_ENV = not IS_LOCAL_ENV

# SECURITY WARNING: keep the secret key used in production secret!
# Production MUST supply SECRET_KEY via the environment. We fail closed rather
# than fall back to a committed value: a known signing key makes every JWT
# forgeable (full auth bypass) and -- because EncryptedTextField derives its key
# from SECRET_KEY by default -- every stored OAuth token decryptable. The
# insecure literal below is a convenience fallback for local/dev/test ONLY.
_DEV_INSECURE_SECRET_KEY = 'django-insecure-vh##sgy=^gqeoyqjm0*%23zewxuw=&l&-dv6%%k*$sw7#+vzp+'


def _resolve_secret_key(*, is_production: bool) -> str:
    secret = _env_first('SECRET_KEY', 'DJANGO_SECRET_KEY')
    if secret:
        return secret
    if is_production:
        raise ImproperlyConfigured(
            "SECRET_KEY (or DJANGO_SECRET_KEY) must be set in the environment in "
            "production. Refusing to start with the committed development key."
        )
    return _DEV_INSECURE_SECRET_KEY


SECRET_KEY = _resolve_secret_key(is_production=IS_PRODUCTION_ENV)

# --- Field-level encryption (integrations.fields.EncryptedTextField) ----------
# Connector OAuth tokens (Gmail/Stripe/Xero/Notion/Slack/Linear/GitHub) are
# encrypted at rest. Historically the Fernet key was derived from SECRET_KEY,
# coupling token secrecy to the (previously committed) signing key. Provide a
# dedicated FIELD_ENCRYPTION_KEY -- a urlsafe-base64 Fernet key, e.g.
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# -- so the two concerns rotate independently. When unset, the field key falls
# back to one derived from SECRET_KEY. LEGACY_FIELD_ENCRYPTION_SECRET lets rows
# written under the old key still decrypt until re-encrypted via
# `manage.py reencrypt_secrets`.
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY', '')
LEGACY_FIELD_ENCRYPTION_SECRET = os.getenv(
    'LEGACY_FIELD_ENCRYPTION_SECRET', _DEV_INSECURE_SECRET_KEY
)

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')
ALLOWED_HOSTS.extend(['.localhost'])

# Disable trailing slash redirect for API endpoints
APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hospital',
    'organizations',
    'workflow_runs',
    'startup_updates',
    'content_factory',
    'content_analytics',
    'founder_tools',
    'data_access',
    'core',
    'esafety',
    'generic_hackathons',
    'vibe_raising',
    'mlai_studio',
    'victor_ai',
    'jobs',
    "rest_framework",
    "roo",

    "integrations",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.RequestLoggingMiddleware',
    'core.middleware.PointsEndpointTimeoutMiddleware',
]

ROOT_URLCONF = 'mlai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mlai.wsgi.application'

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:5173,https://mlai.au,https://www.mlai.au,https://admin.mlai.au').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://localhost:5173,https://mlai.au,https://www.mlai.au,https://admin.mlai.au').split(',')
# The standalone admin dashboard (admin.mlai.au) must always be an allowed,
# credentialed origin, even if the env-var lists above are overridden in prod.
for _admin_origin in ('https://admin.mlai.au',):
    if _admin_origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_admin_origin)
    if _admin_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_admin_origin)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (*default_headers, "x-request-id")
CORS_EXPOSE_HEADERS = ["X-Request-ID"]


WATT_THE_HACK_REGISTERED_TEAMS = {}
WATT_THE_HACK_MAX_JUDGING_RUNS = int(os.getenv('WATT_THE_HACK_MAX_JUDGING_RUNS', '3'))


database_url = os.getenv('DATABASE_URL')
is_sqlite_database = (database_url or '').startswith('sqlite:')
database_conn_max_age = 0 if is_sqlite_database else 600
SQLITE_TIMEOUT_SECONDS = int(os.getenv('SQLITE_TIMEOUT_SECONDS', '30'))
SQLITE_BUSY_TIMEOUT_MS = int(os.getenv('SQLITE_BUSY_TIMEOUT_MS', str(SQLITE_TIMEOUT_SECONDS * 1000)))
SQLITE_ENABLE_WAL = _env_is_true('SQLITE_ENABLE_WAL', True)
SQLITE_LOCK_RETRY_AFTER_SECONDS = int(os.getenv('SQLITE_LOCK_RETRY_AFTER_SECONDS', '2'))

# Parse database configuration from $DATABASE_URL
default_config = dj_database_url.config(
    default=os.environ.get('DATABASE_URL'),
    conn_max_age=database_conn_max_age,
    ssl_require=os.getenv('DATABASE_SSL_REQUIRE', 'False') == 'True'
)

if default_config.get('ENGINE') == 'django.db.backends.sqlite3':
    sqlite_options = default_config.setdefault('OPTIONS', {})
    sqlite_options.setdefault('timeout', SQLITE_TIMEOUT_SECONDS)

DATABASES = {
    'default': default_config
}


# Watt Unity session tickets must be shared across gunicorn workers: the request that MINTS a ticket
# (unity-sessions/current/) and the one that REDEEMS it (redeem-ticket/) are typically served by
# different worker processes, so a per-process LocMemCache 404s the redeem.
#
# Prefer Redis/Valkey (REDIS_URL) — a real shared cache across all workers, better under load and
# off Postgres. Falls back to a Postgres DatabaseCache for `watt_session` (and a local `default`)
# when REDIS_URL is unset OR the `redis` package isn't installed, so local/CI and un-rebuilt images
# keep working instead of hard-crashing.
_REDIS_URL = os.getenv('REDIS_URL', '').strip()
if _REDIS_URL:
    try:
        import redis as _redis_dep  # noqa: F401  (Django's builtin RedisCache needs redis-py)
        _REDIS_CACHE_AVAILABLE = True
    except ImportError:
        _REDIS_CACHE_AVAILABLE = False
else:
    _REDIS_CACHE_AVAILABLE = False


def _build_cache_settings(*, redis_url: str, redis_available: bool, is_production: bool):
    """Build cache settings, refusing process-local security state in production."""

    if is_production and not redis_url:
        raise ImproperlyConfigured(
            'REDIS_URL must be configured in production. Health Hack quotas, '
            'in-flight locks, and spending caps require a shared Redis/Valkey cache.'
        )
    if is_production and not redis_available:
        raise ImproperlyConfigured(
            'The redis package is required in production when REDIS_URL is configured.'
        )
    if redis_url and not redis_url.lower().startswith(('redis://', 'rediss://')):
        raise ImproperlyConfigured('REDIS_URL must use the redis:// or rediss:// scheme.')

    if redis_available:
        return {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_url,
                'KEY_PREFIX': 'mlai',
            },
            'watt_session': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_url,
                'KEY_PREFIX': 'watt_session',
            },
        }
    return {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        },
        'watt_session': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'watt_unity_session_cache',
        },
    }


CACHES = _build_cache_settings(
    redis_url=_REDIS_URL,
    redis_available=_REDIS_CACHE_AVAILABLE,
    is_production=IS_PRODUCTION_ENV,
)


def _configure_sqlite_connection(sender, connection, **kwargs):
    if connection.vendor != 'sqlite':
        return
    try:
        with connection.cursor() as cursor:
            cursor.execute(f'PRAGMA busy_timeout={SQLITE_BUSY_TIMEOUT_MS}')
            if SQLITE_ENABLE_WAL and connection.settings_dict.get('NAME') != ':memory:':
                cursor.execute('PRAGMA journal_mode=WAL')
            cursor.execute('PRAGMA synchronous=NORMAL')
    except Exception:
        # SQLite pragmas are local-development hardening only; never block app boot.
        return


connection_created.connect(_configure_sqlite_connection)

POINTS_STATEMENT_TIMEOUT_MS = int(os.getenv('POINTS_STATEMENT_TIMEOUT_MS', '12000'))
POINTS_LOCK_TIMEOUT_MS = int(os.getenv('POINTS_LOCK_TIMEOUT_MS', '5000'))
GMAIL_API_HTTP_TIMEOUT_SECONDS = float(os.getenv('GMAIL_API_HTTP_TIMEOUT_SECONDS', '4'))
GMAIL_METADATA_PAGE_MAX_RESULTS = int(os.getenv('GMAIL_METADATA_PAGE_MAX_RESULTS', '5'))


AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'hospital.authentication.CustomJWTAuthentication',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Rate limit for MedHack endpoints
        'watt_unity_ticket_redeem': os.getenv('WATT_UNITY_TICKET_REDEEM_RATE', '60/minute'),
    }
}

HEALTH_HACK_ACTIVE_CASE_ID = int(os.getenv('HEALTH_HACK_ACTIVE_CASE_ID', '1'))
HEALTH_HACK_AI_BODY_MAX_BYTES = int(os.getenv('HEALTH_HACK_AI_BODY_MAX_BYTES', str(16 * 1024)))
HEALTH_HACK_AI_UPSTREAM_MAX_BYTES = int(
    os.getenv('HEALTH_HACK_AI_UPSTREAM_MAX_BYTES', str(32 * 1024))
)
HEALTH_HACK_AI_REPLY_MAX_CHARS = int(os.getenv('HEALTH_HACK_AI_REPLY_MAX_CHARS', '1500'))
HEALTH_HACK_AI_REPLY_MAX_WORDS = int(os.getenv('HEALTH_HACK_AI_REPLY_MAX_WORDS', '160'))
HEALTH_HACK_AI_MAX_PROMPT_TOKENS = int(
    os.getenv('HEALTH_HACK_AI_MAX_PROMPT_TOKENS', '12000')
)
HEALTH_HACK_AI_MAX_COMPLETION_TOKENS = int(
    os.getenv('HEALTH_HACK_AI_MAX_COMPLETION_TOKENS', '2000')
)
HEALTH_HACK_DIAGNOSIS_UPSTREAM_MAX_BYTES = int(
    os.getenv('HEALTH_HACK_DIAGNOSIS_UPSTREAM_MAX_BYTES', str(8 * 1024))
)

# Participant/network thresholds start in observation mode so event traffic can
# tune them without gameplay friction. The generous global spend ceiling is a
# hard circuit breaker by default and must never silently become advisory.
HEALTH_HACK_AI_RATE_LIMIT_MODE = os.getenv(
    'HEALTH_HACK_AI_RATE_LIMIT_MODE', 'observe'
).strip().lower()
HEALTH_HACK_AI_BUDGET_MODE = os.getenv(
    'HEALTH_HACK_AI_BUDGET_MODE', 'enforce'
).strip().lower()
_validate_health_hack_ai_modes(
    rate_mode=HEALTH_HACK_AI_RATE_LIMIT_MODE,
    budget_mode=HEALTH_HACK_AI_BUDGET_MODE,
    is_production=IS_PRODUCTION_ENV,
)

HEALTH_HACK_AI_KILL_SWITCH = _env_is_true('HEALTH_HACK_AI_KILL_SWITCH', False)
HEALTH_HACK_AI_PARTICIPANT_BURST_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_PARTICIPANT_BURST_LIMIT', '3')
)
HEALTH_HACK_AI_PARTICIPANT_10M_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_PARTICIPANT_10M_LIMIT', '40')
)
HEALTH_HACK_AI_PARTICIPANT_HOURLY_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_PARTICIPANT_HOURLY_LIMIT', '100')
)
HEALTH_HACK_AI_NETWORK_BURST_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_NETWORK_BURST_LIMIT', '60')
)
HEALTH_HACK_AI_NETWORK_10M_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_NETWORK_10M_LIMIT', '400')
)
HEALTH_HACK_AI_NETWORK_HOURLY_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_NETWORK_HOURLY_LIMIT', '1000')
)
HEALTH_HACK_AI_INFLIGHT_TTL_SECONDS = int(
    os.getenv('HEALTH_HACK_AI_INFLIGHT_TTL_SECONDS', '35')
)
HEALTH_HACK_AI_PENDING_TTL_SECONDS = int(
    os.getenv('HEALTH_HACK_AI_PENDING_TTL_SECONDS', '35')
)
HEALTH_HACK_AI_DAILY_CALL_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_DAILY_CALL_LIMIT', '5000')
)
HEALTH_HACK_AI_DAILY_TOKEN_LIMIT = int(
    os.getenv('HEALTH_HACK_AI_DAILY_TOKEN_LIMIT', '5000000')
)
HEALTH_HACK_CHAT_RETENTION_DAYS = int(
    os.getenv('HEALTH_HACK_CHAT_RETENTION_DAYS', '30')
)
HEALTH_HACK_FREE_TICKET_URL = os.getenv(
    'HEALTH_HACK_FREE_TICKET_URL',
    'https://luma.com/mlai-8obe?coupon=RQY4N0',
)
HEALTH_HACK_DISCOUNT_URL = os.getenv(
    'HEALTH_HACK_DISCOUNT_URL',
    'https://luma.com/mlai-8obe?coupon=ALMOSTGOTIT',
)
# The two-patient ward runs concurrent one-guess books. Guess/claim/status
# accept exactly these case ids; each case's first solver gets its own ticket
# coupon (falling back to HEALTH_HACK_FREE_TICKET_URL for unmapped cases),
# while the runner-up discount stays global.
HEALTH_HACK_OPEN_CASE_IDS = [
    int(token)
    for token in os.getenv('HEALTH_HACK_OPEN_CASE_IDS', '1,2').split(',')
    if token.strip()
]
_HEALTH_HACK_DEFAULT_FREE_TICKET_URLS = {
    1: 'https://luma.com/mlai-8obe?coupon=RQY4N0',
    2: 'https://luma.com/mlai-8obe?coupon=7FS6FZ',
}
try:
    HEALTH_HACK_FREE_TICKET_URLS = {
        int(case_key): str(url)
        for case_key, url in json.loads(
            os.getenv('HEALTH_HACK_FREE_TICKET_URLS', '') or '{}'
        ).items()
    } or _HEALTH_HACK_DEFAULT_FREE_TICKET_URLS
except (ValueError, TypeError):
    raise ImproperlyConfigured(
        'HEALTH_HACK_FREE_TICKET_URLS must be a JSON object of case_id -> URL'
    )

WATT_HACKATHON_CLASS_ID = os.getenv('WATT_HACKATHON_CLASS_ID', 'WATT')
WATT_HACKATHON_API_BASE_URL = os.getenv('WATT_HACKATHON_API_BASE_URL', '')
WATT_UNITY_SESSION_TICKET_TTL_SECONDS = int(os.getenv('WATT_UNITY_SESSION_TICKET_TTL_SECONDS', '300'))
VAGON_STREAM_ID = os.getenv('VAGON_STREAM_ID', '')
VAGON_STREAM_URL = os.getenv('VAGON_STREAM_URL', '')

# --- Global campaign window (deterministic resume) ---------------------------------------
# The fixed-length campaign maps linearly onto [START, START + LENGTH * DAY_SECONDS] and is
# shared by ALL teams and ALL sessions, so a player who first connects mid-window sees the
# campaign already in progress (e.g. day 18). WATT_CAMPAIGN_START is an ISO-8601 datetime WITH
# an explicit UTC offset, so the window is timezone-unambiguous regardless of the server /
# Vagon-VM clock. Leave blank to disable (Unity then falls back to the classroom/local clock).
# TEST VALUE = today 22:00 Australia/Melbourne (AEST, +10:00). CHANGE THIS FOR GO-LIVE (e.g.
# the event date at 11:00 -> "2026-06-15T11:00:00+10:00").
WATT_CAMPAIGN_START = os.getenv('WATT_CAMPAIGN_START', '2026-06-04T22:00:00+10:00')
WATT_CAMPAIGN_LENGTH_DAYS = int(os.getenv('WATT_CAMPAIGN_LENGTH_DAYS', '46'))
WATT_CAMPAIGN_DAY_SECONDS = float(os.getenv('WATT_CAMPAIGN_DAY_SECONDS', '700'))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_COOKIE': 'access_token',  # Cookie name for access token
    'AUTH_COOKIE_REFRESH': 'refresh_token',  # Cookie name for refresh token
    'AUTH_COOKIE_SECURE': not DEBUG,  # Set to True in production with HTTPS
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

DJANGO_LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'vibe_raising': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'integrations': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'hospital.authentication': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
    },
}

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if IS_PRODUCTION_ENV:
    try:
        from .settings_prod import *
    except ImportError:
        pass

# App URLs
DEFAULT_FRONTEND_URL = os.getenv('DEFAULT_FRONTEND_URL') or (
    'http://localhost:5173' if IS_LOCAL_ENV else 'https://mlai.au'
)
DEFAULT_BACKEND_URL = os.getenv('DEFAULT_BACKEND_URL') or (
    'http://localhost:8000' if IS_LOCAL_ENV else 'https://api.mlai.au'
)
MEDHACK_URL = os.getenv('MEDHACK_URL') or DEFAULT_FRONTEND_URL
ESAFETY_URL = os.getenv('ESAFETY_URL') or DEFAULT_FRONTEND_URL
WATT_THE_HACK_URL = os.getenv('WATT_THE_HACK_URL') or DEFAULT_FRONTEND_URL
VIBE_RAISING_URL = os.getenv('VIBE_RAISING_URL') or DEFAULT_FRONTEND_URL
FOUNDER_TOOLS_URL = os.getenv('FOUNDER_TOOLS_URL') or VIBE_RAISING_URL
CONTENT_FACTORY_FRONTEND_URL = os.getenv('CONTENT_FACTORY_FRONTEND_URL') or DEFAULT_FRONTEND_URL
ADMIN_FRONTEND_URL = os.getenv('ADMIN_FRONTEND_URL') or (
    'http://localhost:3001' if IS_LOCAL_ENV else 'https://admin.mlai.au'
)
CONTENT_FACTORY_URL = os.getenv('CONTENT_FACTORY_URL') or (
    'http://localhost:8001' if IS_LOCAL_ENV else ''
)

# Health Hack simulated-patient gateway. The browser-facing Cloudflare Worker
# calls this Django service over HTTPS; Django reaches Roo over the private
# DigitalOcean VPC so Roo itself does not need a public hostname.
ROO_SERVICE_URL = os.getenv('ROO_SERVICE_URL', '').rstrip('/')
ROO_SIM_PATIENT_KEY = os.getenv('ROO_SIM_PATIENT_KEY', '').strip()
HEALTH_HACK_API_KEY = os.getenv('HEALTH_HACK_API_KEY', '').strip()
ROO_API_KEY = os.getenv('ROO_API_KEY', '').strip()
_validate_health_hack_service_secrets(
    health_hack_key=HEALTH_HACK_API_KEY,
    roo_sim_patient_key=ROO_SIM_PATIENT_KEY,
    roo_api_key=ROO_API_KEY,
    is_production=IS_PRODUCTION_ENV,
)
CONTENT_FACTORY_PREVIEW_BASE_URL = os.getenv('CONTENT_FACTORY_PREVIEW_BASE_URL', '')
CONTENT_FACTORY_PREVIEW_LINK_TTL_SECONDS = int(
    os.getenv('CONTENT_FACTORY_PREVIEW_LINK_TTL_SECONDS', str(7 * 24 * 60 * 60))
)
CONTENT_FACTORY_LIVE_PREVIEW_START_READ_TIMEOUT_SECONDS = int(
    os.getenv('CONTENT_FACTORY_LIVE_PREVIEW_START_READ_TIMEOUT_SECONDS', '20')
)
CONTENT_FACTORY_API_KEY = os.getenv('CONTENT_FACTORY_API_KEY')
CONTENT_FACTORY_DEFAULT_ARTICLE_DELIVERY_MODE = os.getenv(
    'CONTENT_FACTORY_DEFAULT_ARTICLE_DELIVERY_MODE',
    'review_draft',
)
CONTENT_AUTOMATION_ACTION_MAX_AGE_SECONDS = int(
    os.getenv('CONTENT_AUTOMATION_ACTION_MAX_AGE_SECONDS', str(14 * 24 * 60 * 60))
)
# Daily email links are short-lived capability URLs. They render a read-only
# confirmation page on GET and only execute after an explicit POST.
CONTENT_AUTOMATION_EMAIL_ACTION_MAX_AGE_SECONDS = int(
    os.getenv('CONTENT_AUTOMATION_EMAIL_ACTION_MAX_AGE_SECONDS', str(48 * 60 * 60))
)
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', 'Roo <notifications@mlai.au>')
# Customer.io App API key (already used for magic-link emails). When set, it is
# the preferred transport for notification-channel emails; Resend is fallback.
CUSTOMERIO_API_KEY = os.getenv('CUSTOMERIO_API_KEY', '')
CUSTOMERIO_FROM_EMAIL = os.getenv('CUSTOMERIO_FROM_EMAIL', '')
# Transactional message id of the Victor:AI completed-registration receipt.
CUSTOMERIO_VICTOR_REGISTRATION_TEMPLATE_ID = os.getenv(
    'CUSTOMERIO_VICTOR_REGISTRATION_TEMPLATE_ID', '4'
)
# Transactional message id of the "Vibe Marketing Daily Reminder" template in
# Customer.io. When set, the daily topic_selection email renders through that
# template (Liquid loop over message_data.topics) instead of a raw HTML body.
CUSTOMERIO_TOPIC_TEMPLATE_ID = os.getenv('CUSTOMERIO_TOPIC_TEMPLATE_ID', '3')
# Friendly monthly-update renewal reminders. Production delivery stays off
# until both Customer.io templates have been reviewed and their ids configured.
MONTHLY_UPDATE_REMINDERS_ENABLED = _env_is_true('MONTHLY_UPDATE_REMINDERS_ENABLED', False)
MONTHLY_UPDATE_REMINDER_TIMEZONE = os.getenv(
    'MONTHLY_UPDATE_REMINDER_TIMEZONE', 'Australia/Melbourne'
)
MONTHLY_UPDATE_REMINDER_HOUR = int(os.getenv('MONTHLY_UPDATE_REMINDER_HOUR', '9'))
MONTHLY_UPDATE_REMINDER_MINUTE = int(os.getenv('MONTHLY_UPDATE_REMINDER_MINUTE', '0'))
MONTHLY_UPDATE_REMINDERS_QUEUE_DRAFT = _env_is_true(
    'MONTHLY_UPDATE_REMINDERS_QUEUE_DRAFT', True
)
CUSTOMERIO_MONTHLY_UPDATE_7D_TEMPLATE_ID = os.getenv(
    'CUSTOMERIO_MONTHLY_UPDATE_7D_TEMPLATE_ID', ''
)
CUSTOMERIO_MONTHLY_UPDATE_1D_TEMPLATE_ID = os.getenv(
    'CUSTOMERIO_MONTHLY_UPDATE_1D_TEMPLATE_ID', ''
)
MONTHLY_UPDATE_REMINDER_APP_URL = os.getenv(
    'MONTHLY_UPDATE_REMINDER_APP_URL', 'https://mlai.au'
).rstrip('/')
# Twilio credentials drive WhatsApp sends (Messages API) and inbound webhook
# validation (X-Twilio-Signature is HMAC-SHA1 keyed by the auth token).
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
# WhatsApp-enabled Twilio number in E.164 (no whatsapp: prefix).
TWILIO_WHATSAPP_FROM = os.getenv('TWILIO_WHATSAPP_FROM', '')
# Approved WhatsApp Content template SID (HX...) used to deliver
# channel-verification OTPs; must be an AUTHENTICATION template.
TWILIO_WHATSAPP_OTP_CONTENT_SID = os.getenv('TWILIO_WHATSAPP_OTP_CONTENT_SID', '')
# Approved utility Content template for the daily topic message (variables:
# {{1}} domain, {{2}}-{{4}} topic titles). Without it, topic sends fall back to
# plain text and only deliver inside an open 24h service window.
TWILIO_WHATSAPP_TOPIC_CONTENT_SID = os.getenv('TWILIO_WHATSAPP_TOPIC_CONTENT_SID', '')
# Approved utility Content template for article review notifications (variables:
# {{1}} title, {{2}} domain, {{3}} expanded founder-tools review URL). The fixed
# template copy must include "Reply STOP to opt out.".
TWILIO_WHATSAPP_REVIEW_CONTENT_SID = os.getenv('TWILIO_WHATSAPP_REVIEW_CONTENT_SID', '')
NOTIFICATION_CHANNEL_VERIFY_MAX_AGE_SECONDS = int(
    os.getenv('NOTIFICATION_CHANNEL_VERIFY_MAX_AGE_SECONDS', str(3 * 24 * 60 * 60))
)
SCHEDULED_DISCOVERY_TIMEZONE = os.getenv('SCHEDULED_DISCOVERY_TIMEZONE', 'Australia/Melbourne')
SCHEDULED_DISCOVERY_CHANNEL_NAME = os.getenv('SCHEDULED_DISCOVERY_CHANNEL_NAME', 'vibe-marketing')
SCHEDULED_DISCOVERY_SLOT_MINUTES = int(os.getenv('SCHEDULED_DISCOVERY_SLOT_MINUTES', '15'))
SCHEDULED_DISCOVERY_MAX_TARGETS = int(os.getenv('SCHEDULED_DISCOVERY_MAX_TARGETS', '20'))
JOBS_PUBLIC_BASE_URL = os.getenv('JOBS_PUBLIC_BASE_URL', DEFAULT_BACKEND_URL)
JOBS_TRIGGER_TOKEN = os.getenv('JOBS_TRIGGER_TOKEN', '')
JOBS_SCHEDULER_ENABLED = _env_is_true('JOBS_SCHEDULER_ENABLED', True)
JOBS_SCHEDULE_TIMEZONE = os.getenv('JOBS_SCHEDULE_TIMEZONE', 'Australia/Melbourne')
JOBS_SCHEDULE_HOUR = int(os.getenv('JOBS_SCHEDULE_HOUR', '7'))
JOBS_SCHEDULE_MINUTE = int(os.getenv('JOBS_SCHEDULE_MINUTE', '0'))
JOBS_RETRY_ATTEMPTS = int(os.getenv('JOBS_RETRY_ATTEMPTS', '3'))
JOBS_RETRY_DELAY_SECONDS = int(os.getenv('JOBS_RETRY_DELAY_SECONDS', '300'))
JOBS_FAILURE_STOP_AFTER_DAYS = int(os.getenv('JOBS_FAILURE_STOP_AFTER_DAYS', '3'))
JOBS_SCHEDULER_POST_TO_SLACK = _env_is_true('JOBS_SCHEDULER_POST_TO_SLACK', True)
JOBS_SCHEDULER_POST_TO_NOTION = _env_is_true('JOBS_SCHEDULER_POST_TO_NOTION', True)
JOBS_SCHEDULER_MAX_PAGES = int(os.getenv('JOBS_SCHEDULER_MAX_PAGES', '1'))
JOBS_SCHEDULER_PER_KEYWORD_LIMIT = int(os.getenv('JOBS_SCHEDULER_PER_KEYWORD_LIMIT', '5'))
JOBS_SCRAPE_HEADLESS = _env_is_true('JOBS_SCRAPE_HEADLESS', True)
JOBS_SEEK_MAX_PAGES = int(os.getenv('JOBS_SEEK_MAX_PAGES', '3'))
JOBS_SEEK_PER_KEYWORD_LIMIT = int(os.getenv('JOBS_SEEK_PER_KEYWORD_LIMIT', '12'))
JOBS_FRESHNESS_HOURS = int(os.getenv('JOBS_FRESHNESS_HOURS', '72'))
JOBS_TOP_PICK_LIMIT = int(os.getenv('JOBS_TOP_PICK_LIMIT', '7'))
JOBS_NOTION_TOP_PICK_LIMIT = int(os.getenv('JOBS_NOTION_TOP_PICK_LIMIT', '7'))
JOBS_NOTION_API_TOKEN = os.getenv('JOBS_NOTION_API_TOKEN', '')
JOBS_NOTION_PARENT_PAGE_ID = os.getenv('JOBS_NOTION_PARENT_PAGE_ID', '')
JOBS_NOTION_API_VERSION = os.getenv('JOBS_NOTION_API_VERSION', '2022-06-28')
JOBS_SLACK_CHANNEL = os.getenv('JOBS_SLACK_CHANNEL', '#jobs')
JOBS_SLACK_WEBHOOK_URL = os.getenv('JOBS_SLACK_WEBHOOK_URL', '')
SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN', '')
HOSPITAL_SLACK_CHANNEL_NAME = os.getenv('HOSPITAL_SLACK_CHANNEL_NAME', 'healthhack')
HEALTHHACK_ANNOUNCEMENT_ADMIN_IDS = [
    value.strip()
    for value in os.getenv('HEALTHHACK_ANNOUNCEMENT_ADMIN_IDS', '').split(',')
    if value.strip()
]
JOBS_SLACK_BOT_TOKEN = os.getenv('JOBS_SLACK_BOT_TOKEN', '')
JOBS_LLM_JUDGE_ENABLED = _env_is_true('JOBS_LLM_JUDGE_ENABLED', False)
JOBS_LLM_JUDGE_API_KEY = os.getenv('JOBS_LLM_JUDGE_API_KEY', '')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
JOBS_LLM_JUDGE_BASE_URL = os.getenv('JOBS_LLM_JUDGE_BASE_URL', 'https://api.openai.com/v1')
JOBS_LLM_JUDGE_MODEL = os.getenv('JOBS_LLM_JUDGE_MODEL', 'gpt-4o-mini')
JOBS_LLM_LOCATION_CHECK_ENABLED = _env_is_true('JOBS_LLM_LOCATION_CHECK_ENABLED', True)
VALLEY_HARNESS_URL = os.getenv('VALLEY_HARNESS_URL', '')
VALLEY_HARNESS_API_KEY = os.getenv('VALLEY_HARNESS_API_KEY', '')
SLACK_BRIDGE_BOT_TOKEN = os.getenv('SLACK_BRIDGE_BOT_TOKEN', '')
SLACK_BRIDGE_SIGNING_SECRET = os.getenv('SLACK_BRIDGE_SIGNING_SECRET', '')
SLACK_BRIDGE_BOT_USER_ID = os.getenv('SLACK_BRIDGE_BOT_USER_ID', '')
DISCORD_BRIDGE_BOT_TOKEN = os.getenv('DISCORD_BRIDGE_BOT_TOKEN', '')
DISCORD_BRIDGE_APPLICATION_ID = os.getenv('DISCORD_BRIDGE_APPLICATION_ID', '')
DISCORD_BRIDGE_PUBLIC_KEY = os.getenv('DISCORD_BRIDGE_PUBLIC_KEY', '')

# Google OAuth Settings
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET")
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get(
    "GOOGLE_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/google",
)

GOOGLE_OAUTH_SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]
GOOGLE_OAUTH_IDENTITY_SCOPES = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]
GOOGLE_WEBSITE_BASELINE_SCOPES = [
    "https://www.googleapis.com/auth/webmasters.readonly",
]

# Content Factory page analytics. Umami remains the raw event store; this
# service retains only daily, article-scoped aggregates.
UMAMI_BASE_URL = os.environ.get("UMAMI_BASE_URL", "").strip().rstrip("/")
UMAMI_API_TOKEN = os.environ.get("UMAMI_API_TOKEN", "").strip()
UMAMI_USERNAME = os.environ.get("UMAMI_USERNAME", "").strip()
UMAMI_PASSWORD = os.environ.get("UMAMI_PASSWORD", "").strip()
UMAMI_TEAM_ID = os.environ.get("UMAMI_TEAM_ID", "").strip()
CONTENT_ANALYTICS_TRACKER_SCRIPT_URL = os.environ.get("CONTENT_ANALYTICS_TRACKER_SCRIPT_URL", "").strip()
# Public Umami host used as the tracker's data-host-url. This is not an event
# endpoint; Umami's served tracker owns the configured collection path.
CONTENT_ANALYTICS_HOST_URL = os.environ.get("CONTENT_ANALYTICS_HOST_URL", "").strip().rstrip("/")
CONTENT_ANALYTICS_FIRST_PARTY_PROXY_ENABLED = _env_is_true(
    "CONTENT_ANALYTICS_FIRST_PARTY_PROXY_ENABLED",
    False,
)
CONTENT_ANALYTICS_SYNC_ENABLED = _env_is_true("CONTENT_ANALYTICS_SYNC_ENABLED", True)
CONTENT_ANALYTICS_SYNC_LOOKBACK_DAYS = int(os.environ.get("CONTENT_ANALYTICS_SYNC_LOOKBACK_DAYS", "3") or 3)
CONTENT_ANALYTICS_SYNC_INTERVAL_SECONDS = int(os.environ.get("CONTENT_ANALYTICS_SYNC_INTERVAL_SECONDS", "86400") or 86400)
CONTENT_ANALYTICS_SYNC_MAX_BACKFILL_DAYS_PER_RUN = int(
    os.environ.get("CONTENT_ANALYTICS_SYNC_MAX_BACKFILL_DAYS_PER_RUN", "30") or 30
)
CONTENT_ANALYTICS_UMAMI_SOURCE_ATTRIBUTION_LIMIT = int(
    os.environ.get("CONTENT_ANALYTICS_UMAMI_SOURCE_ATTRIBUTION_LIMIT", "3") or 3
)
CONTENT_ANALYTICS_GSC_FINALIZATION_LAG_DAYS = int(
    os.environ.get("CONTENT_ANALYTICS_GSC_FINALIZATION_LAG_DAYS", "3") or 3
)
CONTENT_ANALYTICS_GSC_INITIAL_BACKFILL_DAYS = int(
    os.environ.get("CONTENT_ANALYTICS_GSC_INITIAL_BACKFILL_DAYS", "480") or 480
)
CONTENT_ANALYTICS_GSC_QUERY_LIMIT = int(os.environ.get("CONTENT_ANALYTICS_GSC_QUERY_LIMIT", "100") or 100)
CONTENT_ANALYTICS_ARTICLE_MANIFEST_LIMIT = int(
    os.environ.get("CONTENT_ANALYTICS_ARTICLE_MANIFEST_LIMIT", "500") or 500
)
CONTENT_ANALYTICS_UMAMI_RETENTION_DAYS = int(
    os.environ.get("CONTENT_ANALYTICS_UMAMI_RETENTION_DAYS", "120") or 120
)
# Daily article performance brief (immutable report snapshots). Rates are
# fractions of visits (0.03 = 3%).
CONTENT_ANALYTICS_REPORT_WINDOW_DAYS = int(
    os.environ.get("CONTENT_ANALYTICS_REPORT_WINDOW_DAYS", "7") or 7
)
CONTENT_ANALYTICS_REPORT_MIN_VISITS = int(
    os.environ.get("CONTENT_ANALYTICS_REPORT_MIN_VISITS", "20") or 20
)
CONTENT_ANALYTICS_REPORT_TOP_CONVERSION_RATE = float(
    os.environ.get("CONTENT_ANALYTICS_REPORT_TOP_CONVERSION_RATE", "0.03") or 0.03
)
CONTENT_ANALYTICS_REPORT_HIGH_ENGAGED_RATE = float(
    os.environ.get("CONTENT_ANALYTICS_REPORT_HIGH_ENGAGED_RATE", "0.40") or 0.40
)
CONTENT_ANALYTICS_REPORT_LOW_CTA_REACH_RATE = float(
    os.environ.get("CONTENT_ANALYTICS_REPORT_LOW_CTA_REACH_RATE", "0.50") or 0.50
)
# Scheduler for the daily brief: generates each enabled org's report once per
# org-local date, after the configured local hour. Off until the pilot passes.
CONTENT_ANALYTICS_REPORTS_ENABLED = _env_is_true("CONTENT_ANALYTICS_REPORTS_ENABLED", False)
CONTENT_ANALYTICS_REPORT_LOCAL_HOUR = int(
    os.environ.get("CONTENT_ANALYTICS_REPORT_LOCAL_HOUR", "7") or 7
)
CONTENT_ANALYTICS_REPORT_DEFAULT_TIMEZONE = (
    os.environ.get("CONTENT_ANALYTICS_REPORT_DEFAULT_TIMEZONE", "").strip()
    or "Australia/Melbourne"
)
# Report-ready delivery through the consented notification channels. Separate
# switch so briefs can accumulate silently before delivery is turned on.
CONTENT_ANALYTICS_REPORT_NOTIFICATIONS_ENABLED = _env_is_true(
    "CONTENT_ANALYTICS_REPORT_NOTIFICATIONS_ENABLED", False
)
# Customer.io transactional template for the report email; inline HTML is the
# fallback when unset (and Resend below that).
CUSTOMERIO_REPORT_TEMPLATE_ID = os.environ.get("CUSTOMERIO_REPORT_TEMPLATE_ID", "").strip()
GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT_JSON = os.environ.get(
    "GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT_JSON",
    "",
).strip()
GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT_FILE = os.environ.get(
    "GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT_FILE",
    "",
).strip()
GOOGLE_PLACES_API_KEY = os.environ.get("GOOGLE_PLACES_API_KEY", "")
# Google PageSpeed Insights key for website-baseline Lighthouse/Core Web Vitals.
# Managed here and handed to the content-factory producer via
# GET /api/content-factory/service/config so the key lives in one place.
PAGESPEED_API_KEY = os.environ.get("PAGESPEED_API_KEY", "")
ABR_LOOKUP_AUTHENTICATION_GUID = os.environ.get("ABR_LOOKUP_AUTHENTICATION_GUID", "")
# When true, the vibe-raising registration gate skips the live ABR lookup (used when no
# ABR credential is configured) but still enforces the ABN and ACN checksums and derives
# the ACN from the ABN. Lets registered companies with a valid ABN proceed without ABR.
VIBE_RAISING_SKIP_ABR_VERIFICATION = os.environ.get(
    "VIBE_RAISING_SKIP_ABR_VERIFICATION", ""
).strip().lower() in ("1", "true", "yes", "on")
# Roo points awarded to a founder of a verified registered company (valid ACN) the first
# time they complete a monthly update each month. 0 disables the reward.
ROO_POINTS_MONTHLY_UPDATE_REWARD = int(os.environ.get("ROO_POINTS_MONTHLY_UPDATE_REWARD", "20"))

# Founder-authorized connector OAuth settings
STRIPE_CONNECT_CLIENT_ID = _env_first(
    "STRIPE_CONNECT_CLIENT_ID",
    "STRIPE_CONNECT_OAUTH_CLIENT_ID",
    "STRIPE_CLIENT_ID",
)
STRIPE_SECRET_KEY = _env_first(
    "STRIPE_SECRET_KEY",
    "STRIPE_API_SECRET_KEY",
    "STRIPE_API_KEY",
)
# Dedicated secret key for the Vibe Raising Stripe Connect OAuth integration;
# STRIPE_SECRET_KEY may be a restricted rk_ key reserved for Roo point purchases.
STRIPE_VIBE_RAISING_KEY = _env_first(
    "STRIPE_VIBE_RAISING_KEY",
    "STRIPE_VIBE_RAISING_SECRET_KEY",
)
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_OAUTH_REDIRECT_URI = os.environ.get(
    "STRIPE_OAUTH_REDIRECT_URI",
    f"{DEFAULT_BACKEND_URL}/integrations/callback/stripe",
)
STRIPE_OAUTH_SCOPES = _env_list("STRIPE_OAUTH_SCOPES", ["read_only"])
STRIPE_API_VERSION = os.environ.get("STRIPE_API_VERSION", "2026-02-25.clover")
RECONCILIATION_DEFAULT_DOMAIN = os.environ.get("RECONCILIATION_DEFAULT_DOMAIN", "mlai.au")
RECONCILIATION_SCHEDULER_ENABLED = os.environ.get(
    "RECONCILIATION_SCHEDULER_ENABLED", "true"
).strip().lower() in ("1", "true", "yes", "on")

XERO_CLIENT_ID = os.environ.get("XERO_CLIENT_ID", "")
XERO_CLIENT_SECRET = os.environ.get("XERO_CLIENT_SECRET", "")
XERO_OAUTH_REDIRECT_URI = os.environ.get(
    "XERO_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/xero",
)
XERO_OAUTH_SCOPES = _env_list(
    "XERO_OAUTH_SCOPES",
    [
        "offline_access",
        "accounting.invoices.read",
        "accounting.payments.read",
        # Applying a bank payment to an existing ACCPAY bill is a write and
        # deliberately uses the narrow payments scope, not invoices.write.
        "accounting.payments",
        "accounting.settings.read",
        # Creating missing Event Name / Project Name tracking options is part
        # of the explicitly approved reconciliation posting operation.
        "accounting.settings",
        "accounting.contacts.read",
        # Required by the explicit Stripe-payout approval workflow. Existing
        # connections must reconnect once to grant this additional scope.
        "accounting.banktransactions",
    ],
)

# Automatic API writes are opt-in. Admin/Roo calls can still explicitly
# confirm one preview while the final statement-line reconciliation stays in
# Xero for a human to approve.
XERO_STATEMENT_AUTO_POST_ENABLED = os.environ.get(
    "XERO_STATEMENT_AUTO_POST_ENABLED", "false"
).strip().lower() in ("1", "true", "yes", "on")
XERO_STATEMENT_BANK_TRANSACTION_MIN_CONFIDENCE = float(
    os.environ.get("XERO_STATEMENT_BANK_TRANSACTION_MIN_CONFIDENCE", "0.92")
)
XERO_STATEMENT_BILL_PAYMENT_MIN_CONFIDENCE = float(
    os.environ.get("XERO_STATEMENT_BILL_PAYMENT_MIN_CONFIDENCE", "0.98")
)

NOTION_CLIENT_ID = os.environ.get("NOTION_CLIENT_ID", "")
NOTION_CLIENT_SECRET = os.environ.get("NOTION_CLIENT_SECRET", "")
NOTION_OAUTH_REDIRECT_URI = os.environ.get(
    "NOTION_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/notion",
)
NOTION_API_VERSION = os.environ.get("NOTION_API_VERSION", "2026-03-11")
NOTION_SYNC_PAGE_LIMIT = int(os.environ.get("NOTION_SYNC_PAGE_LIMIT", "20") or 20)

GOOGLE_DRIVE_OAUTH_REDIRECT_URI = os.environ.get(
    "GOOGLE_DRIVE_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/google-drive",
)
GOOGLE_DRIVE_OAUTH_SCOPES = _env_list(
    "GOOGLE_DRIVE_OAUTH_SCOPES",
    [
        "https://www.googleapis.com/auth/drive.readonly",
        "openid",
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile",
    ],
)

GOOGLE_ANALYTICS_OAUTH_REDIRECT_URI = os.environ.get(
    "GOOGLE_ANALYTICS_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/google-analytics",
)
GOOGLE_ANALYTICS_OAUTH_SCOPES = _env_list(
    "GOOGLE_ANALYTICS_OAUTH_SCOPES",
    [
        "https://www.googleapis.com/auth/analytics.readonly",
        "openid",
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile",
    ],
)

SLACK_CLIENT_ID = _env_first("FT_SLACK_CLIENT_ID", "SLACK_CLIENT_ID")
SLACK_CLIENT_SECRET = _env_first("FT_SLACK_CLIENT_SECRET", "SLACK_CLIENT_SECRET")
SLACK_OAUTH_REDIRECT_URI = _env_first(
    "FT_SLACK_OAUTH_REDIRECT_URI",
    "SLACK_OAUTH_REDIRECT_URI",
    default="http://localhost:8000/integrations/callback/slack",
)
SLACK_OAUTH_SCOPES = _env_list(
    "SLACK_OAUTH_SCOPES",
    [
        "channels:history",
        "channels:read",
        "groups:history",
        "groups:read",
        "team:read",
        "users:read",
    ],
)
SLACK_OAUTH_USER_SCOPES = _env_list("SLACK_OAUTH_USER_SCOPES", SLACK_OAUTH_SCOPES)
SLACK_OAUTH_BOT_SCOPES = _env_list("SLACK_OAUTH_BOT_SCOPES", [])
SLACK_SYNC_HISTORY_DAYS = int(os.environ.get("SLACK_SYNC_HISTORY_DAYS", "120") or 120)
SLACK_SYNC_HISTORY_PAGE_LIMIT = int(os.environ.get("SLACK_SYNC_HISTORY_PAGE_LIMIT", "100") or 100)
SLACK_SYNC_HISTORY_MAX_PAGES = int(os.environ.get("SLACK_SYNC_HISTORY_MAX_PAGES", "5") or 5)
SLACK_SYNC_REPLY_MAX_PAGES = int(os.environ.get("SLACK_SYNC_REPLY_MAX_PAGES", "3") or 3)
SLACK_SYNC_REPLY_PAGE_BUDGET = int(os.environ.get("SLACK_SYNC_REPLY_PAGE_BUDGET", "2") or 2)
SLACK_API_CONNECT_TIMEOUT_SECONDS = float(os.environ.get("SLACK_API_CONNECT_TIMEOUT_SECONDS", "3") or 3)
SLACK_API_READ_TIMEOUT_SECONDS = float(os.environ.get("SLACK_API_READ_TIMEOUT_SECONDS", "8") or 8)

LINEAR_API_KEY = os.environ.get("LINEAR_API_KEY", "")
LINEAR_CLIENT_ID = os.environ.get("LINEAR_CLIENT_ID", "")
LINEAR_CLIENT_SECRET = os.environ.get("LINEAR_CLIENT_SECRET", "")
LINEAR_OAUTH_REDIRECT_URI = os.environ.get(
    "LINEAR_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/linear",
)
LINEAR_OAUTH_SCOPES = _env_list("LINEAR_OAUTH_SCOPES", ["read"])
LINEAR_SYNC_PROJECT_PAGE_LIMIT = int(os.environ.get("LINEAR_SYNC_PROJECT_PAGE_LIMIT", "100") or 100)
LINEAR_SYNC_ISSUE_PAGE_LIMIT = int(os.environ.get("LINEAR_SYNC_ISSUE_PAGE_LIMIT", "50") or 50)
LINEAR_SYNC_UPDATE_PAGE_LIMIT = int(os.environ.get("LINEAR_SYNC_UPDATE_PAGE_LIMIT", "20") or 20)
LINEAR_API_CONNECT_TIMEOUT_SECONDS = float(os.environ.get("LINEAR_API_CONNECT_TIMEOUT_SECONDS", "3") or 3)
LINEAR_API_READ_TIMEOUT_SECONDS = float(os.environ.get("LINEAR_API_READ_TIMEOUT_SECONDS", "20") or 20)

BASIQ_API_KEY = os.environ.get("BASIQ_API_KEY", "")
BASIQ_API_BASE_URL = os.environ.get("BASIQ_API_BASE_URL", "https://au-api.basiq.io")
BASIQ_CONSENT_UI_URL = os.environ.get("BASIQ_CONSENT_UI_URL", "https://consent.basiq.io/home")
BASIQ_API_VERSION = os.environ.get("BASIQ_API_VERSION", "3.0")

# GitHub App Settings (for GitHub App installation flow)
GITHUB_APP_ID = os.environ.get("GITHUB_APP_ID")
GITHUB_APP_PRIVATE_KEY = os.environ.get("GITHUB_APP_PRIVATE_KEY")
GITHUB_OAUTH_CLIENT_ID = os.environ.get("GITHUB_OAUTH_CLIENT_ID")
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get("GITHUB_OAUTH_CLIENT_SECRET")
GITHUB_OAUTH_REDIRECT_URI = os.environ.get(
    "GITHUB_OAUTH_REDIRECT_URI",
    "http://localhost:8000/integrations/callback/github",
)
# Shared secret for verifying GitHub webhook deliveries (X-Hub-Signature-256).
# When unset, the webhook endpoint rejects every request, so publish state only
# advances via the best-effort poller.
GITHUB_WEBHOOK_SECRET = os.environ.get("GITHUB_WEBHOOK_SECRET", "")

# Points System Configuration
POINTS_BOOTSTRAP_ADMIN_SLACK_IDS = [s.strip() for s in os.getenv('POINTS_BOOTSTRAP_ADMIN_SLACK_IDS', '').split(',') if s.strip()]
DEFAULT_COWORKING_CAPACITY = int(os.getenv('DEFAULT_COWORKING_CAPACITY', '24'))
# Standard coworking cost. The active 'COWORKING_DAY' RewardsCatalog row takes
# precedence over this fallback when present (see CoworkingService).
COWORKING_DAY_COST_POINTS = int(os.getenv('COWORKING_DAY_COST_POINTS', '8'))
# Discounted cost charged when the user's startup has a 'ready' monthly update
# for the booking's month.
COWORKING_DAY_DISCOUNT_COST_POINTS = int(os.getenv('COWORKING_DAY_DISCOUNT_COST_POINTS', '4'))
COWORKING_REFUND_CUTOFF_HOURS = int(os.getenv('COWORKING_REFUND_CUTOFF_HOURS', '18'))  # 6pm prev day
COWORKING_BOOKING_ADVANCE_DAYS = int(os.environ.get('COWORKING_BOOKING_ADVANCE_DAYS', 30))

# Internal API Key for service-to-service auth (e.g. from Roo agent)
MLAI_API_KEY = os.environ.get('MLAI_API_KEY')
INTERNAL_API_KEY = os.environ.get('INTERNAL_API_KEY') or ROO_API_KEY or MLAI_API_KEY

# Dedicated, fail-closed access for read-only Victor application reports in Roo.
# This secret is used only to sign short-lived Slack actor assertions; the
# generic Roo/internal API keys are deliberately not accepted by these views.
VICTOR_AI_ROO_ENABLED = _env_is_true('VICTOR_AI_ROO_ENABLED', False)
VICTOR_AI_ROO_SIGNING_SECRET = os.environ.get('VICTOR_AI_ROO_SIGNING_SECRET', '').strip()
VICTOR_AI_ROO_ASSERTION_MAX_AGE_SECONDS = int(
    os.environ.get('VICTOR_AI_ROO_ASSERTION_MAX_AGE_SECONDS', '60') or 60
)
VICTOR_AI_ROO_ASSERTION_CLOCK_SKEW_SECONDS = int(
    os.environ.get('VICTOR_AI_ROO_ASSERTION_CLOCK_SKEW_SECONDS', '5') or 5
)
VICTOR_AI_ROO_EXPORT_MAX_ROWS = int(
    os.environ.get('VICTOR_AI_ROO_EXPORT_MAX_ROWS', '5000') or 5000
)
if VICTOR_AI_ROO_ENABLED:
    if len(VICTOR_AI_ROO_SIGNING_SECRET) < 32:
        raise ImproperlyConfigured(
            'VICTOR_AI_ROO_SIGNING_SECRET must contain at least 32 characters when enabled.'
        )
    if not 10 <= VICTOR_AI_ROO_ASSERTION_MAX_AGE_SECONDS <= 300:
        raise ImproperlyConfigured(
            'VICTOR_AI_ROO_ASSERTION_MAX_AGE_SECONDS must be between 10 and 300.'
        )
    if not 0 <= VICTOR_AI_ROO_ASSERTION_CLOCK_SKEW_SECONDS <= 30:
        raise ImproperlyConfigured(
            'VICTOR_AI_ROO_ASSERTION_CLOCK_SKEW_SECONDS must be between 0 and 30.'
        )
    if not 1 <= VICTOR_AI_ROO_EXPORT_MAX_ROWS <= 10000:
        raise ImproperlyConfigured(
            'VICTOR_AI_ROO_EXPORT_MAX_ROWS must be between 1 and 10000.'
        )
LUMA_API_KEY = os.environ.get('LUMA_API_KEY')
LUMA_BASE_URL = os.environ.get('LUMA_BASE_URL', 'https://public-api.luma.com')

# MedHack Game Configuration
MEDHACK_ADMIN_IDS = [s.strip() for s in os.getenv('MEDHACK_ADMIN_IDS', '').split(',') if s.strip()]
