# Generated by Django 4.2.16 on 2026-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic_hackathons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WattTheHackSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_scenarios",
                    models.CharField(
                        default="t1_welcome,t2_first_code",
                        help_text="Comma-separated list of unlocked scenario IDs (e.g. 't1_welcome,t2_first_code,s1_duck_curve')",
                        max_length=2000,
                    ),
                ),
                (
                    "auto_unlock",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, all scenarios NOT marked as judging will be unlocked automatically.",
                    ),
                ),
                (
                    "require_team_for_sim",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, users must be in a WTH team to use the sandbox.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watt The Hack Settings",
                "verbose_name_plural": "Watt The Hack Settings",
            },
        ),
    ]
