# Generated by Django 4.2.16 on 2026-06-03 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_leaders(apps, schema_editor):
    """Existing teams predate the leader field, and the bare M2M has no join timestamp, so the
    'creator' is unknown. Best-effort: assign the earliest-registered member (lowest user id)."""
    Team = apps.get_model('generic_hackathons', 'GenericHackathonTeam')
    for team in Team.objects.filter(leader__isnull=True):
        first_member = team.members.order_by('id').first()
        if first_member is not None:
            team.leader = first_member
            team.save(update_fields=['leader'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generic_hackathons', '0002_wattthehacksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generichackathonteam',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_generic_hackathon_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_leaders, migrations.RunPython.noop),
    ]
