# Generated by Django 4.2.16 on 2026-06-03 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generic_hackathons', '0003_generichackathonteam_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericHackathonJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='generic_hackathons.generichackathonteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_hackathon_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='generichackathonjoinrequest',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_generic_hackathon_join_request'),
        ),
    ]
