# Generated by Django 4.2.16 on 2026-06-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_hackathons', '0005_generichackathonteam_eval_token'),
        ('generic_hackathons', '0005_watt_session_cache_table'),
    ]

    operations = [
    ]
