# Generated by Django 4.2.16 on 2026-06-28 07:30

from collections import defaultdict

from django.db import migrations, models


def _normalize_domain(domain):
    """Inlined copy of integrations.utils.normalize_domain (migrations must not
    import app code, which can drift)."""
    if not domain:
        return ""
    domain = domain.strip().lower()
    if domain.startswith("https://"):
        domain = domain[8:]
    elif domain.startswith("http://"):
        domain = domain[7:]
    if domain.startswith("www."):
        domain = domain[4:]
    if "/" in domain:
        domain = domain.split("/")[0]
    return domain


def normalize_and_dedupe_company_domains(apps, schema_editor):
    """Make existing data satisfy the (profile, domain) partial-unique constraint.

    1. Normalize every stored domain (so http/www variants collapse).
    2. For each (profile, normalized-domain) group with more than one company,
       keep the profile's active company (else the oldest) and NULL the domain on
       the rest. Those companies already shared a single Organization, so this
       only makes the collision explicit; the domain can be re-entered to split
       them into their own Organization.
    """
    VibeRaisingCompany = apps.get_model("founder_tools", "VibeRaisingCompany")
    VibeRaisingProfile = apps.get_model("founder_tools", "VibeRaisingProfile")

    # 1. Normalize in place.
    for company in (
        VibeRaisingCompany.objects.exclude(domain__isnull=True)
        .exclude(domain="")
        .iterator()
    ):
        normalized = _normalize_domain(company.domain)
        if normalized != company.domain:
            company.domain = normalized
            company.save(update_fields=["domain"])

    # 2. Resolve duplicates.
    active_by_profile = {
        profile.id: profile.active_company_id
        for profile in VibeRaisingProfile.objects.all().only("id", "active_company")
    }
    groups = defaultdict(list)
    for company in (
        VibeRaisingCompany.objects.exclude(domain__isnull=True)
        .exclude(domain="")
        .order_by("created_at", "id")
    ):
        groups[(company.profile_id, company.domain)].append(company)

    for (profile_id, domain), companies in groups.items():
        if len(companies) < 2:
            continue
        active_id = active_by_profile.get(profile_id)
        keep = next((c for c in companies if active_id and c.id == active_id), companies[0])
        for company in companies:
            if company.id == keep.id:
                continue
            print(
                f"[0008] Nulling duplicate domain {domain!r} on company "
                f"{company.id} (profile {profile_id}); kept {keep.id}."
            )
            company.domain = None
            company.save(update_fields=["domain"])


class Migration(migrations.Migration):

    dependencies = [
        ('founder_tools', '0007_viberaisingcompany_avatar_url'),
    ]

    operations = [
        migrations.RunPython(
            normalize_and_dedupe_company_domains, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='viberaisingcompany',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', False), models.Q(('domain', ''), _negated=True)), fields=('profile', 'domain'), name='uniq_profile_domain'),
        ),
    ]
