# Generated by Django 4.2.16 on 2026-06-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder_tools', '0007_viberaisingcompany_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberaisingcompany',
            name='abr_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viberaisingcompany',
            name='acn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='viberaisingcompany',
            name='entity_type_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
