# Generated by Django 4.2.16 on 2026-07-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('founder_tools', '0008_viberaisingcompany_abr_verified_at_and_more'),
        ('founder_tools', '0008_viberaisingcompany_uniq_profile_domain'),
    ]

    operations = [
    ]
