# Generated by Django 4.2.16 on 2026-06-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder_tools', '0008_viberaisingcompany_abr_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viberaisingcompany',
            name='is_nonprofit',
            field=models.BooleanField(default=False),
        ),
    ]
