# Generated by Django 4.2.16 on 2026-05-13 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0017_alter_external_service_provider_choices'),
        ('content_factory', '0011_vibe_marketing_component_comment_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for_at', models.DateTimeField(db_index=True)),
                ('local_date', models.DateField(db_index=True)),
                ('slot_index', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('queued', 'Queued'), ('topic_selection_sent', 'Topic Selection Sent'), ('delivery_mode_required', 'Delivery Mode Required'), ('generating', 'Generating'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=32)),
                ('content_factory_run_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('article_content_factory_run_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('selected_topic', models.JSONField(blank=True, default=dict)),
                ('selected_delivery_mode', models.CharField(blank=True, default='', max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_factory_automation_run',
                'ordering': ['-scheduled_for_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('slack', 'Slack'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], db_index=True, max_length=20)),
                ('route_id', models.CharField(db_index=True, help_text='Slack user ID, E.164 WhatsApp number, or email address.', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('consent_state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('opted_out', 'Opted Out'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='organizations.organization')),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_notification_channels', to='integrations.externalserviceconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_factory_notification_channel',
                'ordering': ['organization_id', 'channel_type', 'route_id'],
            },
        ),
        migrations.CreateModel(
            name='ResearchAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('timezone', models.CharField(default='Australia/Melbourne', max_length=64)),
                ('frequency_per_day', models.PositiveSmallIntegerField(default=1)),
                ('local_send_times', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=20)),
                ('last_scheduled_for_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_automations', to='content_factory.notificationchannel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_automations', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_research_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_factory_research_automation',
                'ordering': ['organization_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opted_out', 'Opted Out')], db_index=True, default='pending', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='content_factory.automationrun')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='content_factory.notificationchannel')),
            ],
            options={
                'db_table': 'content_factory_notification_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='automationrun',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='content_factory.researchautomation'),
        ),
        migrations.AddIndex(
            model_name='researchautomation',
            index=models.Index(fields=['status', 'updated_at'], name='cf_research_auto_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchautomation',
            index=models.Index(fields=['organization', 'status'], name='cf_research_auto_org_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['event_type', 'status'], name='cf_notify_delivery_event_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status'], name='cf_notify_delivery_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['channel_type', 'consent_state'], name='cf_notify_channel_consent_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['user', 'channel_type'], name='cf_notify_channel_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationchannel',
            constraint=models.UniqueConstraint(fields=('organization', 'channel_type', 'route_id'), name='content_notify_channel_unique_route'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['status', 'scheduled_for_at'], name='cf_auto_run_due_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['content_factory_run_id'], name='cf_auto_run_cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.UniqueConstraint(fields=('automation', 'local_date', 'slot_index'), name='content_auto_run_unique_slot'),
        ),
    ]
