# Generated by Django 4.2.16 on 2026-06-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0012_research_automations'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='writtenarticle',
            index=models.Index(fields=['organization', '-created_at'], name='wa_org_created_idx'),
        ),
    ]
