# Generated by Django 4.2.16 on 2026-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0013_writtenarticle_wa_org_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFactoryCallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('job_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('emitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_factory_callback_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
