# Generated by Django 4.2.16 on 2026-06-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0014_contentfactorycallbackevent'),
        ('content_factory', '0014_writtenarticle_publish_status'),
    ]

    operations = [
    ]
