# Generated by Django 4.2.16 on 2026-06-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0017_backfill_writtenarticle_source_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='verification_code_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='verification_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='verification_send_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
