# Generated by Django 4.2.16 on 2026-06-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0019_notification_delivery_per_channel_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='article_system_setup_cache',
            field=models.JSONField(blank=True, default=dict, help_text='Self-contained component-reuse cache (inventory, managed files, context fingerprint) from the last scan.'),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='framework_component_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Framework-adapted component spec docs from the last scan, reused to skip regeneration.'),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='scan_request_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Fingerprint of the scan request shape; with last_scanned_sha lets an unchanged re-scan short-circuit instead of re-running.', max_length=64),
        ),
    ]
