# Generated by Django 4.2.16 on 2026-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0021_organizationcontentconfig_auto_publish_requires_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenarticle',
            name='content_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='writtenarticle',
            name='merge_commit_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='writtenarticle',
            name='on_main_commit_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='writtenarticle',
            name='on_main_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
