# Generated by Django 4.2.16 on 2026-06-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('content_factory', '0022_writtenarticle_content_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='directory_style_feedback',
            field=models.JSONField(blank=True, default=dict, help_text='Accepted directory visual-style report (renderer profile, page spec, component manifest).'),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='reference_screenshots',
            field=models.JSONField(blank=True, default=list, help_text='Hosted screenshot URLs of the live target site, used as image-generation references.'),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='renderer_style_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Derived Tailwind class profile applied by the article renderer.'),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='visual_context',
            field=models.JSONField(blank=True, default=dict, help_text='Computed design tokens + screenshot/page metadata captured from the live target site.'),
        ),
        migrations.CreateModel(
            name='WebsiteDesignSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveIntegerField(default=1, help_text="Version of the `spec` shape (owned by content-factory's design schema).")),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('github_repo', models.CharField(blank=True, default='', max_length=255)),
                ('repo_head_sha', models.CharField(blank=True, default='', max_length=40)),
                ('source_urls', models.JSONField(blank=True, default=list, help_text='Live URLs sampled to build this snapshot.')),
                ('screenshot_urls', models.JSONField(blank=True, default=list, help_text='Hosted screenshot URLs captured during the design scan.')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', help_text='active | superseded | capturing | failed', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('spec', models.JSONField(blank=True, default=dict, help_text='Structured design spec: typography, color system, components, layout, application rules.')),
                ('design_spec_md', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_snapshots', to='organizations.organization')),
            ],
            options={
                'db_table': 'content_factory_design_snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='cf_design_snapshot_active_idx')],
            },
        ),
    ]
