# Generated by Django 4.2.16 on 2026-06-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0025_orgconfig_use_component_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='authors',
            field=models.JSONField(blank=True, default=list, help_text='Article author profiles for this org: [{id, name, role, credentials, bio, avatarUrl, avatarAlt, url, sameAs}, ...].'),
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='default_author_id',
            field=models.CharField(blank=True, default='', help_text='id of the author in `authors` used as the byline when an article run does not name one.', max_length=128),
        ),
    ]
