# Generated by Django 4.2.16 on 2026-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0026_organizationcontentconfig_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfactoryhealingrecord',
            name='promotion_state',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('promoted', 'Promoted'), ('archived', 'Archived')], db_index=True, default='candidate', max_length=32),
        ),
    ]
