# Generated by Django 4.2.16 on 2026-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0027_healing_record_archived_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='scan_artifact_cache',
            field=models.JSONField(blank=True, default=dict, help_text='Scan context fingerprint cache from the last scan; lets a same-SHA re-scan prove its generation inputs are unchanged before replaying stored components.'),
        ),
    ]
