# Generated by Django 4.2.16 on 2026-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0028_organizationcontentconfig_scan_artifact_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='delivery_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this channel receives the daily research reminder and topic buttons. Independent of consent_state: unchecking it excludes the channel from delivery without revoking consent (so re-enabling needs no re-verification).'),
        ),
    ]
