# Generated by Django 4.2.16 on 2026-07-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0029_notificationchannel_delivery_enabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentfactoryhealingrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contentfactoryhealingrecord',
            name='framework',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='contentfactoryhealingrecord',
            unique_together={('domain', 'github_repo', 'failure_kind', 'failure_family_key', 'framework')},
        ),
        migrations.CreateModel(
            name='ContentFactoryLearningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(db_index=True, max_length=64)),
                ('scope', models.CharField(choices=[('repo', 'Repo'), ('framework', 'Framework')], db_index=True, default='repo', max_length=32)),
                ('repo_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('framework', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('entry_key', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurrences', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_factory_learning_entry',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['store', 'repo_name'], name='cf_learning_store_repo_idx'), models.Index(fields=['store', 'scope', 'framework'], name='cf_learning_store_fw_idx')],
                'unique_together': {('store', 'scope', 'repo_name', 'framework', 'entry_key')},
            },
        ),
    ]
