# Generated by Django 4.2.16 on 2026-07-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_analytics', '0003_articleperformancereport_and_more'),
        ('content_factory', '0034_keywordvelocity_trend_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='performance_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to='content_analytics.articleperformancereport'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='automation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='content_factory.automationrun'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(check=models.Q(('automation_run__isnull', False), ('performance_report__isnull', False), _connector='OR'), name='cf_notify_delivery_has_subject'),
        ),
    ]
