# Generated by Django 4.2.16 on 2026-08-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_factory', '0035_notificationdelivery_performance_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchedkeyword',
            name='ai_search_volume',
            field=models.IntegerField(blank=True, help_text='Monthly AI-assistant search volume, when measured', null=True),
        ),
        migrations.AddField(
            model_name='researchedkeyword',
            name='ai_monthly_searches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchedkeyword',
            name='aeo_score',
            field=models.FloatField(blank=True, help_text='Answer-engine visibility score, when measured', null=True),
        ),
        migrations.AddField(
            model_name='researchedkeyword',
            name='query_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
