# Generated by Django 4.2.16 on 2026-08-23 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('content_factory', '0036_researched_keyword_ai_search_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIsland',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('pillar_keyword', models.CharField(help_text='Centroid keyword; the island-scoped discovery dispatch keyword', max_length=200)),
                ('icon_key', models.CharField(default='default', max_length=32)),
                ('color_key', models.CharField(default='purple', max_length=32)),
                ('status', models.CharField(choices=[('emerging', 'Emerging'), ('visible', 'Visible'), ('archived', 'Archived')], db_index=True, default='emerging', max_length=20)),
                ('origin', models.CharField(choices=[('pillar_strategy_seed', 'Pillar Strategy Seed'), ('cluster_birth', 'Cluster Birth'), ('manual', 'Manual')], default='cluster_birth', max_length=32)),
                ('centroid_embedding', models.JSONField(blank=True, default=list)),
                ('keyword_count', models.IntegerField(default=0)),
                ('total_volume', models.IntegerField(default=0)),
                ('avg_difficulty', models.FloatField(default=0.0)),
                ('opportunity_score', models.FloatField(db_index=True, default=0.0)),
                ('ai_search_volume', models.IntegerField(default=0)),
                ('articles_written', models.IntegerField(default=0)),
                ('consecutive_misses', models.IntegerField(default=0)),
                ('last_missed_on', models.DateField(blank=True, null=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('last_expanded_on', models.DateField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_islands', to='organizations.organization')),
            ],
            options={
                'db_table': 'seo_content_island',
                'ordering': ['-opportunity_score', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ContentIslandSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_on', models.DateField(db_index=True)),
                ('keyword_count', models.IntegerField(default=0)),
                ('total_volume', models.IntegerField(default=0)),
                ('avg_difficulty', models.FloatField(default=0.0)),
                ('opportunity_score', models.FloatField(default=0.0)),
                ('ai_search_volume', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('emerging', 'Emerging'), ('visible', 'Visible'), ('archived', 'Archived')], default='emerging', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='content_factory.contentisland')),
            ],
            options={
                'db_table': 'seo_content_island_snapshot',
                'ordering': ['-captured_on'],
                'unique_together': {('island', 'captured_on')},
            },
        ),
        migrations.CreateModel(
            name='ContentIslandRefreshDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('content_factory_run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_island_refresh_dispatches', to='organizations.organization')),
            ],
            options={
                'db_table': 'seo_content_island_refresh_dispatch',
                'ordering': ['-local_date', '-updated_at'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='seo_island_disp_state_idx')],
                'unique_together': {('organization', 'local_date')},
            },
        ),
        migrations.CreateModel(
            name='ContentIslandKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('is_centroid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='content_factory.contentisland')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='island_memberships', to='content_factory.researchedkeyword')),
            ],
            options={
                'db_table': 'seo_content_island_keyword',
                'indexes': [models.Index(fields=['island', 'is_centroid'], name='seo_island_kw_centroid_idx')],
                'unique_together': {('island', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='ContentIslandEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('island_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='content_factory.contentisland')),
                ('island_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='content_factory.contentisland')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_island_edges', to='organizations.organization')),
            ],
            options={
                'db_table': 'seo_content_island_edge',
                'ordering': ['-similarity'],
                'indexes': [models.Index(fields=['organization', '-similarity'], name='seo_island_edge_org_sim_idx')],
                'unique_together': {('island_a', 'island_b')},
            },
        ),
        migrations.AddIndex(
            model_name='contentisland',
            index=models.Index(fields=['organization', 'status'], name='seo_island_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contentisland',
            index=models.Index(fields=['organization', '-opportunity_score'], name='seo_island_org_opp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentisland',
            unique_together={('organization', 'slug')},
        ),
    ]
