# Generated by Django 4.2.16 on 2026-10-04 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_factory', '0041_writtenarticle_editorial_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('github_repo', models.CharField(max_length=255)),
                ('installation_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('app_root', models.CharField(blank=True, default='', max_length=500)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('site_url', models.CharField(blank=True, default='', max_length=512)),
                ('state', models.CharField(choices=[('connected', 'Connected'), ('paused', 'Publishing paused'), ('disconnected', 'Disconnected'), ('revoked', 'Provider access revoked')], default='connected', max_length=20)),
                ('generation', models.PositiveBigIntegerField(default=1)),
                ('configuration_version', models.PositiveBigIntegerField(default=1)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('verified_sha', models.CharField(blank=True, default='', max_length=64)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_websites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_connections', to='organizations.organization')),
            ],
            options={
                'db_table': 'content_factory_website_connection',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTemplateRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('source_sha', models.CharField(blank=True, default='', max_length=64)),
                ('provenance', models.CharField(max_length=40)),
                ('status', models.CharField(default='validated', max_length=20)),
                ('body', models.TextField()),
                ('validation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_revisions', to='content_factory.websiteconnection')),
            ],
            options={
                'db_table': 'content_factory_website_template',
            },
        ),
        migrations.CreateModel(
            name='WebsiteScanSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField()),
                ('run_id', models.CharField(max_length=100)),
                ('source_sha', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(max_length=64)),
                ('detector_version', models.CharField(blank=True, default='', max_length=100)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_snapshots', to='content_factory.websiteconnection')),
            ],
            options={
                'db_table': 'content_factory_website_scan',
            },
        ),
        migrations.CreateModel(
            name='WebsiteRepositoryMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField()),
                ('operation_id', models.CharField(max_length=200, unique=True)),
                ('run_id', models.CharField(blank=True, default='', max_length=100)),
                ('base_sha', models.CharField(max_length=64)),
                ('head_sha', models.CharField(blank=True, default='', max_length=64)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('pr_url', models.URLField(blank=True, default='', max_length=1000)),
                ('patch_digest', models.CharField(max_length=64)),
                ('files', models.JSONField(default=list)),
                ('status', models.CharField(default='proposed', max_length=32)),
                ('cleanup', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_mutations', to='content_factory.websiteconnection')),
            ],
            options={
                'db_table': 'content_factory_website_mutation',
            },
        ),
        migrations.CreateModel(
            name='WebsiteConnectionTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_key', models.CharField(max_length=255)),
                ('generation', models.PositiveBigIntegerField()),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('adapter', models.CharField(blank=True, default='', max_length=100)),
                ('adapter_version', models.CharField(blank=True, default='', max_length=100)),
                ('source_sha', models.CharField(blank=True, default='', max_length=64)),
                ('contract', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='content_factory.websiteconnection')),
            ],
            options={
                'db_table': 'content_factory_website_target',
            },
        ),
        migrations.CreateModel(
            name='WebsiteConnectionOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('action', models.CharField(max_length=32)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('receipt', models.JSONField(default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='content_factory.websiteconnection')),
            ],
            options={
                'db_table': 'content_factory_website_operation',
            },
        ),
        migrations.AddField(
            model_name='organizationcontentconfig',
            name='website_connection',
            field=models.ForeignKey(blank=True, help_text='Selected website; its generation is the publication consent authority.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_configs', to='content_factory.websiteconnection'),
        ),
        migrations.AddConstraint(
            model_name='websitetemplaterevision',
            constraint=models.UniqueConstraint(fields=('connection', 'purpose', 'digest'), name='cf_web_template_digest_unique'),
        ),
        migrations.AddConstraint(
            model_name='websitescansnapshot',
            constraint=models.UniqueConstraint(fields=('connection', 'generation', 'run_id', 'fingerprint'), name='cf_web_scan_identity_unique'),
        ),
        migrations.AddIndex(
            model_name='websiterepositorymutation',
            index=models.Index(fields=['connection', 'status'], name='cf_web_mutation_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='websiteconnectiontarget',
            constraint=models.UniqueConstraint(fields=('connection', 'target_key'), name='cf_web_target_key_unique'),
        ),
        migrations.AddIndex(
            model_name='websiteconnectionoperation',
            index=models.Index(fields=['state', 'next_attempt_at'], name='cf_web_operation_due_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteconnection',
            index=models.Index(fields=['organization', 'state'], name='cf_web_org_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='websiteconnection',
            constraint=models.CheckConstraint(check=models.Q(('generation__gte', 1)), name='cf_web_generation_positive'),
        ),
    ]
