# Generated by Django 5.1.5 on 2025-11-25 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='esafety_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
