# Generated by Django 5.1.5 on 2025-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esafety', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
