# Generated by Django 5.1.5 on 2025-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esafety', '0004_team_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(help_text='Supports Markdown (bold, italics, etc.)'),
        ),
    ]
