# Generated by Django 5.1.5 on 2025-11-30 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esafety', '0005_alter_announcement_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='coarse_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='fine_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100)),
                ('predicted_labels', models.JSONField()),
                ('correct_labels', models.JSONField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='esafety.submission')),
            ],
        ),
    ]
