# Generated by Django 5.1.5 on 2025-11-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esafety', '0006_submission_coarse_score_submission_fine_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='logs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
