# Generated by Django 5.1.5 on 2025-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esafety', '0007_submission_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
