# Generated by Django 4.2.16 on 2026-07-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VictorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ref', models.CharField(max_length=64, unique=True)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('complete', 'Complete')], default='lead', max_length=16)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('startup_stage', models.CharField(blank=True, max_length=64)),
                ('industry_sector', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('idea', models.TextField(blank=True)),
                ('support', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
