# Generated by Django 4.2.16 on 2026-07-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victor_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victorapplication',
            name='revenue_last_3_months',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='victorapplication',
            name='team_members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='victorapplication',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
