# Generated by Django 4.2.16 on 2026-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victor_ai', '0002_victorapplication_revenue_last_3_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victorapplication',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
