# Generated by Django 4.2 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victor_ai', '0003_victorapplication_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VictorRooRequestReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=128, unique=True)),
                ('request_id', models.CharField(db_index=True, max_length=128)),
                ('event_id', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='VictorApplicationAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('slack_team_id', models.CharField(db_index=True, max_length=32)),
                ('slack_channel_id', models.CharField(db_index=True, max_length=32)),
                ('acting_slack_user_id', models.CharField(db_index=True, max_length=32)),
                ('request_id', models.CharField(db_index=True, max_length=128)),
                ('target_application_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(default='success', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
