# Generated by Django 5.1.5 on 2025-12-17 07:37

import integrations.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('slack_user_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('github_access_token', integrations.fields.EncryptedTextField(blank=True, null=True)),
                ('github_user_name', models.TextField(blank=True, null=True)),
                ('github_scopes', models.JSONField(blank=True, default=list)),
                ('project_scanned', models.BooleanField(default=False)),
                ('pending_intent', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_integrations',
            },
        ),
    ]
