# Generated by Django 4.2.16 on 2025-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_userintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='github_repo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
