# Generated by Django 4.2.16 on 2025-12-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_add_github_repo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='last_scanned_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
