# Generated by Django 4.2.16 on 2026-03-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_startupprofile_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailattachmentartifact',
            name='content_disposition',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gmailattachmentartifact',
            name='gmail_attachment_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='gmailattachmentartifact',
            name='part_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
