# Generated by Django 4.2.16 on 2026-04-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_gmailattachmentartifact_content_disposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBridgeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_channel_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slack_channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('discord_guild_id', models.CharField(blank=True, default='', max_length=100)),
                ('discord_channel_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('discord_channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('sync_edits', models.BooleanField(default=True)),
                ('sync_deletes', models.BooleanField(default=True)),
                ('sync_replies', models.BooleanField(default=True)),
                ('pilot_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'community_bridge_channel',
                'ordering': ['slack_channel_id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityBridgeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=20)),
                ('receipt_key', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_channel_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_parent_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('enqueued', 'Enqueued'), ('ignored', 'Ignored'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], db_index=True, default='accepted', max_length=20)),
                ('queued_delivery_count', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='integrations.communitybridgechannel')),
            ],
            options={
                'db_table': 'community_bridge_receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityBridgeMessageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_platform', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=20)),
                ('source_channel_id', models.CharField(db_index=True, max_length=100)),
                ('source_message_id', models.CharField(db_index=True, max_length=100)),
                ('source_parent_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_author_id', models.CharField(blank=True, default='', max_length=100)),
                ('destination_platform', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=20)),
                ('destination_channel_id', models.CharField(db_index=True, max_length=100)),
                ('destination_message_id', models.CharField(db_index=True, max_length=100)),
                ('destination_parent_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('destination_payload', models.JSONField(blank=True, default=dict)),
                ('source_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('destination_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='integrations.communitybridgechannel')),
            ],
            options={
                'db_table': 'community_bridge_message_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityBridgeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_platform', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=20)),
                ('source_platform', models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=20)),
                ('delivery_type', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=20)),
                ('source_event_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_channel_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_message_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source_parent_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_channel_id', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.communitybridgechannel')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='integrations.communitybridgereceipt')),
            ],
            options={
                'db_table': 'community_bridge_delivery',
                'ordering': ['available_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='communitybridgereceipt',
            index=models.Index(fields=['platform', 'status', 'created_at'], name='bridge_rcpt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communitybridgereceipt',
            index=models.Index(fields=['source_channel_id', 'source_message_id'], name='bridge_rcpt_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitybridgereceipt',
            constraint=models.UniqueConstraint(fields=('platform', 'receipt_key'), name='community_bridge_receipt_platform_key_unique'),
        ),
        migrations.AddIndex(
            model_name='communitybridgemessagelink',
            index=models.Index(fields=['source_platform', 'source_channel_id', 'source_message_id'], name='bridge_link_source_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='communitybridgemessagelink',
            index=models.Index(fields=['destination_platform', 'destination_channel_id', 'destination_message_id'], name='bridge_link_dest_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitybridgemessagelink',
            constraint=models.UniqueConstraint(fields=('source_platform', 'source_channel_id', 'source_message_id', 'destination_platform'), name='community_bridge_link_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='communitybridgemessagelink',
            constraint=models.UniqueConstraint(fields=('destination_platform', 'destination_channel_id', 'destination_message_id', 'source_platform'), name='community_bridge_link_destination_unique'),
        ),
        migrations.AddIndex(
            model_name='communitybridgedelivery',
            index=models.Index(fields=['status', 'available_at'], name='bridge_dlv_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='communitybridgedelivery',
            index=models.Index(fields=['target_platform', 'status', 'available_at'], name='bridge_dlv_tgt_idx'),
        ),
        migrations.AddIndex(
            model_name='communitybridgedelivery',
            index=models.Index(fields=['source_platform', 'source_message_id'], name='bridge_dlv_src_msg_idx'),
        ),
    ]
