# Generated by Django 4.2.16 on 2026-04-24 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import integrations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_delete_viberaisingpendingsignup'),
        ('organizations', '0001_split_content_factory_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0009_communitybridgechannel_communitybridgereceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('xero', 'Xero'), ('bank_feed', 'Bank Feed'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('slack', 'Slack')], db_index=True, max_length=32)),
                ('access_token', integrations.fields.EncryptedTextField(blank=True, default='')),
                ('refresh_token', integrations.fields.EncryptedTextField(blank=True, default='')),
                ('token_type', models.CharField(blank=True, default='', max_length=64)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('account_label', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('syncing', 'Syncing'), ('error', 'Error'), ('disconnected', 'Disconnected')], db_index=True, default='connected', max_length=32)),
                ('sync_cursor', models.JSONField(blank=True, default=dict)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_service_connections', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_service_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'provider'], name='extsvc_user_provider_idx'), models.Index(fields=['organization', 'provider'], name='extsvc_org_provider_idx'), models.Index(fields=['provider', 'external_account_id'], name='extsvc_provider_extid_idx')],
            },
        ),
    ]
