# Generated by Django 4.2.16 on 2026-04-24 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import integrations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_delete_viberaisingpendingsignup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0009_communitybridgechannel_communitybridgereceipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('xero', 'Xero'), ('basiq', 'Basiq')], db_index=True, max_length=20)),
                ('external_account_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', integrations.fields.EncryptedTextField(blank=True, null=True)),
                ('refresh_token', integrations.fields.EncryptedTextField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, default='', max_length=64)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('action_required', 'Action Required'), ('disconnected', 'Disconnected'), ('error', 'Error')], db_index=True, default='connected', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_connections', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('xero', 'Xero'), ('basiq', 'Basiq')], db_index=True, max_length=20)),
                ('external_account_id', models.CharField(db_index=True, max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(blank=True, default='', max_length=12)),
                ('account_type', models.CharField(blank=True, default='', max_length=64)),
                ('selected_for_revenue', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='integrations.financialconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('xero', 'Xero'), ('basiq', 'Basiq')], db_index=True, max_length=20)),
                ('object_type', models.CharField(choices=[('subscription', 'Subscription'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('repeating_invoice', 'Repeating Invoice'), ('bank_transaction', 'Bank Transaction'), ('bank_account', 'Bank Account')], db_index=True, max_length=40)),
                ('external_id', models.CharField(max_length=255)),
                ('source_status', models.CharField(blank=True, default='', max_length=100)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=255)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=12)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at_source', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_records', to='integrations.financialaccount')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_records', to='integrations.financialconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_financial_records', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('currency', models.CharField(db_index=True, max_length=12)),
                ('mrr_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('mrr_growth_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('mrr_delta', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('cash_collected_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('recognized_revenue_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_mix', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_record_ids', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_revenue_snapshots', to='core.organization')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_revenue_snapshots', to='core.contentfactoryrun')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'month'], name='monthly_revenue_org_month_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyrevenuesnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'month', 'currency'), name='monthly_revenue_snapshot_org_month_currency_unique'),
        ),
        migrations.AddIndex(
            model_name='financialconnection',
            index=models.Index(fields=['organization', 'provider', 'status'], name='fin_conn_org_prov_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='financialconnection',
            index=models.Index(fields=['user', 'provider', 'updated_at'], name='fin_conn_user_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'external_account_id'), name='financial_connection_provider_external_unique'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['organization', 'provider'], name='fin_account_org_provider_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('connection', 'external_account_id'), name='financial_account_connection_external_unique'),
        ),
        migrations.AddIndex(
            model_name='externalfinancialrecord',
            index=models.Index(fields=['organization', 'provider', 'object_type'], name='fin_rec_org_prov_type_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfinancialrecord',
            index=models.Index(fields=['organization', 'period_start'], name='fin_record_org_period_idx'),
        ),
        migrations.AddIndex(
            model_name='externalfinancialrecord',
            index=models.Index(fields=['organization', 'currency'], name='fin_record_org_currency_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalfinancialrecord',
            constraint=models.UniqueConstraint(fields=('connection', 'object_type', 'external_id'), name='external_financial_record_unique'),
        ),
    ]
