# Generated by Django 4.2.16 on 2026-04-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_runs', '0001_split_content_factory_apps'),
        ('organizations', '0001_split_content_factory_apps'),
        ('integrations', '0010_external_service_connection'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='gmailattachmentartifact',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_attachment_artifacts', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='gmailmessageartifact',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_message_artifacts', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='gmailsynccursor',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_sync_cursors', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='gmailthreadartifact',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_thread_artifacts', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='monthlyupdatedraft',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_update_drafts', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='monthlyupdatedraft',
                    name='run',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_update_drafts', to='workflow_runs.contentfactoryrun'),
                ),
                migrations.AlterField(
                    model_name='startupevent',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_events', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='startupevent',
                    name='run',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_events', to='workflow_runs.contentfactoryrun'),
                ),
                migrations.AlterField(
                    model_name='startupmetricobservation',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_metric_observations', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='startupmetricobservation',
                    name='run',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_metric_observations', to='workflow_runs.contentfactoryrun'),
                ),
                migrations.AlterField(
                    model_name='startupprofile',
                    name='organization',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to='organizations.organization'),
                ),
                migrations.AlterField(
                    model_name='userstartupbinding',
                    name='organization',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_startup_bindings', to='organizations.organization'),
                ),
            ],
        ),
    ]
