# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0012_financial_account_external_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalfinancialrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("bank_transaction", "Bank Transaction"),
                    ("xero_repeating_invoice", "Xero Repeating Invoice"),
                    ("xero_invoice", "Xero Invoice"),
                    ("xero_payment", "Xero Payment"),
                ],
                db_index=True,
                default="bank_transaction",
                max_length=64,
            ),
        ),
    ]
