# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0013_xero_financial_record_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="startupmetricobservation",
            name="source_provider",
            field=models.CharField(blank=True, db_index=True, default="gmail", max_length=32),
        ),
        migrations.AddField(
            model_name="startupmetricobservation",
            name="source_record_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="startupmetricobservation",
            name="source_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="startupmetricobservation",
            index=models.Index(
                fields=["organization", "source_provider", "period_month"],
                name="startup_metric_org_source_idx",
            ),
        ),
    ]
