# Generated by Codex on 2026-04-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_split_content_factory_apps"),
        ("integrations", "0014_startup_metric_source_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackChannelSelection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(blank=True, default="", max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                ("selected", models.BooleanField(db_index=True, default=False)),
                ("sync_cursor", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slack_channel_selections", to="integrations.externalserviceconnection")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="slack_channel_selections", to="organizations.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slack_channel_selections", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["channel_name", "channel_id"],
            },
        ),
        migrations.CreateModel(
            name="SlackMessageArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(blank=True, default="", max_length=255)),
                ("slack_message_ts", models.CharField(max_length=64)),
                ("thread_ts", models.CharField(blank=True, default="", max_length=64)),
                ("parent_ts", models.CharField(blank=True, default="", max_length=64)),
                ("author_id", models.CharField(blank=True, default="", max_length=100)),
                ("author_name", models.CharField(blank=True, default="", max_length=255)),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("text", models.TextField(blank=True, default="")),
                ("cleaned_text", models.TextField(blank=True, default="")),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slack_message_artifacts", to="integrations.externalserviceconnection")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slack_message_artifacts", to="organizations.organization")),
            ],
            options={
                "ordering": ["-posted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SlackThreadArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel_id", models.CharField(max_length=100)),
                ("channel_name", models.CharField(blank=True, default="", max_length=255)),
                ("thread_ts", models.CharField(max_length=64)),
                ("source_message_ids", models.JSONField(blank=True, default=list)),
                ("source_message_count", models.IntegerField(default=0)),
                ("cleaned_text", models.TextField(blank=True, default="")),
                ("participant_summary", models.JSONField(blank=True, default=dict)),
                ("message_payloads", models.JSONField(blank=True, default=list)),
                ("latest_message_at", models.DateTimeField(blank=True, null=True)),
                ("extraction_status", models.CharField(choices=[("pending", "Pending"), ("hydrated", "Hydrated"), ("processed", "Processed"), ("unsupported", "Unsupported"), ("error", "Error")], db_index=True, default="pending", max_length=20)),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slack_thread_artifacts", to="integrations.externalserviceconnection")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slack_thread_artifacts", to="organizations.organization")),
            ],
            options={
                "ordering": ["-latest_message_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="slackchannelselection",
            constraint=models.UniqueConstraint(fields=("connection", "channel_id"), name="slack_channel_selection_conn_channel_uniq"),
        ),
        migrations.AddIndex(
            model_name="slackchannelselection",
            index=models.Index(fields=["user", "selected"], name="slack_chan_user_selected_idx"),
        ),
        migrations.AddIndex(
            model_name="slackchannelselection",
            index=models.Index(fields=["organization", "selected"], name="slack_chan_org_selected_idx"),
        ),
        migrations.AddConstraint(
            model_name="slackmessageartifact",
            constraint=models.UniqueConstraint(fields=("organization", "connection", "channel_id", "slack_message_ts"), name="slack_message_org_conn_channel_ts_uniq"),
        ),
        migrations.AddIndex(
            model_name="slackmessageartifact",
            index=models.Index(fields=["organization", "channel_id", "posted_at"], name="slack_msg_org_channel_post_idx"),
        ),
        migrations.AddIndex(
            model_name="slackmessageartifact",
            index=models.Index(fields=["organization", "thread_ts"], name="slack_msg_org_thread_idx"),
        ),
        migrations.AddConstraint(
            model_name="slackthreadartifact",
            constraint=models.UniqueConstraint(fields=("organization", "connection", "channel_id", "thread_ts"), name="slack_thread_org_conn_channel_ts_uniq"),
        ),
        migrations.AddIndex(
            model_name="slackthreadartifact",
            index=models.Index(fields=["organization", "extraction_status"], name="slack_thread_org_extract_idx"),
        ),
        migrations.AddIndex(
            model_name="slackthreadartifact",
            index=models.Index(fields=["organization", "latest_message_at"], name="slack_thread_org_latest_idx"),
        ),
    ]
