# Generated by Codex on 2026-04-25

from django.db import migrations, models


PROVIDER_CHOICES = [
    ("stripe", "Stripe"),
    ("xero", "Xero"),
    ("bank_feed", "Bank Feed"),
    ("notion", "Notion"),
    ("google_drive", "Google Drive"),
    ("slack", "Slack"),
    ("linear", "Linear"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0016_split_startup_updates_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalfinancialrecord",
            name="provider",
            field=models.CharField(choices=PROVIDER_CHOICES, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="externalserviceconnection",
            name="provider",
            field=models.CharField(choices=PROVIDER_CHOICES, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="financialaccount",
            name="provider",
            field=models.CharField(choices=PROVIDER_CHOICES, db_index=True, max_length=32),
        ),
    ]
