# Generated by Django 4.2.16 on 2026-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_google_analytics_provider_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfinancialrecord',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('xero', 'Xero'), ('bank_feed', 'Bank Feed'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('google_analytics', 'Google Analytics'), ('luma', 'Luma')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='externalserviceconnection',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('xero', 'Xero'), ('bank_feed', 'Bank Feed'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('google_analytics', 'Google Analytics'), ('luma', 'Luma')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('xero', 'Xero'), ('bank_feed', 'Bank Feed'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('google_analytics', 'Google Analytics'), ('luma', 'Luma')], db_index=True, max_length=32),
        ),
    ]
