# Generated by Django 4.2.16 on 2026-06-28 07:48

from django.db import migrations, models


def backfill_and_dedupe_connections(apps, schema_editor):
    """Make existing data satisfy the (user, organization, provider,
    external_account_id) unique constraint.

    1. Backfill NULL organization from the user's default Gmail binding (else
       their only binding), so legacy connections created before org-scoped
       OAuth state get attributed to a startup.
    2. Drop exact duplicates on the constraint key, keeping the most recently
       updated row (the prior (user, provider) upsert logic should mean there
       are none, but be defensive so AddConstraint cannot fail).
    """
    ExternalServiceConnection = apps.get_model("integrations", "ExternalServiceConnection")
    UserStartupBinding = apps.get_model("startup_updates", "UserStartupBinding")

    # 1. Backfill NULL organization from bindings.
    bindings_by_user = {}
    for binding in UserStartupBinding.objects.all().only(
        "user_id", "organization_id", "is_default_for_gmail", "updated_at"
    ):
        bindings_by_user.setdefault(binding.user_id, []).append(binding)

    for connection in ExternalServiceConnection.objects.filter(
        organization__isnull=True
    ).only("id", "user_id"):
        candidates = bindings_by_user.get(connection.user_id) or []
        if not candidates:
            continue
        default = next((b for b in candidates if b.is_default_for_gmail), None)
        chosen = default or (candidates[0] if len(candidates) == 1 else None)
        if chosen is not None and chosen.organization_id is not None:
            connection.organization_id = chosen.organization_id
            connection.save(update_fields=["organization"])

    # 2. Dedupe on the constraint key.
    seen = set()
    for connection in ExternalServiceConnection.objects.all().order_by(
        "-updated_at", "-id"
    ).only("id", "user_id", "organization_id", "provider", "external_account_id"):
        key = (
            connection.user_id,
            connection.organization_id,
            connection.provider,
            connection.external_account_id,
        )
        if key in seen:
            print(
                f"[0020] Deleting duplicate connection {connection.id} "
                f"(user={connection.user_id}, org={connection.organization_id}, "
                f"provider={connection.provider})."
            )
            connection.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_luma_provider_choice'),
        ('startup_updates', '0013_luma_event_selection'),
    ]

    operations = [
        migrations.RunPython(
            backfill_and_dedupe_connections, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='externalserviceconnection',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'provider', 'external_account_id'), name='uniq_user_org_provider_account'),
        ),
    ]
