# Generated by Django 4.2.16 on 2026-06-28 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_google_connection_organizations(apps, schema_editor):
    """Attribute each existing Gmail connection to a startup.

    Until now GoogleConnection was OneToOne(user), so every user has at most one
    connection. Assign it to the user's default Gmail binding (else their only
    binding) so it lands under the right startup before the (user, organization)
    constraint is added.
    """
    GoogleConnection = apps.get_model("integrations", "GoogleConnection")
    UserStartupBinding = apps.get_model("startup_updates", "UserStartupBinding")

    bindings_by_user = {}
    for binding in UserStartupBinding.objects.all().only(
        "user_id", "organization_id", "is_default_for_gmail"
    ):
        bindings_by_user.setdefault(binding.user_id, []).append(binding)

    for connection in GoogleConnection.objects.filter(organization__isnull=True).only(
        "id", "user_id"
    ):
        candidates = bindings_by_user.get(connection.user_id) or []
        if not candidates:
            continue
        default = next((b for b in candidates if b.is_default_for_gmail), None)
        chosen = default or (candidates[0] if len(candidates) == 1 else None)
        if chosen is not None and chosen.organization_id is not None:
            connection.organization_id = chosen.organization_id
            connection.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_company_linkedin_url'),
        ('integrations', '0020_externalserviceconnection_uniq_user_org_provider_account'),
        ('startup_updates', '0013_luma_event_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleconnection',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_connections', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='googleconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            backfill_google_connection_organizations, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='googleconnection',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uniq_google_connection_user_org'),
        ),
    ]
