# Generated by Django 4.2.16 on 2026-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_githubinstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubinstallation',
            name='liveness_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
