# Generated by Django 4.2 on 2026-07-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_company_linkedin_url"),
        ("integrations", "0023_githubinstallation_liveness_checked_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_account_id", models.CharField(blank=True, default="", max_length=255)),
                ("xero_bank_account_id", models.CharField(blank=True, default="", max_length=255)),
                ("xero_bank_account_name", models.CharField(blank=True, default="", max_length=255)),
                ("xero_contact_id", models.CharField(blank=True, default="", max_length=255)),
                ("xero_contact_name", models.CharField(default="Stripe Payments", max_length=255)),
                ("revenue_account_code", models.CharField(blank=True, default="", max_length=64)),
                ("fee_account_code", models.CharField(blank=True, default="", max_length=64)),
                ("refund_account_code", models.CharField(blank=True, default="", max_length=64)),
                ("revenue_tax_type", models.CharField(blank=True, default="", max_length=64)),
                ("fee_tax_type", models.CharField(blank=True, default="", max_length=64)),
                ("refund_tax_type", models.CharField(blank=True, default="", max_length=64)),
                ("line_amount_types", models.CharField(default="Inclusive", max_length=16)),
                ("event_tracking_category_id", models.CharField(blank=True, default="", max_length=255)),
                ("event_tracking_category_name", models.CharField(default="Event Name", max_length=255)),
                ("project_tracking_category_id", models.CharField(blank=True, default="", max_length=255)),
                ("project_tracking_category_name", models.CharField(default="Project Name", max_length=255)),
                ("standalone_fee_project_option_id", models.CharField(blank=True, default="", max_length=255)),
                ("standalone_fee_project_option_name", models.CharField(blank=True, default="", max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="reconciliation_profile", to="organizations.organization")),
                ("xero_connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reconciliation_profiles", to="integrations.externalserviceconnection")),
            ],
            options={"db_table": "stripe_xero_reconciliation_profile"},
        ),
        migrations.CreateModel(
            name="ReconciliationMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_type", models.CharField(choices=[("luma_event", "Luma event"), ("stripe_product", "Stripe product"), ("stripe_invoice", "Stripe invoice"), ("stripe_metadata", "Stripe metadata"), ("unattributed", "Unattributed Stripe transaction")], max_length=32)),
                ("source_id", models.CharField(max_length=255)),
                ("source_label", models.CharField(blank=True, default="", max_length=500)),
                ("accounting_treatment", models.CharField(blank=True, choices=[("revenue", "Recognise revenue"), ("clearing", "Clear revenue recorded elsewhere")], default="", max_length=16)),
                ("event_tracking_option_id", models.CharField(blank=True, default="", max_length=255)),
                ("event_tracking_option_name", models.CharField(blank=True, default="", max_length=255)),
                ("project_tracking_option_id", models.CharField(blank=True, default="", max_length=255)),
                ("project_tracking_option_name", models.CharField(blank=True, default="", max_length=255)),
                ("account_code", models.CharField(blank=True, default="", max_length=64)),
                ("tax_type", models.CharField(blank=True, default="", max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reconciliation_mappings", to="organizations.organization")),
            ],
            options={"db_table": "stripe_xero_reconciliation_mapping"},
        ),
        migrations.CreateModel(
            name="StripePayoutReconciliation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_account_id", models.CharField(blank=True, default="", max_length=255)),
                ("payout_id", models.CharField(max_length=255)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=12)),
                ("amount_cents", models.BigIntegerField(default=0)),
                ("source_hash", models.CharField(blank=True, default="", max_length=64)),
                ("report_payload", models.JSONField(blank=True, default=dict)),
                ("preview_payload", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("needs_review", "Needs review"), ("ready", "Ready"), ("posting", "Posting"), ("posted", "Posted"), ("failed", "Failed")], db_index=True, default="needs_review", max_length=32)),
                ("approved_by_slack_id", models.CharField(blank=True, default="", max_length=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("xero_bank_transaction_id", models.CharField(blank=True, default="", max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stripe_payout_reconciliations", to="organizations.organization")),
            ],
            options={"db_table": "stripe_payout_reconciliation"},
        ),
        migrations.AddConstraint(
            model_name="reconciliationmapping",
            constraint=models.UniqueConstraint(fields=("organization", "source_type", "source_id"), name="recon_mapping_org_source_uniq"),
        ),
        migrations.AddIndex(
            model_name="reconciliationmapping",
            index=models.Index(fields=["organization", "active"], name="recon_mapping_org_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="stripepayoutreconciliation",
            constraint=models.UniqueConstraint(fields=("organization", "stripe_account_id", "payout_id"), name="recon_payout_org_account_id_uniq"),
        ),
        migrations.AddIndex(
            model_name="stripepayoutreconciliation",
            index=models.Index(fields=["organization", "arrival_date"], name="recon_payout_org_arrival_idx"),
        ),
    ]
