# Generated by Django 4.2.16 on 2026-07-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('integrations', '0025_reconciliation_context_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroStatementLineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_id', models.CharField(max_length=255)),
                ('statement_line_id', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('narration', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=500)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, default='AUD', max_length=12)),
                ('current_contact', models.CharField(blank=True, default='', max_length=255)),
                ('current_account', models.CharField(blank=True, default='', max_length=255)),
                ('current_description', models.TextField(blank=True, default='')),
                ('current_event_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_project_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_tax_type', models.CharField(blank=True, default='', max_length=255)),
                ('ready_in_xero', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_statement_line_snapshots', to='organizations.organization')),
            ],
            options={
                'db_table': 'xero_statement_line_snapshot',
            },
        ),
        migrations.AlterField(
            model_name='externalfinancialrecord',
            name='record_type',
            field=models.CharField(choices=[('bank_transaction', 'Bank Transaction'), ('xero_repeating_invoice', 'Xero Repeating Invoice'), ('xero_invoice', 'Xero Invoice'), ('xero_bill', 'Xero Bill'), ('xero_payment', 'Xero Payment')], db_index=True, default='bank_transaction', max_length=64),
        ),
        migrations.CreateModel(
            name='XeroStatementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=255)),
                ('proposed_action', models.CharField(choices=[('prefill_create', 'Prefill Create'), ('match_existing_bill', 'Match Existing Bill'), ('needs_review', 'Needs Review')], default='needs_review', max_length=32)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_code', models.CharField(blank=True, default='', max_length=64)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_type', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_source_id', models.CharField(blank=True, default='', max_length=255)),
                ('event_tracking_option_name', models.CharField(blank=True, default='', max_length=255)),
                ('project_source_id', models.CharField(blank=True, default='', max_length=255)),
                ('project_tracking_option_name', models.CharField(blank=True, default='', max_length=255)),
                ('matched_xero_bill_id', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True, default='')),
                ('review_note', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('source_hash', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied to Xero form'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='proposed', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_statement_suggestions', to='organizations.organization')),
                ('statement_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='integrations.xerostatementlinesnapshot')),
            ],
            options={
                'db_table': 'xero_statement_suggestion',
                'indexes': [models.Index(fields=['organization', 'status'], name='xero_stmt_suggest_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='xerostatementsuggestion',
            constraint=models.UniqueConstraint(fields=('organization', 'statement_line', 'run_id'), name='xero_stmt_suggest_org_line_run_uniq'),
        ),
        migrations.AddIndex(
            model_name='xerostatementlinesnapshot',
            index=models.Index(fields=['organization', 'active', 'ready_in_xero'], name='xero_stmt_org_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='xerostatementlinesnapshot',
            index=models.Index(fields=['organization', 'transaction_date'], name='xero_stmt_org_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='xerostatementlinesnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'bank_account_id', 'statement_line_id'), name='xero_stmt_org_account_line_uniq'),
        ),
    ]
