# Generated by Django 4.2.16 on 2026-07-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0026_xero_statement_reconciliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xerostatementsuggestion",
            name="proposed_action",
            field=models.CharField(
                choices=[
                    ("create_bank_transaction", "Create Bank Transaction"),
                    ("pay_existing_bill", "Pay Existing Bill"),
                    ("prefill_create", "Prefill Create"),
                    ("match_existing_bill", "Match Existing Bill"),
                    ("needs_review", "Needs Review"),
                ],
                default="needs_review",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="XeroStatementPosting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation", models.CharField(choices=[("bank_transaction", "Bank Transaction"), ("bill_payment", "Bill Payment")], max_length=32)),
                ("status", models.CharField(choices=[("previewed", "Previewed"), ("ready", "Ready"), ("posting", "Posting"), ("match_ready", "Ready to Match"), ("failed", "Failed")], db_index=True, default="previewed", max_length=20)),
                ("source_hash", models.CharField(max_length=64)),
                ("payload_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("preview_payload", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("requested_by_slack_id", models.CharField(blank=True, default="", max_length=100)),
                ("automatic", models.BooleanField(default=False)),
                ("xero_bank_transaction_id", models.CharField(blank=True, default="", max_length=255)),
                ("xero_payment_id", models.CharField(blank=True, default="", max_length=255)),
                ("xero_bill_id", models.CharField(blank=True, default="", max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="xero_statement_postings", to="organizations.organization")),
                ("statement_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="postings", to="integrations.xerostatementlinesnapshot")),
                ("suggestion", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="postings", to="integrations.xerostatementsuggestion")),
            ],
            options={
                "db_table": "xero_statement_posting",
                "indexes": [models.Index(fields=["organization", "status"], name="xero_stmt_post_status_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="xerostatementposting",
            constraint=models.UniqueConstraint(fields=("organization", "statement_line", "source_hash"), name="xero_stmt_post_org_line_hash_uniq"),
        ),
    ]
