# Generated by Django 4.2.16 on 2026-07-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_xero_statement_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearIssueCreationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('linear_issue_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'linear_issue_creation_receipt',
                'ordering': ['-created_at'],
            },
        ),
    ]
