# Generated by Django 4.2.16 on 2026-07-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('integrations', '0028_xero_statement_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanitixEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=500)),
                ('event_url', models.URLField(blank=True, default='', max_length=1000)),
                ('currency', models.CharField(blank=True, default='', max_length=12)),
                ('timezone_name', models.CharField(blank=True, default='', max_length=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('total_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'humanitix_event',
                'ordering': ['-start_at', 'event_name', 'external_event_id'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationprofile',
            name='humanitix_contact_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationprofile',
            name='humanitix_contact_name',
            field=models.CharField(default='Humanitix', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalfinancialrecord',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('humanitix', 'Humanitix'), ('xero', 'Xero'), ('bank_feed', 'Bank Feed'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('google_analytics', 'Google Analytics'), ('luma', 'Luma')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='externalserviceconnection',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('humanitix', 'Humanitix'), ('xero', 'Xero'), ('bank_feed', 'Bank Feed'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('google_analytics', 'Google Analytics'), ('luma', 'Luma')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('humanitix', 'Humanitix'), ('xero', 'Xero'), ('bank_feed', 'Bank Feed'), ('notion', 'Notion'), ('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('google_analytics', 'Google Analytics'), ('luma', 'Luma')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='reconciliationmapping',
            name='source_type',
            field=models.CharField(choices=[('luma_event', 'Luma event'), ('humanitix_event', 'Humanitix event'), ('humanitix_ticket_type', 'Humanitix ticket type'), ('humanitix_payout', 'Humanitix payout'), ('stripe_product', 'Stripe product'), ('stripe_invoice', 'Stripe invoice'), ('stripe_metadata', 'Stripe metadata'), ('unattributed', 'Unattributed Stripe transaction')], max_length=32),
        ),
        migrations.CreateModel(
            name='HumanitixPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_reference', models.CharField(max_length=255)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=12)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('humanitix_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('box_office_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('absorbed_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('preview_payload', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('ready', 'Ready'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed')], db_index=True, default='needs_review', max_length=32)),
                ('approved_by_slack_id', models.CharField(blank=True, default='', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('xero_bank_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humanitix_payouts', to='integrations.externalserviceconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humanitix_payouts', to='organizations.organization')),
            ],
            options={
                'db_table': 'humanitix_payout',
                'ordering': ['-payout_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HumanitixEventFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('paid_order_count', models.PositiveIntegerField(default=0)),
                ('free_order_count', models.PositiveIntegerField(default=0)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('donations', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('humanitix_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('absorbed_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gateway_breakdown', models.JSONField(blank=True, default=dict)),
                ('ticket_type_breakdown', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='integrations.humanitixevent')),
            ],
            options={
                'db_table': 'humanitix_event_financial_summary',
            },
        ),
        migrations.AddField(
            model_name='humanitixevent',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humanitix_events', to='integrations.externalserviceconnection'),
        ),
        migrations.AddField(
            model_name='humanitixevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humanitix_events', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='HumanitixPayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_line_key', models.CharField(max_length=255)),
                ('external_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('event_name', models.CharField(blank=True, default='', max_length=500)),
                ('component', models.CharField(choices=[('ticket_sales', 'Ticket sales'), ('donations', 'Donations'), ('add_ons', 'Add-ons'), ('refunds', 'Refunds'), ('absorbed_fees', 'Absorbed fees'), ('adjustments', 'Adjustments'), ('net_payout', 'Net payout')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_lines', to='integrations.humanitixevent')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='integrations.humanitixpayout')),
            ],
            options={
                'db_table': 'humanitix_payout_line',
                'ordering': ['payout_id', 'source_line_key'],
                'indexes': [models.Index(fields=['event', 'component'], name='humanitix_line_event_comp_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='humanitixpayoutline',
            constraint=models.UniqueConstraint(fields=('payout', 'source_line_key'), name='humanitix_payout_line_source_uniq'),
        ),
        migrations.AddIndex(
            model_name='humanitixpayout',
            index=models.Index(fields=['organization', 'payout_date'], name='humanitix_payout_org_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='humanitixpayout',
            constraint=models.UniqueConstraint(fields=('organization', 'payout_reference'), name='humanitix_payout_org_reference_uniq'),
        ),
        migrations.AddIndex(
            model_name='humanitixevent',
            index=models.Index(fields=['organization', 'start_at'], name='humanitix_event_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='humanitixevent',
            index=models.Index(fields=['connection', 'last_synced_at'], name='humanitix_event_conn_sync_idx'),
        ),
        migrations.AddConstraint(
            model_name='humanitixevent',
            constraint=models.UniqueConstraint(fields=('organization', 'external_event_id'), name='humanitix_event_org_external_uniq'),
        ),
    ]
