# Generated by Django 4.2.16 on 2026-08-02 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0037_reconciliation_profitability_policy"),
        ("integrations", "0038_account_backed_bridge_identity"),
    ]

    operations = []
