# Generated by Django 4.2.16 on 2026-08-14

from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """Add a field while tolerating production schemas that already contain it."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)

        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor,
                    model._meta.db_table,
                )
            }

        if field.column in columns:
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0039_merge_20260802_1530"),
    ]

    operations = [
        AddFieldIfMissing(
            model_name="reconciliationprofile",
            name="require_statement_tracking",
            field=models.BooleanField(default=False),
        ),
        AddFieldIfMissing(
            model_name="reconciliationprofile",
            name="default_project_tracking_option_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        AddFieldIfMissing(
            model_name="reconciliationprofile",
            name="default_project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        AddFieldIfMissing(
            model_name="reconciliationsuggestion",
            name="allocation_mode",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("project", "Project"),
                    ("mlai_core", "MLAI core"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=16,
            ),
        ),
        AddFieldIfMissing(
            model_name="reconciliationsuggestion",
            name="project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        AddFieldIfMissing(
            model_name="reconciliationrule",
            name="allocation_mode",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("project", "Project"),
                    ("mlai_core", "MLAI core"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=16,
            ),
        ),
        AddFieldIfMissing(
            model_name="reconciliationrule",
            name="project_source_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        AddFieldIfMissing(
            model_name="reconciliationrule",
            name="project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        AddFieldIfMissing(
            model_name="xerostatementsuggestion",
            name="allocation_mode",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("project", "Project"),
                    ("mlai_core", "MLAI core"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=16,
            ),
        ),
        AddFieldIfMissing(
            model_name="xerostatementsuggestion",
            name="project_source_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        AddFieldIfMissing(
            model_name="xerostatementsuggestion",
            name="project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
