# Generated by Django 4.2.16 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0039_merge_20260802_1530"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationprofile",
            name="require_statement_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reconciliationprofile",
            name="default_project_tracking_option_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reconciliationprofile",
            name="default_project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reconciliationsuggestion",
            name="allocation_mode",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("project", "Project"),
                    ("mlai_core", "MLAI core"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationsuggestion",
            name="project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reconciliationrule",
            name="allocation_mode",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("project", "Project"),
                    ("mlai_core", "MLAI core"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationrule",
            name="project_source_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="reconciliationrule",
            name="project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="xerostatementsuggestion",
            name="allocation_mode",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("project", "Project"),
                    ("mlai_core", "MLAI core"),
                    ("unassigned", "Unassigned"),
                ],
                default="unassigned",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="xerostatementsuggestion",
            name="project_source_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="xerostatementsuggestion",
            name="project_tracking_option_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
