# Generated by Django 4.2.16 on 2026-09-14 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import integrations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0046_communitybridgedeletionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeApiBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100)),
                ('workspace_id', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('next_admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bridge_api_budget',
            },
        ),
        migrations.CreateModel(
            name='BridgeSyncInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100)),
                ('workspace_id', models.CharField(max_length=100)),
                ('source_event_id', models.CharField(max_length=255)),
                ('encrypted_payload', integrations.fields.EncryptedTextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bridge_sync_inbox',
            },
        ),
        migrations.CreateModel(
            name='BridgeSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('head', 'head'), ('archive', 'archive'), ('thread', 'thread'), ('authority', 'authority')], max_length=20)),
                ('source_object_key', models.CharField(blank=True, default='', max_length=100)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority_lane', models.CharField(default='background', max_length=20)),
                ('last_served_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('backoff_seconds', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bridge_sync_job',
            },
        ),
        migrations.CreateModel(
            name='BridgeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=100)),
                ('source_channel_id', models.CharField(max_length=100)),
                ('authority_generation', models.PositiveBigIntegerField(default=1)),
                ('archive_cursor', models.JSONField(blank=True, default=dict)),
                ('head_cursor', models.JSONField(blank=True, default=dict)),
                ('verified_ranges', models.JSONField(blank=True, default=dict)),
                ('latest_source_activity', models.CharField(blank=True, default='', max_length=32)),
                ('last_successful_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('last_served_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bridge_sync_state',
            },
        ),
        migrations.CreateModel(
            name='BridgeWorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=100)),
                ('lane', models.CharField(max_length=40)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('progressed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_count', models.PositiveBigIntegerField(default=0)),
                ('failed_count', models.PositiveBigIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'bridge_worker_heartbeat',
            },
        ),
        migrations.AddField(
            model_name='communitybridgedelivery',
            name='canonical_envelope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='communitybridgedelivery',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitybridgedelivery',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitybridgedelivery',
            name='source_revision',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='bridgeworkerheartbeat',
            constraint=models.UniqueConstraint(fields=('worker_id', 'lane'), name='bridge_heartbeat_worker_unique'),
        ),
        migrations.AddField(
            model_name='bridgesyncstate',
            name='private_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='integrations.slackdmmirrorconversation'),
        ),
        migrations.AddField(
            model_name='bridgesyncstate',
            name='public_channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='integrations.communitybridgechannel'),
        ),
        migrations.AddField(
            model_name='bridgesyncjob',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='integrations.bridgesyncstate'),
        ),
        migrations.AddIndex(
            model_name='bridgesyncinbox',
            index=models.Index(fields=['status', 'available_at'], name='bridge_inbox_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='bridgesyncinbox',
            constraint=models.UniqueConstraint(fields=('app_id', 'workspace_id', 'source_event_id'), name='bridge_inbox_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='bridgeapibudget',
            constraint=models.UniqueConstraint(fields=('app_id', 'workspace_id', 'method'), name='bridge_api_budget_unique'),
        ),
        migrations.AddIndex(
            model_name='bridgesyncstate',
            index=models.Index(fields=['workspace_id', 'last_served_at'], name='bridge_sync_fair_idx'),
        ),
        migrations.AddConstraint(
            model_name='bridgesyncstate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('private_conversation__isnull', True), ('public_channel__isnull', False)), models.Q(('private_conversation__isnull', False), ('public_channel__isnull', True)), _connector='OR'), name='bridge_sync_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='bridgesyncjob',
            index=models.Index(fields=['kind', 'due_at'], name='bridge_sync_job_due_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgesyncjob',
            index=models.Index(fields=['lease_expires_at'], name='bridge_sync_job_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='bridgesyncjob',
            constraint=models.UniqueConstraint(fields=('state', 'kind', 'source_object_key'), name='bridge_sync_job_unique'),
        ),
    ]
