from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content_factory", "0032_writtenarticle_analytics_identity"),
        ("integrations", "0019_luma_provider_choice"),
        ("organizations", "0002_organization_company_linkedin_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(db_index=True, default="umami", max_length=32)),
                ("external_website_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("provision_status", models.CharField(choices=[("pending", "Pending"), ("provisioned", "Provisioned"), ("error", "Error"), ("disabled", "Disabled")], db_index=True, default="pending", max_length=24)),
                ("team_id", models.CharField(blank=True, default="", max_length=64)),
                ("tracker_script_url", models.CharField(blank=True, default="", max_length=2048)),
                ("collector_url", models.CharField(blank=True, default="", help_text="Public Umami host URL supplied to the tracker as data-host-url", max_length=2048)),
                ("last_provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_site", to="organizations.organization")),
            ],
            options={"db_table": "content_analytics_site"},
        ),
        migrations.CreateModel(
            name="SearchConsoleProperty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_url", models.CharField(blank=True, db_index=True, default="", max_length=2048)),
                ("access_method", models.CharField(choices=[("service_account", "Service account"), ("oauth", "OAuth")], default="service_account", max_length=24)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("verified", "Verified"), ("error", "Error"), ("disabled", "Disabled")], db_index=True, default="pending", max_length=20)),
                ("permission_level", models.CharField(blank=True, default="", max_length=64)),
                ("service_account_email", models.EmailField(blank=True, default="", max_length=254)),
                ("sync_enabled", models.BooleanField(db_index=True, default=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("google_connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="search_console_properties", to="integrations.googleconnection")),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="search_console_property", to="organizations.organization")),
            ],
            options={"db_table": "content_analytics_gsc_property"},
        ),
        migrations.CreateModel(
            name="ArticleBehaviorDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("pageviews", models.PositiveBigIntegerField(default=0)),
                ("visitors", models.PositiveBigIntegerField(default=0)),
                ("visits", models.PositiveBigIntegerField(default=0)),
                ("bounces", models.PositiveBigIntegerField(default=0)),
                ("umami_total_time", models.PositiveBigIntegerField(default=0)),
                ("engaged_30_count", models.PositiveBigIntegerField(default=0, help_text="Unique visits that reached 30 seconds")),
                ("scroll_50_count", models.PositiveBigIntegerField(default=0, help_text="Unique visits that reached 50% scroll")),
                ("scroll_90_count", models.PositiveBigIntegerField(default=0, help_text="Unique visits that reached 90% scroll")),
                ("cta_impression_count", models.PositiveBigIntegerField(default=0, help_text="Unique visits where a CTA became visible")),
                ("cta_click_count", models.PositiveBigIntegerField(default=0, help_text="Unique visits with a CTA click")),
                ("outbound_click_count", models.PositiveBigIntegerField(default=0, help_text="Unique visits with a tracked outbound click")),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="behavior_daily", to="content_factory.writtenarticle")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="article_behavior_daily", to="organizations.organization")),
            ],
            options={"db_table": "content_analytics_behavior_daily", "ordering": ["date", "article_id"]},
        ),
        migrations.CreateModel(
            name="ArticleTrafficSourceDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("source_category", models.CharField(choices=[("search", "Search"), ("ai", "AI assistant"), ("social", "Social"), ("email", "Email"), ("paid", "Paid"), ("referral", "Referral"), ("direct", "Direct or unknown"), ("other", "Other")], db_index=True, max_length=24)),
                ("source_name", models.CharField(blank=True, default="", max_length=255)),
                ("pageviews", models.PositiveBigIntegerField(default=0)),
                ("visitors", models.PositiveBigIntegerField(default=0)),
                ("visits", models.PositiveBigIntegerField(default=0)),
                ("cta_impression_count", models.PositiveBigIntegerField(default=0)),
                ("cta_click_count", models.PositiveBigIntegerField(default=0)),
                ("conversion_attribution_available", models.BooleanField(default=False, help_text="Whether CTA visits were attributed to this source rather than left unassigned")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="traffic_source_daily", to="content_factory.writtenarticle")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="article_traffic_source_daily", to="organizations.organization")),
            ],
            options={"db_table": "content_analytics_traffic_daily"},
        ),
        migrations.CreateModel(
            name="ArticleSearchDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("engine", models.CharField(db_index=True, default="google", max_length=32)),
                ("surface", models.CharField(db_index=True, default="web", max_length=64)),
                ("country", models.CharField(blank=True, default="", max_length=8)),
                ("device", models.CharField(blank=True, default="", max_length=32)),
                ("clicks", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("impressions", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("ctr", models.DecimalField(decimal_places=10, default=0, max_digits=12)),
                ("position", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="search_daily", to="content_factory.writtenarticle")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="article_search_daily", to="organizations.organization")),
            ],
            options={"db_table": "content_analytics_search_daily"},
        ),
        migrations.CreateModel(
            name="ArticleSearchQueryDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("engine", models.CharField(db_index=True, default="google", max_length=32)),
                ("surface", models.CharField(default="web", max_length=64)),
                ("query", models.CharField(max_length=1024)),
                ("clicks", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("impressions", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("ctr", models.DecimalField(decimal_places=10, default=0, max_digits=12)),
                ("position", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="search_query_daily", to="content_factory.writtenarticle")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="article_search_query_daily", to="organizations.organization")),
            ],
            options={"db_table": "content_analytics_search_query_daily"},
        ),
        migrations.CreateModel(
            name="AnalyticsSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("umami", "Umami"), ("search_console", "Google Search Console")], max_length=32)),
                ("status", models.CharField(choices=[("idle", "Idle"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="idle", max_length=20)),
                ("cursor", models.JSONField(blank=True, default=dict)),
                ("backfill_started_on", models.DateField(blank=True, null=True)),
                ("synced_through", models.DateField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("last_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analytics_sync_states", to="organizations.organization")),
            ],
            options={"db_table": "content_analytics_sync_state"},
        ),
        migrations.AddConstraint(model_name="analyticssite", constraint=models.UniqueConstraint(condition=~models.Q(external_website_id=""), fields=("provider", "external_website_id"), name="analytics_provider_site_uniq")),
        migrations.AddIndex(model_name="analyticssite", index=models.Index(fields=["enabled", "provision_status"], name="analytics_site_due_idx")),
        migrations.AddIndex(model_name="searchconsoleproperty", index=models.Index(fields=["sync_enabled", "status"], name="gsc_property_due_idx")),
        migrations.AddConstraint(model_name="articlebehaviordaily", constraint=models.UniqueConstraint(fields=("article", "date"), name="article_behavior_day_uniq")),
        migrations.AddIndex(model_name="articlebehaviordaily", index=models.Index(fields=["organization", "date"], name="behavior_org_day_idx")),
        migrations.AddConstraint(model_name="articletrafficsourcedaily", constraint=models.UniqueConstraint(fields=("article", "date", "source_category", "source_name"), name="article_traffic_day_source_uniq")),
        migrations.AddIndex(model_name="articletrafficsourcedaily", index=models.Index(fields=["organization", "date", "source_category"], name="traffic_org_day_src_idx")),
        migrations.AddConstraint(model_name="articlesearchdaily", constraint=models.UniqueConstraint(fields=("article", "date", "engine", "surface", "country", "device"), name="article_search_day_grain_uniq")),
        migrations.AddIndex(model_name="articlesearchdaily", index=models.Index(fields=["organization", "date", "engine"], name="search_org_day_engine_idx")),
        migrations.AddConstraint(model_name="articlesearchquerydaily", constraint=models.UniqueConstraint(fields=("article", "date", "engine", "surface", "query"), name="article_search_query_day_uniq")),
        migrations.AddIndex(model_name="articlesearchquerydaily", index=models.Index(fields=["organization", "date", "engine"], name="query_org_day_engine_idx")),
        migrations.AddConstraint(model_name="analyticssyncstate", constraint=models.UniqueConstraint(fields=("organization", "source"), name="analytics_org_source_uniq")),
        migrations.AddIndex(model_name="analyticssyncstate", index=models.Index(fields=["source", "status", "updated_at"], name="analytics_sync_due_idx")),
    ]
