# Generated by Django 4.2.16 on 2026-07-21 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('content_analytics', '0002_article_analytics_location_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('prior_window_start', models.DateField()),
                ('prior_window_end', models.DateField()),
                ('data_through_date', models.DateField(blank=True, null=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_performance_reports', to='organizations.organization')),
            ],
            options={
                'db_table': 'content_analytics_performance_report',
                'ordering': ['-report_date', '-id'],
                'indexes': [models.Index(fields=['organization', '-report_date'], name='perf_report_org_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='articleperformancereport',
            constraint=models.UniqueConstraint(fields=('organization', 'report_date'), name='perf_report_org_day_uniq'),
        ),
    ]
