# Generated by Django 5.1.5 on 2025-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_prediction_diastolic_bp_prediction_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
    ]
