# Generated by Django 4.2.16 on 2026-02-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_team_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.JSONField(blank=True, help_text='Scoring breakdown: confusion matrix, per-class stats, missed crises, first 100 row details', null=True),
        ),
    ]
