# Generated by Django 4.2.16 on 2026-07-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_add_feedback_to_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCaseWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sim Case Winner',
                'verbose_name_plural': 'Sim Case Winners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimDiagnosisGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.PositiveIntegerField(db_index=True, help_text='Case ID from roo cases.yaml')),
                ('client_id', models.CharField(help_text='Anonymous browser UUID', max_length=64)),
                ('guess_text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField()),
                ('outcome', models.CharField(choices=[('pending_claim', 'Correct — awaiting email'), ('incorrect', 'Incorrect'), ('ticket', 'Free ticket (winner)'), ('discount', '30% discount')], max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Set at claim time', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sim Diagnosis Guess',
                'verbose_name_plural': 'Sim Diagnosis Guesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='simdiagnosisguess',
            constraint=models.UniqueConstraint(fields=('case_id', 'client_id'), name='uniq_sim_guess_case_client'),
        ),
        migrations.AddField(
            model_name='simcasewinner',
            name='guess',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='win', to='hospital.simdiagnosisguess'),
        ),
    ]
