# Generated by Django 4.2.16 on 2026-07-12 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


def backfill_participants_and_prizes(apps, schema_editor):
    SimParticipant = apps.get_model('hospital', 'SimParticipant')
    SimDiagnosisGuess = apps.get_model('hospital', 'SimDiagnosisGuess')
    SimCaseWinner = apps.get_model('hospital', 'SimCaseWinner')

    for guess in SimDiagnosisGuess.objects.all().iterator():
        try:
            participant_id = uuid.UUID(str(guess.client_id))
        except (ValueError, TypeError, AttributeError):
            participant_id = None
        if participant_id is not None:
            participant, _ = SimParticipant.objects.get_or_create(id=participant_id)
            guess.participant = participant

        if guess.outcome == 'ticket':
            guess.prize_kind = 'free_ticket'
        elif guess.outcome == 'discount':
            guess.prize_kind = 'discount_30'
        guess.save(update_fields=['participant', 'prize_kind'])

    case_ids = (
        SimDiagnosisGuess.objects
        .filter(is_correct=True)
        .values_list('case_id', flat=True)
        .distinct()
    )
    for case_id in case_ids:
        winner = SimCaseWinner.objects.filter(case_id=case_id).first()
        if winner is None:
            first_correct = (
                SimDiagnosisGuess.objects
                .filter(case_id=case_id, is_correct=True)
                .order_by('created_at', 'pk')
                .first()
            )
            if first_correct is not None:
                winner = SimCaseWinner.objects.create(case_id=case_id, guess=first_correct)

        if winner is not None:
            SimDiagnosisGuess.objects.filter(pk=winner.guess_id).update(
                prize_kind='free_ticket',
            )
            SimDiagnosisGuess.objects.filter(
                case_id=case_id,
                is_correct=True,
            ).exclude(pk=winner.guess_id).update(prize_kind='discount_30')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_simcasewinner_simdiagnosisguess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.PositiveIntegerField(db_index=True)),
                ('role', models.CharField(choices=[('patient', 'Sash'), ('nurse', 'Dr Snow')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_turn_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_turn_at'],
            },
        ),
        migrations.CreateModel(
            name='SimConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('player_text', models.TextField()),
                ('npc_text', models.TextField(blank=True, default='')),
                ('response_source', models.CharField(choices=[('pending', 'Pending'), ('llm', 'LLM'), ('deterministic', 'Deterministic'), ('error', 'Error')], default='pending', max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sim Participant',
                'verbose_name_plural': 'Sim Participants',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='simdiagnosisguess',
            name='prize_kind',
            field=models.CharField(choices=[('none', 'No prize'), ('free_ticket', 'Free ticket'), ('discount_30', '30% discount')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='simdiagnosisguess',
            name='redemption_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simconversationturn',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='hospital.simconversation'),
        ),
        migrations.AddField(
            model_name='simconversation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='hospital.simparticipant'),
        ),
        migrations.AddField(
            model_name='simdiagnosisguess',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guesses', to='hospital.simparticipant'),
        ),
        migrations.RunPython(backfill_participants_and_prizes, noop_reverse),
        migrations.AddConstraint(
            model_name='simdiagnosisguess',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('case_id'), condition=models.Q(('email', ''), _negated=True), name='uniq_sim_claim_email_case_ci'),
        ),
        migrations.AddConstraint(
            model_name='simconversation',
            constraint=models.UniqueConstraint(fields=('participant', 'case_id', 'role'), name='uniq_sim_conversation_participant_case_role'),
        ),
    ]
