# Generated by Django 4.2.16 on 2026-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_sim_observability_and_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconversationturn',
            name='suggested_action',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simconversationturn',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='simconversation',
            name='role',
            field=models.CharField(choices=[('patient', 'Sash'), ('nurse', 'Dr Snow'), ('clerk', 'Nurse Paws')], max_length=16),
        ),
    ]
