# Generated by Django 4.2.16 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_sim_ai_npc_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='simdiagnosisguess',
            name='case_title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Human-readable simulated-patient challenge title from Roo',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name='simdiagnosisguess',
            name='email',
            field=models.EmailField(
                blank=True,
                default='',
                help_text='Prize registration email; stored only, no email is sent',
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name='simdiagnosisguess',
            name='redemption_delivered_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Legacy field; unused by the link-only prize flow',
                null=True,
            ),
        ),
    ]
