# Generated by Django 4.2.16 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_sim_prize_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='simconversationturn',
            name='public_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simconversationturn',
            name='response_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='simconversationturn',
            index=models.Index(fields=['created_at'], name='sim_turn_created_idx'),
        ),
    ]
