# Generated by Django 4.2.16 on 2026-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ref', models.CharField(max_length=64, unique=True)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('complete', 'Complete')], default='lead', max_length=16)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('legal_work', models.CharField(blank=True, max_length=64)),
                ('visa', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=500)),
                ('github', models.CharField(blank=True, max_length=500)),
                ('portfolio', models.CharField(blank=True, max_length=500)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('skills_other', models.JSONField(blank=True, default=list)),
                ('ai_tools', models.JSONField(blank=True, default=list)),
                ('ai_tools_other', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('interests_other', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(blank=True, max_length=64)),
                ('availability_other', models.CharField(blank=True, max_length=255)),
                ('start_date', models.CharField(blank=True, max_length=64)),
                ('start_date_other', models.CharField(blank=True, max_length=255)),
                ('rate', models.CharField(blank=True, max_length=255)),
                ('projects', models.TextField(blank=True)),
                ('anything_else', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
