# Generated by Django 5.1.5 on 2025-02-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_team_submission_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_team',
            field=models.BooleanField(default=False),
        ),
    ]
