# Generated by Django 5.1.5 on 2025-12-08 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('portfolio', models.CharField(choices=[('events', 'Events'), ('marketing', 'Marketing'), ('tech', 'Tech'), ('ops', 'Ops'), ('sales', 'Sales')], default='events', max_length=50)),
                ('points', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('pending_approval', 'Pending Approval'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_by_user_id', models.CharField(help_text='Slack ID of minter', max_length=50)),
                ('assigned_to_user_id', models.CharField(blank=True, help_text='Slack ID of volunteer', max_length=50, null=True)),
                ('closed_by_user_id', models.CharField(blank=True, help_text='Slack ID of approver', max_length=50, null=True)),
                ('slack_channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('slack_thread_ts', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(help_text='Slack User ID (e.g. U123ABC)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('committee', 'Committee'), ('portfolio_lead', 'Portfolio Lead'), ('admin', 'Admin')], default='committee', max_length=50)),
                ('portfolio', models.CharField(blank=True, choices=[('events', 'Events'), ('marketing', 'Marketing'), ('tech', 'Tech'), ('ops', 'Ops'), ('sales', 'Sales')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(help_text='User receiving points', max_length=50)),
                ('points_delta', models.IntegerField(help_text='Points awarded (can be negative for corrections)')),
                ('reason', models.TextField(blank=True)),
                ('created_by_user_id', models.CharField(help_text='Slack ID of who awarded points', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='roo.task')),
            ],
        ),
    ]
