# Generated by Django 5.1.5 on 2025-12-16 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_slack_id_alter_globalsettings_is_obscured'),
        ('roo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingDayCapacity',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('notes', models.TextField(blank=True, help_text='Reason for capacity change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coworking Day Capacity',
                'verbose_name_plural': 'Coworking Day Capacities',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='points_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(default=0, help_text='Current spendable balance')),
                ('lifetime_earned', models.IntegerField(default=0, help_text='Total points ever earned')),
                ('lifetime_spent', models.IntegerField(default=0, help_text='Total points ever spent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Points Account',
                'verbose_name_plural': 'Points Accounts',
            },
        ),
        migrations.CreateModel(
            name='RewardsCatalog',
            fields=[
                ('code', models.CharField(help_text='Unique reward code e.g. HOTDESK_DAY', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost_points', models.IntegerField()),
                ('fulfillment', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_per_user', models.IntegerField(blank=True, help_text='Max redemptions per user (null=unlimited)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards Catalog',
                'ordering': ['cost_points'],
            },
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.AddField(
            model_name='ledger',
            name='created_by_slack_id',
            field=models.CharField(blank=True, help_text='Who initiated/approved', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='delta',
            field=models.IntegerField(blank=True, help_text='Points change (positive=earn, negative=spend)', null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ledger',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Prevents duplicate transactions', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='kind',
            field=models.CharField(blank=True, choices=[('EARN', 'Earn'), ('SPEND', 'Spend'), ('ADJUST', 'Adjust'), ('REFUND', 'Refund')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='reference_id',
            field=models.CharField(blank=True, help_text='ID of related object', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='reference_type',
            field=models.CharField(blank=True, help_text='e.g. TASK_SUBMISSION, BOOKING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='source',
            field=models.CharField(choices=[('TASK', 'Task'), ('COWORKING', 'Coworking'), ('EVENT', 'Event'), ('MERCH', 'Merch'), ('TOOLS', 'Tools'), ('DONATION', 'Donation'), ('MANUAL', 'Manual'), ('LEGACY', 'Legacy')], default='LEGACY', max_length=20),
        ),
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='User who claimed this task (linked via FK)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='created_by_user_id',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use created_by_slack_id instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='points_delta',
            field=models.IntegerField(blank=True, help_text='DEPRECATED: Use delta instead', null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='reason',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use description instead', null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='slack_user_id',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use user FK instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_ledger_entries', to='roo.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('pending_approval', 'Pending Approval'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='CoworkingBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('points_cost', models.IntegerField()),
                ('slack_channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coworking_booking', to='roo.ledger')),
                ('refund_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coworking_refund', to='roo.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworking_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coworking Booking',
                'verbose_name_plural': 'Coworking Bookings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PointsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(help_text='Slack User ID (e.g. U123ABC)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('committee', 'Committee'), ('portfolio_lead', 'Portfolio Lead'), ('admin', 'Admin')], default='committee', max_length=50)),
                ('portfolio', models.CharField(blank=True, choices=[('events', 'Events'), ('marketing', 'Marketing'), ('tech', 'Tech'), ('ops', 'Ops'), ('sales', 'Sales')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by_slack_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Admin',
                'verbose_name_plural': 'Points Admins',
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_slack_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes or admin fulfillment notes', null=True)),
                ('slack_channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('slack_thread_ts', models.CharField(blank=True, max_length=50, null=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_redemption', to='roo.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='roo.rewardscatalog')),
            ],
            options={
                'verbose_name': 'Reward Redemption',
                'verbose_name_plural': 'Reward Redemptions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_text', models.TextField(help_text='Description of work completed')),
                ('submission_url', models.URLField(blank=True, help_text='Link to proof of work', null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('approved_by_slack_id', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_submission', to='roo.ledger')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='roo.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Submission',
                'verbose_name_plural': 'Task Submissions',
            },
        ),
        migrations.DeleteModel(
            name='Minter',
        ),
        migrations.AddConstraint(
            model_name='coworkingbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('user', 'date'), name='unique_active_booking_per_user_date'),
        ),
    ]
