# Generated by Django 5.1.5 on 2025-12-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0004_seed_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.SlugField(help_text="Unique identifier for lookup e.g. 'newsletter'", max_length=100, unique=True)),
                ('points', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates (Rate Card)',
                'ordering': ['name'],
            },
        ),
    ]
