# Generated by Django 5.1.5 on 2025-12-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0005_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardscatalog',
            name='stock_remaining',
            field=models.IntegerField(blank=True, help_text='Total stock available. Null = infinite', null=True),
        ),
    ]
