# Generated by Django 5.1.5 on 2025-12-18 01:56

from django.db import migrations


def populate_rate_card(apps, schema_editor):
    TaskTemplate = apps.get_model('roo', 'TaskTemplate')
    items = [
        # Community Actions
        {'alias': 'intro', 'name': 'Introduce yourself in #_start-here', 'points': 2, 'description': 'Community Action (Low friction)'},
        {'alias': 'founder_support', 'name': 'Support key founder posts', 'points': 1, 'description': 'Community Action (Low friction)'},
        {'alias': 'monthly_update', 'name': 'Monthly startup update', 'points': 10, 'description': 'Community Action (Low friction)'},
        # Volunteering
        {'alias': 'event_help', 'name': 'Door / registration / setup', 'points': 12, 'description': 'Volunteering (Standard)'},
        {'alias': 'workshop_help', 'name': 'Co-facilitating workshop', 'points': 24, 'description': 'Volunteering (Standard)'},
        {'alias': 'talk', 'name': 'Giving a talk', 'points': 24, 'description': 'Volunteering (Standard)'},
        {'alias': 'docs', 'name': 'Writing docs/tutorials', 'points': 36, 'description': 'Volunteering (Standard)'},
    ]
    for item in items:
        TaskTemplate.objects.update_or_create(alias=item['alias'], defaults=item)


def populate_rewards(apps, schema_editor):
    RewardsCatalog = apps.get_model('roo', 'RewardsCatalog')
    items = [
        # Coworking
        {'code': 'COWORKING_DAY', 'name': '1 Day Hot-desk', 'cost_points': 4, 'fulfillment': 'auto', 'stock_remaining': None, 'description': 'Coworking'},
        # Office Hours & Mentoring
        {'code': 'OFFICE_HOURS_30', 'name': '30 min Office Hours', 'cost_points': 12, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Office Hours & Mentoring'},
        {'code': 'MENTORING_90', 'name': '90 min Deep-dive Mentoring', 'cost_points': 24, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Office Hours & Mentoring'},
        # Events
        {'code': 'EVENT_TICKET', 'name': 'Free Community Event Ticket', 'cost_points': 12, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Events'},
        {'code': 'WORKSHOP_50', 'name': '50% Off Workshop Ticket', 'cost_points': 30, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Events'},
        {'code': 'WORKSHOP_FREE', 'name': 'Free Workshop Ticket', 'cost_points': 48, 'fulfillment': 'manual', 'stock_remaining': 5, 'description': 'Events (Limited Stock)'},
        # Merch
        {'code': 'STICKER', 'name': 'Sticker', 'cost_points': 1, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Merch'},
        {'code': 'SUNGLASSES', 'name': 'MLAI Sunglasses', 'cost_points': 5, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Merch'},
        {'code': 'MUG', 'name': 'MLAI Mug', 'cost_points': 7, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Merch'},
        {'code': 'TSHIRT', 'name': 'MLAI T-shirt', 'cost_points': 12, 'fulfillment': 'manual', 'stock_remaining': None, 'description': 'Merch'},
    ]
    for item in items:
        RewardsCatalog.objects.update_or_create(code=item['code'], defaults=item)


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0006_rewardscatalog_stock_remaining'),
    ]

    operations = [
        migrations.RunPython(populate_rate_card, migrations.RunPython.noop),
        migrations.RunPython(populate_rewards, migrations.RunPython.noop),
    ]
