# Generated by Django 5.1.5 on 2025-12-18 04:08

from django.db import migrations


def populate_rate_card(apps, schema_editor):
    TaskTemplate = apps.get_model('roo', 'TaskTemplate')
    items = [
        # A) Governance & Committee Ops
        {'alias': 'gov_attend_committee', 'name': 'Attend committee meeting', 'points': 6, 'description': 'Governance & Committee Ops (60 min)'},
        {'alias': 'gov_chair_committee', 'name': 'Chair/host committee meeting', 'points': 12, 'description': 'Governance & Committee Ops (prep + run + follow-ups ~2 hrs)'},
        {'alias': 'gov_prep_agenda', 'name': 'Prepare meeting agenda', 'points': 3, 'description': 'Governance & Committee Ops (30 min)'},
        {'alias': 'gov_minutes', 'name': 'Minutes taker', 'points': 9, 'description': 'Governance & Committee Ops (meeting + clean-up notes ~90 min)'},
        {'alias': 'gov_action_items', 'name': 'Publish action items to Notion + assign owners', 'points': 3, 'description': 'Governance & Committee Ops (30 min)'},
        {'alias': 'gov_planning_attend', 'name': 'Quarterly planning session attendee', 'points': 12, 'description': 'Governance & Committee Ops (2 hrs)'},
        {'alias': 'gov_planning_lead', 'name': 'Quarterly planning session facilitator', 'points': 24, 'description': 'Governance & Committee Ops (prep + run ~4 hrs)'},
        {'alias': 'gov_update_roster', 'name': 'Update committee roster / roles page', 'points': 3, 'description': 'Governance & Committee Ops (30 min)'},
        {'alias': 'gov_update_okr', 'name': 'Update roadmap / OKRs', 'points': 6, 'description': 'Governance & Committee Ops (60 min)'},
        {'alias': 'gov_draft_policy', 'name': 'Draft or update a policy doc', 'points': 12, 'description': 'Governance & Committee Ops (~2 hrs)'},

        # B) Community Management
        {'alias': 'community_welcome_shift', 'name': 'Welcome / onboarding shift', 'points': 6, 'description': 'Community Management (60 min block)'},
        {'alias': 'community_intro_call', 'name': 'Run a "new members intro" call', 'points': 9, 'description': 'Community Management (prep + 45 min call ~90 min)'},
        {'alias': 'community_mod_slack', 'name': 'Moderate Slack channels for a week', 'points': 12, 'description': 'Community Management (light daily check-ins ~2 hrs total)'},
        {'alias': 'community_resolve_issue', 'name': 'Resolve a member support issue', 'points': 3, 'description': 'Community Management (30 min)'},
        {'alias': 'community_weekly_roundup', 'name': 'Post weekly "What\'s on this week" roundup', 'points': 3, 'description': 'Community Management (30 min)'},
        {'alias': 'community_feedback_sum', 'name': 'Collect and summarise community feedback', 'points': 6, 'description': 'Community Management (60 min)'},

        # C) Newsletter & Written Comms
        {'alias': 'comms_nl_collect', 'name': 'Collect updates for newsletter', 'points': 6, 'description': 'Newsletter & Written Comms (60 min)'},
        {'alias': 'comms_nl_draft', 'name': 'Draft newsletter edition', 'points': 12, 'description': 'Newsletter & Written Comms (write + edit ~2 hrs)'},
        {'alias': 'comms_nl_prod', 'name': 'Newsletter full production', 'points': 24, 'description': 'Newsletter & Written Comms (compile + write + format + schedule ~4 hrs)'},
        {'alias': 'comms_nl_qa', 'name': 'Proofread / QA newsletter', 'points': 3, 'description': 'Newsletter & Written Comms (30 min)'},
        {'alias': 'comms_blog_post', 'name': 'Write a community blog post', 'points': 18, 'description': 'Newsletter & Written Comms (1,000–1,500 words ~3 hrs)'},
        {'alias': 'comms_event_recap', 'name': 'Write an event recap post', 'points': 9, 'description': 'Newsletter & Written Comms (60–90 min)'},
        {'alias': 'comms_howto_guide', 'name': 'Write a "how-to" guide/tutorial', 'points': 12, 'description': 'Newsletter & Written Comms (~2 hrs)'},
        {'alias': 'comms_update_docs', 'name': 'Update Notion docs / member handbook page', 'points': 6, 'description': 'Newsletter & Written Comms (60 min)'},

        # D) Social Media & Marketing
        {'alias': 'social_5_posts', 'name': 'Write + schedule 5 social posts', 'points': 6, 'description': 'Social Media & Marketing (60 min)'},
        {'alias': 'social_10_posts', 'name': 'Write + schedule 10 social posts', 'points': 12, 'description': 'Social Media & Marketing (2 hrs)'},
        {'alias': 'social_graphic', 'name': 'Create 1 simple social graphic', 'points': 3, 'description': 'Social Media & Marketing (30 min)'},
        {'alias': 'social_event_promo', 'name': 'Create 1 polished event promo asset set', 'points': 12, 'description': 'Social Media & Marketing (~2 hrs)'},
        {'alias': 'social_edit_video', 'name': 'Edit 1 short video clip/reel', 'points': 6, 'description': 'Social Media & Marketing (45–60 min)'},
        {'alias': 'social_promo_pack', 'name': 'Event promo pack', 'points': 24, 'description': 'Social Media & Marketing (copy + visuals + distribution plan ~4 hrs)'},
        {'alias': 'social_web_update', 'name': 'Website update', 'points': 6, 'description': 'Social Media & Marketing (60 min)'},
        {'alias': 'social_photo_event', 'name': 'Photography at event', 'points': 12, 'description': 'Social Media & Marketing (~2 hrs)'},
        {'alias': 'social_photo_cleanup', 'name': 'Photo clean-up + album + posting highlights', 'points': 12, 'description': 'Social Media & Marketing (~2 hrs)'},

        # E) Events & Programming Operations
        {'alias': 'ops_venue_search', 'name': 'Venue research shortlist', 'points': 6, 'description': 'Events Ops (60 min)'},
        {'alias': 'ops_book_venue', 'name': 'Book venue + confirm logistics', 'points': 6, 'description': 'Events Ops (60 min)'},
        {'alias': 'ops_speaker_outreach', 'name': 'Speaker outreach pack', 'points': 12, 'description': 'Events Ops (~2 hrs)'},
        {'alias': 'ops_speaker_coord', 'name': 'Speaker coordination', 'points': 12, 'description': 'Events Ops (~2 hrs)'},
        {'alias': 'ops_run_sheet', 'name': 'Create event run-sheet', 'points': 6, 'description': 'Events Ops (60 min)'},
        {'alias': 'ops_ticketing', 'name': 'Set up ticketing page + comms links', 'points': 6, 'description': 'Events Ops (60 min)'},
        {'alias': 'ops_mc_event', 'name': 'MC an event', 'points': 12, 'description': 'Events Ops (~2 hrs)'},
        {'alias': 'ops_door_shift', 'name': 'Door/registration shift', 'points': 9, 'description': 'Events Ops (~90 min)'},
        {'alias': 'ops_pack_shift', 'name': 'Setup/pack-down shift', 'points': 9, 'description': 'Events Ops (~90 min)'},
        {'alias': 'ops_workshop_lead', 'name': 'Workshop facilitator', 'points': 30, 'description': 'Events Ops (prep + delivery ~5 hrs)'},
        {'alias': 'ops_workshop_assist', 'name': 'Workshop assistant', 'points': 18, 'description': 'Events Ops (prep + delivery ~3 hrs)'},
        {'alias': 'ops_event_followup', 'name': 'Post-event follow-up', 'points': 6, 'description': 'Events Ops (60 min)'},

        # F) Partnerships
        {'alias': 'partner_leads', 'name': 'Identify 15 sponsor/partner leads', 'points': 6, 'description': 'Partnerships (60 min)'},
        {'alias': 'partner_outreach', 'name': 'Sponsor outreach sprint', 'points': 12, 'description': 'Partnerships (10 emails ~2 hrs)'},
        {'alias': 'partner_call', 'name': 'Sponsor call', 'points': 6, 'description': 'Partnerships (30 min call + prep)'},
        {'alias': 'partner_deck', 'name': 'Draft sponsor proposal / deck update', 'points': 18, 'description': 'Partnerships (~3 hrs)'},
        {'alias': 'partner_deliverables', 'name': 'Manage sponsor deliverables for an event', 'points': 24, 'description': 'Partnerships (~4 hrs)'},
        {'alias': 'partner_maintain', 'name': 'Partner relationship maintenance', 'points': 6, 'description': 'Partnerships (monthly check-in ~60 min)'},

        # G) Grants
        {'alias': 'grant_research', 'name': 'Grant research shortlist', 'points': 12, 'description': 'Grants (~2 hrs)'},
        {'alias': 'grant_draft', 'name': 'Grant draft writing', 'points': 36, 'description': 'Grants (core narrative ~6 hrs)'},
        {'alias': 'grant_app', 'name': 'Grant full application', 'points': 60, 'description': 'Grants (write + budget + attachments ~10 hrs)'},
        {'alias': 'grant_edit', 'name': 'Grant editing/review pass', 'points': 12, 'description': 'Grants (~2 hrs)'},
        {'alias': 'grant_docs', 'name': 'Assemble supporting documents + budget inputs', 'points': 12, 'description': 'Grants (~2 hrs)'},

        # H) Finance
        {'alias': 'fin_bookkeeping', 'name': 'Monthly bookkeeping / reconciliation', 'points': 12, 'description': 'Finance (~2 hrs)'},
        {'alias': 'fin_reimburse', 'name': 'Process reimbursements', 'points': 6, 'description': 'Finance (~60 min)'},
        {'alias': 'fin_budget', 'name': 'Create/update event budget sheet', 'points': 6, 'description': 'Finance (~60 min)'},
        {'alias': 'fin_invoice', 'name': 'Draft sponsor invoice / basic admin paperwork', 'points': 3, 'description': 'Finance (~30 min)'},
        {'alias': 'fin_members', 'name': 'Update membership list / access control', 'points': 6, 'description': 'Finance (60 min)'},
        {'alias': 'fin_forms', 'name': 'Set up forms (RSVP, feedback, volunteer intake)', 'points': 6, 'description': 'Finance (45–60 min)'},

        # I) Tech
        {'alias': 'tech_fix_bug', 'name': 'Fix a small bug / quick improvement', 'points': 6, 'description': 'Tech (~60 min)'},
        {'alias': 'tech_feat_small', 'name': 'Implement a small feature', 'points': 18, 'description': 'Tech (~3 hrs)'},
        {'alias': 'tech_feat_med', 'name': 'Implement a medium feature', 'points': 36, 'description': 'Tech (~6 hrs)'},
        {'alias': 'tech_docs', 'name': 'Write technical documentation page', 'points': 6, 'description': 'Tech (~60 min)'},
        {'alias': 'tech_auto', 'name': 'Set up automation', 'points': 12, 'description': 'Tech (Zapier/Slack ~2 hrs)'},
        {'alias': 'tech_data_clean', 'name': 'Data cleanup / tagging / CRM hygiene', 'points': 12, 'description': 'Tech (~2 hrs)'},
        {'alias': 'tech_analytics', 'name': 'Set up analytics dashboard/report', 'points': 18, 'description': 'Tech (~2–3 hrs)'},
        {'alias': 'tech_security', 'name': 'Security/access review', 'points': 12, 'description': 'Tech (~2 hrs)'},

        # J) Design
        {'alias': 'design_poster', 'name': 'Design a simple poster/flyer', 'points': 9, 'description': 'Design (60–90 min)'},
        {'alias': 'design_promo_kit', 'name': 'Design a full event promo kit', 'points': 18, 'description': 'Design (~3 hrs)'},
        {'alias': 'design_slides', 'name': 'Update slide template / brand assets', 'points': 12, 'description': 'Design (~2 hrs)'},
        {'alias': 'design_merch_coord', 'name': 'Merch coordination', 'points': 12, 'description': 'Design (~2 hrs)'},
        {'alias': 'design_merch_pack', 'name': 'Merch fulfilment session', 'points': 9, 'description': 'Design (~90 min)'},
    ]

    for item in items:
        TaskTemplate.objects.update_or_create(alias=item['alias'], defaults=item)


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0007_populate_pilot_rules'),
    ]

    operations = [
        migrations.RunPython(populate_rate_card, migrations.RunPython.noop),
    ]
