# Generated by Django 5.1.5 on 2025-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0009_add_weekly_allowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelFirstPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Channel First Post',
                'verbose_name_plural': 'Channel First Posts',
                'unique_together': {('slack_user_id', 'channel_id')},
            },
        ),
    ]
