# Generated by Django 4.2.16 on 2025-12-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0010_channelfirstpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=50)),
                ('quest_id', models.CharField(max_length=50)),
                ('current_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('first_progress_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quest Progress',
                'verbose_name_plural': 'Quest Progress',
                'indexes': [models.Index(fields=['slack_user_id'], name='roo_questpr_slack_u_9c005b_idx'), models.Index(fields=['slack_user_id', 'completed'], name='roo_questpr_slack_u_eebc69_idx')],
                'unique_together': {('slack_user_id', 'quest_id')},
            },
        ),
    ]
