# Generated by Django 4.2.16 on 2026-02-09 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0011_questprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedHackCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text="YAML case ID reference (e.g. 'patient_1')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('started_by_slack_id', models.CharField(help_text='Admin Slack ID who started this case', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MedHack Case',
                'verbose_name_plural': 'MedHack Cases',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MedHackWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=50)),
                ('is_first_solver', models.BooleanField(default=False)),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='roo.medhackcase')),
            ],
            options={
                'verbose_name': 'MedHack Winner',
                'verbose_name_plural': 'MedHack Winners',
                'ordering': ['-won_at'],
                'unique_together': {('case', 'slack_user_id')},
            },
        ),
        migrations.CreateModel(
            name='MedHackGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=50)),
                ('guess', models.TextField()),
                ('correct', models.BooleanField(blank=True, help_text='Null while pending, True/False after confirmation', null=True)),
                ('is_pending', models.BooleanField(default=True, help_text='True if awaiting user confirmation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='roo.medhackcase')),
            ],
            options={
                'verbose_name': 'MedHack Guess',
                'verbose_name_plural': 'MedHack Guesses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'slack_user_id'], name='roo_medhack_case_id_bbe3ce_idx')],
            },
        ),
    ]
