# Generated by Django 4.2.16 on 2026-05-04 13:38

from django.db import migrations, models


def backfill_earned_balance(apps, schema_editor):
    PointsAccount = apps.get_model('roo', 'PointsAccount')
    PointsAccount.objects.update(earned_balance=models.F('balance'))


def clear_earned_balance(apps, schema_editor):
    PointsAccount = apps.get_model('roo', 'PointsAccount')
    PointsAccount.objects.update(earned_balance=0)


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0021_alter_taskactivity_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsaccount',
            name='earned_balance',
            field=models.IntegerField(default=0, help_text='Current balance from earned contribution points'),
        ),
        migrations.AddField(
            model_name='pointsaccount',
            name='expired_or_reversed_points',
            field=models.IntegerField(default=0, help_text='Total points expired or reversed'),
        ),
        migrations.AddField(
            model_name='pointsaccount',
            name='lifetime_purchased_topup',
            field=models.IntegerField(default=0, help_text='Total purchased top-up points ever credited'),
        ),
        migrations.AddField(
            model_name='pointsaccount',
            name='purchased_topup_balance',
            field=models.IntegerField(default=0, help_text='Current balance from purchased top-up points'),
        ),
        migrations.RunPython(backfill_earned_balance, clear_earned_balance),
        migrations.AlterField(
            model_name='ledger',
            name='source',
            field=models.CharField(choices=[('TASK', 'Task'), ('COWORKING', 'Coworking'), ('EVENT', 'Event'), ('MERCH', 'Merch'), ('CONTENT_FACTORY', 'Content Factory'), ('TOOLS', 'Tools'), ('DONATION', 'Donation'), ('purchased_topup', 'Purchased Top-Up'), ('MANUAL', 'Manual'), ('LEGACY', 'Legacy')], default='LEGACY', max_length=20),
        ),
    ]
