# Generated by Django 4.2.16 on 2026-05-04 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roo.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roo', '0022_pointsaccount_earned_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_user_id', models.CharField(db_index=True, max_length=50)),
                ('pack_id', models.CharField(max_length=50)),
                ('points_amount', models.PositiveIntegerField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='aud', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=32)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('terms_version_accepted', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_version_accepted', models.CharField(blank=True, max_length=100, null=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_from', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(default=roo.models.default_points_purchase_expires_at)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_purchases', to='roo.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Purchase',
                'verbose_name_plural': 'Points Purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='roo_purchase_user_status_idx'), models.Index(fields=['slack_user_id', 'status'], name='roo_purchase_slack_status_idx'), models.Index(fields=['status', 'created_at'], name='roo_purchase_status_ct_idx')],
            },
        ),
    ]
