# Generated by Django 4.2.16 on 2026-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0026_coworking_day_cost_eight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='source',
            field=models.CharField(choices=[('TASK', 'Task'), ('COWORKING', 'Coworking'), ('EVENT', 'Event'), ('MERCH', 'Merch'), ('CONTENT_FACTORY', 'Content Factory'), ('STARTUP_UPDATE', 'Startup Update'), ('TOOLS', 'Tools'), ('DONATION', 'Donation'), ('purchased_topup', 'Purchased Top-Up'), ('MANUAL', 'Manual'), ('LEGACY', 'Legacy')], default='LEGACY', max_length=20),
        ),
    ]
