# Generated by Django 4.2.16 on 2026-08-01 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roo', '0028_pointspurchase_checkout_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPostAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_key', models.CharField(max_length=255, unique=True)),
                ('workspace_id', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=50)),
                ('root_message_ts', models.CharField(max_length=50)),
                ('poster_slack_id', models.CharField(db_index=True, max_length=50)),
                ('root_text', models.TextField(blank=True, default='')),
                ('social_post_url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('approved', 'Approved'), ('insufficient_points', 'Insufficient points'), ('member_unlinked', 'Member unlinked'), ('invalid_post', 'Invalid post')], db_index=True, max_length=32)),
                ('base_cost_points', models.PositiveIntegerField(default=8)),
                ('charged_points', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_applied', models.BooleanField(default=False)),
                ('balance_before', models.IntegerField(blank=True, null=True)),
                ('new_balance', models.IntegerField(blank=True, null=True)),
                ('rejection_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boost_post_admission', to='roo.ledger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_post_admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['poster_slack_id', 'created_at'], name='roo_boost_poster_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='boostpostadmission',
            constraint=models.UniqueConstraint(fields=('channel_id', 'root_message_ts'), name='uniq_boost_post_slack_root'),
        ),
    ]
