# Generated by Django 4.2.16 on 2026-08-11 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_default_meeting_room(apps, schema_editor):
    MeetingRoom = apps.get_model('roo', 'MeetingRoom')
    MeetingRoom.objects.get_or_create(
        slug='meeting-room',
        defaults={'name': 'Meeting Room', 'is_active': True},
    )


def remove_default_meeting_room(apps, schema_editor):
    MeetingRoom = apps.get_model('roo', 'MeetingRoom')
    MeetingRoom.objects.filter(slug='meeting-room').delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roo', '0029_boostpostadmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RunPython(
            seed_default_meeting_room,
            remove_default_meeting_room,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='source',
            field=models.CharField(choices=[('TASK', 'Task'), ('COWORKING', 'Coworking'), ('MEETING_ROOM', 'Meeting Room'), ('EVENT', 'Event'), ('MERCH', 'Merch'), ('CONTENT_FACTORY', 'Content Factory'), ('STARTUP_UPDATE', 'Startup Update'), ('TOOLS', 'Tools'), ('DONATION', 'Donation'), ('purchased_topup', 'Purchased Top-Up'), ('MANUAL', 'Manual'), ('LEGACY', 'Legacy')], default='LEGACY', max_length=20),
        ),
        migrations.CreateModel(
            name='MeetingRoomBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='roo.meetingroom')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('points_cost', models.PositiveIntegerField()),
                ('client_request_id', models.UUIDField(unique=True)),
                ('requested_by_slack_id', models.CharField(max_length=50)),
                ('slack_channel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_room_booking', to='roo.ledger')),
                ('refund_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_room_refund', to='roo.ledger')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='roo.meetingroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['room', 'status', 'starts_at', 'ends_at'], name='roo_room_time_status_idx'), models.Index(fields=['user', 'status', 'starts_at'], name='roo_room_user_start_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingroombooking',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='meeting_room_booking_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='meetingroomblock',
            index=models.Index(fields=['room', 'starts_at', 'ends_at'], name='roo_room_block_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingroomblock',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='meeting_room_block_end_after_start'),
        ),
    ]
