# Generated by Django 4.2.16 on 2026-07-31 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roo', '0029_boostpostadmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeManagerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('slack_channel_id', models.CharField(max_length=50)),
                ('slack_message_ts', models.CharField(blank=True, default='', max_length=50)),
                ('announcement_status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=20)),
                ('announcement_attempt_count', models.PositiveIntegerField(default=0)),
                ('announcement_last_error', models.TextField(blank=True, default='')),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
                ('claim_cutoff_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('message_update_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='coworkingbooking',
            name='booking_source',
            field=models.CharField(choices=[('points', 'Roo Points'), ('office_manager', 'Office Manager of the Day')], default='points', max_length=30),
        ),
        migrations.AddField(
            model_name='coworkingbooking',
            name='original_points_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OfficeManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('relinquished', 'Relinquished')], default='active', max_length=20)),
                ('points_refunded', models.PositiveIntegerField(default=0)),
                ('winner_dm_status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=20)),
                ('winner_dm_sent_at', models.DateTimeField(blank=True, null=True)),
                ('winner_dm_last_error', models.TextField(blank=True, default='')),
                ('winner_channel_announcement_status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=20)),
                ('winner_channel_announcement_sent_at', models.DateTimeField(blank=True, null=True)),
                ('winner_channel_announcement_last_error', models.TextField(blank=True, default='')),
                ('end_of_day_reminder_status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='pending', max_length=20)),
                ('end_of_day_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('end_of_day_reminder_last_error', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('relinquished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_manager_assignments', to='roo.coworkingbooking')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roo.officemanagerday')),
                ('refund_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_manager_refunds', to='roo.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_manager_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='officemanagerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('day',), name='unique_active_office_manager_per_day'),
        ),
    ]
