# Generated by Django 4.2.16 on 2026-08-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roo', '0030_officemanagerday_coworkingbooking_booking_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officemanagerassignment',
            name='day',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='assignments',
                to='roo.officemanagerday',
            ),
        ),
    ]
