# Generated by Django 4.2.16 on 2026-09-21 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roo', '0040_merge_coworking_operations_office_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='digital_delta_microroo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledger',
            name='purchased_delta_microroo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_refunds', to='roo.ledger'),
        ),
        migrations.AddField(
            model_name='pointsaccount',
            name='digital_balance_microroo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointsaccount',
            name='digital_refund_debt_microroo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AppleIapTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(max_length=16)),
                ('transaction_id', models.CharField(max_length=64)),
                ('original_transaction_id', models.CharField(max_length=64)),
                ('account_token', models.UUIDField()),
                ('product_id', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('granted_microroo', models.PositiveBigIntegerField(default=0)),
                ('price_milliunits', models.PositiveBigIntegerField(null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('purchased_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('latest_signed_at', models.DateTimeField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apple_grants', to='roo.ledger')),
                ('reversal_ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apple_reversals', to='roo.ledger')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppleIapNotification',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=64)),
                ('subtype', models.CharField(blank=True, max_length=64)),
                ('environment', models.CharField(max_length=16)),
                ('signed_at', models.DateTimeField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roo.appleiaptransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='appleiaptransaction',
            index=models.Index(fields=['user', 'environment', 'purchased_at'], name='roo_apple_owner_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appleiaptransaction',
            index=models.Index(fields=['status'], name='roo_apple_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='appleiaptransaction',
            constraint=models.UniqueConstraint(fields=('environment', 'transaction_id'), name='roo_apple_environment_tx_uniq'),
        ),
    ]
