# Generated by Django 4.2.16 on 2026-07-20 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_memory', '0003_source_control_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('notion', 'Notion'), ('gmail', 'Gmail'), ('stripe', 'Stripe'), ('xero', 'Xero'), ('luma', 'Luma')], db_index=True, max_length=32)),
                ('external_account_id', models.CharField(max_length=512)),
                ('source_type', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=1024)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('author_external_id', models.CharField(blank=True, default='', max_length=512)),
                ('lifecycle_state', models.CharField(choices=[('active', 'Active'), ('access_revoked', 'Access revoked'), ('tombstoned', 'Tombstoned')], db_index=True, default='active', max_length=24)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('access_revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tombstone_reason', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_memory_sources', to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_sources', to='org_memory.memoryconnectionconfiguration')),
            ],
            options={
                'ordering': ('organization', 'provider', 'source_type', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='MemorySourceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_key', models.CharField(max_length=512)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bounded_excerpt', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('committee', 'Committee'), ('executive', 'Executive'), ('finance', 'Finance'), ('people_sensitive', 'People sensitive'), ('no_agent', 'No agent')], db_index=True, default='internal', max_length=32)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retired_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='org_memory.memorysource')),
            ],
            options={
                'ordering': ('source', '-captured_at'),
            },
        ),
        migrations.CreateModel(
            name='MemoryWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('notion', 'Notion'), ('gmail', 'Gmail'), ('stripe', 'Stripe'), ('xero', 'Xero'), ('luma', 'Luma')], db_index=True, max_length=32)),
                ('task_type', models.CharField(choices=[('ingest', 'Ingest'), ('chunk', 'Chunk'), ('embed', 'Embed'), ('extract', 'Extract'), ('consolidate', 'Consolidate'), ('summarize', 'Summarize'), ('public_candidate', 'Public candidate'), ('reconcile', 'Reconcile'), ('refresh_permissions', 'Refresh permissions'), ('delete', 'Delete')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('dead', 'Dead'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_work_items', to='organizations.organization')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='org_memory.memorysource')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='org_memory.memorysourceversion')),
            ],
            options={
                'ordering': ('available_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='MemoryWorkerLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('worker_id', models.CharField(max_length=255)),
                ('acquired_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='org_memory.memoryworkitem')),
            ],
            options={
                'ordering': ('-acquired_at',),
            },
        ),
        migrations.AddField(
            model_name='memorysource',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_sources', to='org_memory.memorysourceversion'),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_sources', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='source_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_sources', to='org_memory.memorysourcescope'),
        ),
        migrations.CreateModel(
            name='MemoryReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('claim_activation', 'Claim activation'), ('contradiction', 'Contradiction'), ('correction', 'Correction'), ('sensitivity', 'Sensitivity'), ('stale', 'Stale'), ('entity_merge', 'Entity merge'), ('publication', 'Publication'), ('source_access', 'Source access')], max_length=32)),
                ('target_object_id', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_memory_review_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_review_items', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_memory_review_items', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_memory_review_targets', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-severity', 'due_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='MemoryOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('source_version.captured', 'Source version captured'), ('source.access_revoked', 'Source access revoked'), ('source.tombstoned', 'Source tombstoned')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_outbox_events', to='organizations.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='org_memory.memorysource')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='org_memory.memorysourceversion')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('organization', 'Organization'), ('connection', 'Connection'), ('scope', 'Scope'), ('source', 'Source'), ('provider_principal', 'Provider principal')], max_length=32)),
                ('target_id', models.CharField(max_length=1024)),
                ('reason', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('hard_delete', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_deletion_requests', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_memory_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('ingest', 'Ingest'), ('chunk', 'Chunk'), ('embed', 'Embed'), ('extract', 'Extract'), ('consolidate', 'Consolidate'), ('summarize', 'Summarize'), ('public_candidate', 'Public candidate'), ('reconcile', 'Reconcile'), ('refresh_permissions', 'Refresh permissions'), ('delete', 'Delete')], max_length=32)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField()),
                ('last_error', models.TextField()),
                ('dead_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_dead_letters', to='organizations.organization')),
                ('requeued_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requeued_from_dead_letters', to='org_memory.memoryworkitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_memory_dead_letters', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dead_letter', to='org_memory.memoryworkitem')),
            ],
            options={
                'ordering': ('-dead_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('chunk_kind', models.CharField(blank=True, default='text', max_length=64)),
                ('source_locator', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('committee', 'Committee'), ('executive', 'Executive'), ('finance', 'Finance'), ('people_sensitive', 'People sensitive'), ('no_agent', 'No agent')], db_index=True, default='internal', max_length=32)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_version', models.CharField(blank=True, default='', max_length=64)),
                ('active_for_retrieval', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='org_memory.memorysourceversion')),
            ],
            options={
                'ordering': ('source_version', 'ordinal'),
            },
        ),
        migrations.CreateModel(
            name='MemoryAclSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_revision', models.CharField(blank=True, default='', max_length=512)),
                ('principal_refs', models.JSONField(blank=True, default=list)),
                ('group_refs', models.JSONField(blank=True, default=list)),
                ('link_sharing', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('is_accessible', models.BooleanField(db_index=True, default=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acl_snapshot', to='org_memory.memorysourceversion')),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
        migrations.AddIndex(
            model_name='memoryworkitem',
            index=models.Index(fields=['status', 'available_at', 'created_at'], name='orgmem_work_claim'),
        ),
        migrations.AddIndex(
            model_name='memoryworkitem',
            index=models.Index(fields=['organization', 'provider', 'status'], name='orgmem_work_org_provider'),
        ),
        migrations.AddConstraint(
            model_name='memoryworkitem',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts__gte', 1)), name='orgmem_work_max_attempts_pos'),
        ),
        migrations.AddConstraint(
            model_name='memoryworkitem',
            constraint=models.CheckConstraint(check=models.Q(('attempts__lte', models.F('max_attempts'))), name='orgmem_work_attempts_bounded'),
        ),
        migrations.AddIndex(
            model_name='memoryworkerlease',
            index=models.Index(fields=['released_at', 'expires_at'], name='orgmem_lease_expiry'),
        ),
        migrations.AddConstraint(
            model_name='memoryworkerlease',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('work_item',), name='orgmem_work_active_lease_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memoryworkerlease',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('acquired_at'))), name='orgmem_lease_expiry_valid'),
        ),
        migrations.AddIndex(
            model_name='memorysourceversion',
            index=models.Index(fields=['source', 'is_current', 'captured_at'], name='orgmem_ver_source_current'),
        ),
        migrations.AddConstraint(
            model_name='memorysourceversion',
            constraint=models.UniqueConstraint(fields=('source', 'version_key'), name='orgmem_source_version_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorysourceversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('source',), name='orgmem_source_current_ver_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorysourceversion',
            constraint=models.CheckConstraint(check=models.Q(('is_current', False), ('tombstoned_at__isnull', True), _connector='OR'), name='orgmem_current_ver_not_tomb'),
        ),
        migrations.AddIndex(
            model_name='memorysource',
            index=models.Index(fields=['organization', 'provider', 'source_type', 'lifecycle_state'], name='orgmem_src_org_prov_state'),
        ),
        migrations.AddIndex(
            model_name='memorysource',
            index=models.Index(fields=['configuration', 'lifecycle_state', 'last_seen_at'], name='orgmem_src_cfg_state_seen'),
        ),
        migrations.AddConstraint(
            model_name='memorysource',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'external_account_id', 'source_type', 'external_id'), name='orgmem_source_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorysource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lifecycle_state', 'tombstoned'), ('tombstoned_at__isnull', False)), models.Q(('lifecycle_state', 'tombstoned'), _negated=True), _connector='OR'), name='orgmem_source_tombstone_state'),
        ),
        migrations.AddConstraint(
            model_name='memorysource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('access_revoked_at__isnull', False), ('lifecycle_state', 'access_revoked')), models.Q(('lifecycle_state', 'access_revoked'), _negated=True), _connector='OR'), name='orgmem_source_revoked_state'),
        ),
        migrations.AddIndex(
            model_name='memoryreviewitem',
            index=models.Index(fields=['organization', 'status', 'severity', 'due_at'], name='orgmem_review_queue'),
        ),
        migrations.AddConstraint(
            model_name='memoryreviewitem',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='orgmem_review_idempotency_uniq'),
        ),
        migrations.AddIndex(
            model_name='memoryoutboxevent',
            index=models.Index(fields=['status', 'available_at', 'created_at'], name='orgmem_outbox_pending'),
        ),
        migrations.AddIndex(
            model_name='memorydeletionrequest',
            index=models.Index(fields=['organization', 'status', 'requested_at'], name='orgmem_delete_org_status'),
        ),
        migrations.AddConstraint(
            model_name='memorydeletionrequest',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='orgmem_delete_idempotency_uniq'),
        ),
        migrations.AddIndex(
            model_name='memorydeadletter',
            index=models.Index(fields=['organization', 'resolved_at', 'dead_at'], name='orgmem_dead_org_open'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['source_version', 'active_for_retrieval', 'ordinal'], name='orgmem_chunk_ver_active'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['classification', 'active_for_retrieval', 'occurred_at'], name='orgmem_chunk_class_active'),
        ),
        migrations.AddConstraint(
            model_name='memorychunk',
            constraint=models.UniqueConstraint(fields=('source_version', 'ordinal'), name='orgmem_chunk_version_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorychunk',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_offset__isnull', True), ('start_offset__isnull', True)), models.Q(('end_offset__gt', models.F('start_offset')), ('start_offset__isnull', False)), _connector='OR'), name='orgmem_chunk_offsets_valid'),
        ),
        migrations.AddConstraint(
            model_name='memorychunk',
            constraint=models.CheckConstraint(check=models.Q(('active_for_retrieval', False), models.Q(('classification', 'no_agent'), _negated=True), _connector='OR'), name='orgmem_chunk_no_agent_inactive'),
        ),
        migrations.AddConstraint(
            model_name='memoryaclsnapshot',
            constraint=models.CheckConstraint(check=models.Q(('is_accessible', False), ('revoked_at__isnull', True), _connector='OR'), name='orgmem_acl_accessible_not_revoked'),
        ),
    ]
