# Generated by Django 4.2.16 on 2026-07-21 00:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('org_memory', '0004_evidence_kernel'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryconnectionconfiguration',
            name='next_scheduled_sync_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryconnectionconfiguration',
            name='sync_checkpoint',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='memoryconnectionconfiguration',
            name='sync_cursor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memoryworkitem',
            name='action_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='org_memory.memorysourceactionrequest'),
        ),
        migrations.AddField(
            model_name='memoryworkitem',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='org_memory.memoryconnectionconfiguration'),
        ),
        migrations.CreateModel(
            name='MemorySyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('notion', 'Notion'), ('gmail', 'Gmail'), ('stripe', 'Stripe'), ('xero', 'Xero'), ('luma', 'Luma')], db_index=True, max_length=32)),
                ('action_type', models.CharField(choices=[('discover', 'Discover'), ('preview', 'Preview'), ('dry_run', 'Dry run'), ('backfill', 'Backfill'), ('sync', 'Sync'), ('reprocess', 'Reprocess'), ('refresh_permissions', 'Refresh permissions'), ('delete', 'Delete')], max_length=32)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('cursor_before', models.TextField(blank=True, default='')),
                ('cursor_after', models.TextField(blank=True, default='')),
                ('checkpoint_before', models.JSONField(blank=True, default=dict)),
                ('checkpoint_after', models.JSONField(blank=True, default=dict)),
                ('pages_completed', models.PositiveIntegerField(default=0)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('removals_processed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_run', to='org_memory.memorysourceactionrequest')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='org_memory.memoryconnectionconfiguration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_sync_runs', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryRuntimeLane',
            fields=[
                ('key', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('organization', 'Organization'), ('provider', 'Provider')], max_length=16)),
                ('provider', models.CharField(blank=True, choices=[('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('notion', 'Notion'), ('gmail', 'Gmail'), ('stripe', 'Stripe'), ('xero', 'Xero'), ('luma', 'Luma')], default='', max_length=32)),
                ('blocked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('block_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_runtime_lanes', to='organizations.organization')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.AddField(
            model_name='memoryworkitem',
            name='sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='org_memory.memorysyncrun'),
        ),
        migrations.AddIndex(
            model_name='memorysyncrun',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='orgmem_sync_org_status'),
        ),
        migrations.AddConstraint(
            model_name='memorysyncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'running'))), fields=('configuration',), name='orgmem_sync_active_config_uniq'),
        ),
        migrations.AddIndex(
            model_name='memoryruntimelane',
            index=models.Index(fields=['scope', 'blocked_until'], name='orgmem_lane_blocked'),
        ),
    ]
