# Generated by Django 4.2.16 on 2026-07-21 00:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid


def create_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('CREATE EXTENSION IF NOT EXISTS vector')


def drop_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP EXTENSION IF EXISTS vector')


def create_embedding_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    model = apps.get_model('org_memory', 'MemoryChunkEmbedding')
    schema_editor.add_index(
        model,
        pgvector.django.indexes.HnswIndex(
            ef_construction=64,
            fields=['vector'],
            m=16,
            name='orgmem_embed_vector_hnsw',
            opclasses=('vector_cosine_ops',),
        ),
    )


def drop_embedding_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    model = apps.get_model('org_memory', 'MemoryChunkEmbedding')
    schema_editor.remove_index(
        model,
        pgvector.django.indexes.HnswIndex(
            fields=['vector'],
            name='orgmem_embed_vector_hnsw',
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('org_memory', '0005_memoryconnectionconfiguration_next_scheduled_sync_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, drop_vector_extension),
        migrations.CreateModel(
            name='MemoryChunkEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('dimensions', models.PositiveIntegerField(default=1536)),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
                ('vector_hash', models.CharField(max_length=64)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('chunk', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='memorychunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='orgmem_chunk_search_gin'),
        ),
        migrations.AddField(
            model_name='memorychunkembedding',
            name='chunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='org_memory.memorychunk'),
        ),
        migrations.AddField(
            model_name='memorychunkembedding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_chunk_embeddings', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='memorychunkembedding',
            index=models.Index(fields=['organization', 'model', 'version', 'is_current'], name='orgmem_embed_org_version'),
        ),
        migrations.AddConstraint(
            model_name='memorychunkembedding',
            constraint=models.UniqueConstraint(fields=('chunk', 'model', 'version'), name='orgmem_embedding_chunk_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorychunkembedding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('chunk',), name='orgmem_embedding_one_current'),
        ),
        migrations.AddConstraint(
            model_name='memorychunkembedding',
            constraint=models.CheckConstraint(check=models.Q(('dimensions', 1536)), name='orgmem_embedding_dimensions_1536'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_embedding_hnsw_index,
                    drop_embedding_hnsw_index,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='memorychunkembedding',
                    index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='orgmem_embed_vector_hnsw', opclasses=('vector_cosine_ops',)),
                ),
            ],
        ),
    ]
