# Generated by Django 4.2.16 on 2026-07-21 01:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('org_memory', '0006_memorychunkembedding_memorychunk_search_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveDocumentArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.CharField(max_length=256)),
                ('drive_id', models.CharField(blank=True, default='', max_length=256)),
                ('shortcut_target_id', models.CharField(blank=True, default='', max_length=256)),
                ('parent_ids', models.JSONField(blank=True, default=list)),
                ('selected_root_ids', models.JSONField(default=list)),
                ('lineages', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=512)),
                ('mime_type', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('web_view_url', models.URLField(blank=True, default='', max_length=2048)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_version', models.CharField(blank=True, default='', max_length=512)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('owner_snapshot', models.JSONField(blank=True, default=list)),
                ('permission_snapshot', models.JSONField(blank=True, default=dict)),
                ('lifecycle_state', models.CharField(choices=[('active', 'Active'), ('trashed', 'Trashed'), ('access_lost', 'Access lost'), ('removed', 'Removed')], db_index=True, default='active', max_length=24)),
                ('supported', models.BooleanField(db_index=True, default=False)),
                ('transcript_candidate', models.BooleanField(db_index=True, default=False)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=128)),
                ('extraction_status', models.CharField(choices=[('metadata_only', 'Metadata only'), ('ready_for_parsing', 'Ready for parsing'), ('unsupported', 'Unsupported'), ('extracted', 'Extracted'), ('failed', 'Failed')], db_index=True, default='metadata_only', max_length=32)),
                ('extraction_error', models.TextField(blank=True, default='')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_document_artifacts', to='org_memory.memoryconnectionconfiguration')),
            ],
            options={
                'ordering': ('configuration', 'name', 'file_id'),
            },
        ),
        migrations.CreateModel(
            name='DriveDocumentArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_key', models.CharField(max_length=512)),
                ('metadata_hash', models.CharField(db_index=True, max_length=64)),
                ('metadata_snapshot', models.JSONField(default=dict)),
                ('acl_snapshot', models.JSONField(default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='org_memory.drivedocumentartifact')),
            ],
            options={
                'ordering': ('artifact', '-captured_at'),
            },
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_artifacts', to='org_memory.drivedocumentartifactversion'),
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_document_artifacts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='source_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_document_artifacts', to='org_memory.memorysourcescope'),
        ),
        migrations.CreateModel(
            name='DriveWatchChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=64, unique=True)),
                ('resource_id', models.CharField(max_length=255)),
                ('resource_uri', models.URLField(blank=True, default='', max_length=2048)),
                ('token_hash', models.CharField(max_length=64)),
                ('expiration_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('stopped', 'Stopped')], db_index=True, default='active', max_length=16)),
                ('last_message_number', models.PositiveBigIntegerField(default=0)),
                ('last_resource_state', models.CharField(blank=True, default='', max_length=32)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_watch_channels', to='org_memory.memoryconnectionconfiguration')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['configuration', 'status', 'expiration_at'], name='orgmem_drive_watch_active')],
            },
        ),
        migrations.CreateModel(
            name='DriveInventoryManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_id', models.UUIDField()),
                ('selection_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('selected_roots', models.JSONField(default=list)),
                ('historical_cutoff', models.DateTimeField()),
                ('allowed_mime_types', models.JSONField(default=list)),
                ('is_partial', models.BooleanField(db_index=True, default=False)),
                ('ceiling_reason', models.CharField(blank=True, default='', max_length=64)),
                ('counts', models.JSONField(default=dict)),
                ('formats', models.JSONField(default=dict)),
                ('owners', models.JSONField(default=dict)),
                ('date_range', models.JSONField(default=dict)),
                ('estimated', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('start_page_token', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(default=list)),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_inventory_manifests', to='org_memory.memoryconnectionconfiguration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_inventory_manifests', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['configuration', 'created_at'], name='orgmem_drive_inv_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='driveinventorymanifest',
            constraint=models.UniqueConstraint(fields=('configuration', 'inventory_id'), name='orgmem_drive_inventory_uniq'),
        ),
        migrations.AddIndex(
            model_name='drivedocumentartifactversion',
            index=models.Index(fields=['artifact', 'is_current', 'captured_at'], name='orgmem_drive_ver_current'),
        ),
        migrations.AddConstraint(
            model_name='drivedocumentartifactversion',
            constraint=models.UniqueConstraint(fields=('artifact', 'version_key'), name='orgmem_drive_artifact_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drivedocumentartifactversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('artifact',), name='orgmem_drive_artifact_current_uniq'),
        ),
        migrations.AddIndex(
            model_name='drivedocumentartifact',
            index=models.Index(fields=['organization', 'lifecycle_state', 'source_modified_at'], name='orgmem_drive_org_state'),
        ),
        migrations.AddIndex(
            model_name='drivedocumentartifact',
            index=models.Index(fields=['configuration', 'transcript_candidate', 'extraction_status'], name='orgmem_drive_cfg_extract'),
        ),
        migrations.AddConstraint(
            model_name='drivedocumentartifact',
            constraint=models.UniqueConstraint(fields=('configuration', 'file_id'), name='orgmem_drive_artifact_file_uniq'),
        ),
        migrations.AddConstraint(
            model_name='drivedocumentartifact',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lifecycle_state', 'active'), ('removed_at__isnull', True)), models.Q(('lifecycle_state', 'active'), _negated=True), _connector='OR'), name='orgmem_drive_active_not_removed'),
        ),
    ]
