# Generated by Django 4.2.16 on 2026-07-21 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('org_memory', '0007_drivedocumentartifact_drivedocumentartifactversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=64)),
                ('normalized_title', models.CharField(max_length=512)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('timezone_name', models.CharField(default='Australia/Sydney', max_length=64)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('identity_basis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('organization', '-occurred_at', 'normalized_title'),
            },
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='extracted_content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='extraction_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='last_extracted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='parser_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='drivedocumentartifact',
            name='work_classification',
            field=models.CharField(blank=True, choices=[('', 'None'), ('needs_ocr', 'Needs OCR'), ('needs_transcription', 'Needs transcription'), ('unsupported_format', 'Unsupported format'), ('download_restricted', 'Download restricted'), ('shortcut', 'Shortcut not followed'), ('not_transcript_candidate', 'Not a transcript candidate'), ('duplicate_suppressed', 'Duplicate suppressed')], db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='drivedocumentartifact',
            name='extraction_status',
            field=models.CharField(choices=[('metadata_only', 'Metadata only'), ('ready_for_parsing', 'Ready for parsing'), ('unsupported', 'Unsupported'), ('extracted', 'Extracted'), ('duplicate', 'Duplicate suppressed'), ('failed', 'Failed')], db_index=True, default='metadata_only', max_length=32),
        ),
        migrations.CreateModel(
            name='DriveReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.JSONField(default=dict)),
                ('last_checkpoint', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_reconciliation_reports', to='org_memory.memoryconnectionconfiguration')),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_reports', to='org_memory.driveinventorymanifest')),
                ('sync_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_reconciliation_report', to='org_memory.memorysyncrun')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='DriveMeetingArtifactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('canonical', 'Canonical'), ('same_meeting_as', 'Same meeting as'), ('copied_from', 'Copied from'), ('derived_from', 'Derived from')], default='same_meeting_as', max_length=24)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_link', to='org_memory.drivedocumentartifact')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_drive_artifacts', to='org_memory.drivedocumentartifact')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_links', to='org_memory.drivemeeting')),
            ],
            options={
                'ordering': ('meeting', 'artifact'),
            },
        ),
        migrations.AddField(
            model_name='drivemeeting',
            name='canonical_artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_for_meetings', to='org_memory.drivedocumentartifact'),
        ),
        migrations.AddField(
            model_name='drivemeeting',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_meetings', to='org_memory.memoryconnectionconfiguration'),
        ),
        migrations.AddField(
            model_name='drivemeeting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_meetings', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='DriveDocumentExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('metadata_only', 'Metadata only'), ('ready_for_parsing', 'Ready for parsing'), ('unsupported', 'Unsupported'), ('extracted', 'Extracted'), ('duplicate', 'Duplicate suppressed'), ('failed', 'Failed')], max_length=32)),
                ('work_classification', models.CharField(blank=True, choices=[('', 'None'), ('needs_ocr', 'Needs OCR'), ('needs_transcription', 'Needs transcription'), ('unsupported_format', 'Unsupported format'), ('download_restricted', 'Download restricted'), ('shortcut', 'Shortcut not followed'), ('not_transcript_candidate', 'Not a transcript candidate'), ('duplicate_suppressed', 'Duplicate suppressed')], default='', max_length=32)),
                ('parser_name', models.CharField(max_length=64)),
                ('parser_version', models.CharField(max_length=64)),
                ('export_mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('normalized_content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('content_signature', models.JSONField(blank=True, default=list)),
                ('byte_count', models.PositiveBigIntegerField(default=0)),
                ('character_count', models.PositiveBigIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('parser_report', models.JSONField(blank=True, default=dict)),
                ('extracted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('artifact_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='org_memory.drivedocumentartifactversion')),
                ('source_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_extraction', to='org_memory.memorysourceversion')),
            ],
            options={
                'ordering': ('-extracted_at',),
            },
        ),
        migrations.AddIndex(
            model_name='drivemeeting',
            index=models.Index(fields=['organization', 'occurred_at'], name='orgmem_drive_meeting_date'),
        ),
        migrations.AddConstraint(
            model_name='drivemeeting',
            constraint=models.UniqueConstraint(fields=('configuration', 'identity_key'), name='orgmem_drive_meeting_identity_uniq'),
        ),
        migrations.AddIndex(
            model_name='drivedocumentextraction',
            index=models.Index(fields=['status', 'work_classification', 'extracted_at'], name='orgmem_drive_extract_status'),
        ),
        migrations.AddConstraint(
            model_name='drivedocumentextraction',
            constraint=models.UniqueConstraint(fields=('artifact_version', 'parser_version'), name='orgmem_drive_extract_parser_uniq'),
        ),
    ]
