# Generated by Django 4.2.16 on 2026-07-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_memory', '0008_drivemeeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveinventorymanifest',
            name='counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='driveinventorymanifest',
            name='date_range',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='driveinventorymanifest',
            name='estimated',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='driveinventorymanifest',
            name='formats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='driveinventorymanifest',
            name='owners',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='driveinventorymanifest',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
