# Generated by Django 4.2.16 on 2026-07-21 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_memory', '0009_alter_driveinventorymanifest_counts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_key', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('fact', 'Fact'), ('decision', 'Decision'), ('commitment', 'Commitment'), ('task', 'Task'), ('open_loop', 'Open loop'), ('project_status', 'Project status'), ('event', 'Event'), ('policy', 'Policy'), ('procedure', 'Procedure'), ('lesson', 'Lesson'), ('relationship', 'Relationship'), ('person_profile', 'Person profile'), ('preference', 'Preference'), ('risk', 'Risk'), ('opportunity', 'Opportunity'), ('metric', 'Metric'), ('question', 'Question'), ('summary', 'Summary')], db_index=True, max_length=32)),
                ('epistemic_type', models.CharField(choices=[('proposal', 'Proposal'), ('testimony', 'Testimony'), ('decision', 'Decision'), ('system_fact', 'System-of-record fact'), ('observation', 'Observation')], db_index=True, max_length=24)),
                ('predicate', models.CharField(max_length=255)),
                ('object_value', models.JSONField(blank=True, null=True)),
                ('statement', models.TextField()),
                ('normalized_key', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('stale', 'Stale'), ('superseded', 'Superseded'), ('contradicted', 'Contradicted'), ('retracted', 'Retracted'), ('archived', 'Archived')], db_index=True, default='candidate', max_length=16)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('committee', 'Committee'), ('executive', 'Executive'), ('finance', 'Finance'), ('people_sensitive', 'People sensitive'), ('no_agent', 'No agent')], db_index=True, default='internal', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('importance', models.DecimalField(decimal_places=3, max_digits=4)),
                ('source_authority', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('volatility', models.CharField(choices=[('stable', 'Stable'), ('normal', 'Normal'), ('volatile', 'Volatile')], default='normal', max_length=16)),
                ('observed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_start_at', models.DateTimeField(blank=True, null=True)),
                ('event_end_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('stale_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('review_required', models.BooleanField(db_index=True, default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('extractor_version', models.CharField(max_length=64)),
                ('extractor_model', models.CharField(max_length=128)),
                ('extractor_prompt_version', models.CharField(max_length=64)),
                ('extractor_schema_version', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('extracted', 'Extracted'), ('no_memory', 'No durable memory'), ('quarantined', 'Quarantined'), ('rejected', 'Rejected')], db_index=True, max_length=16)),
                ('extractor_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('prompt_input_hash', models.CharField(max_length=64)),
                ('candidate_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_summary', models.TextField(blank=True, default='')),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('no_memory_reason', models.CharField(blank=True, default='', max_length=512)),
                ('provider_response_id', models.CharField(blank=True, default='', max_length=255)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_extraction_runs', to='organizations.organization')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='org_memory.memorysourceversion')),
            ],
            options={
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_role', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('context', 'Context')], default='supports', max_length=16)),
                ('quote', models.TextField()),
                ('quote_start', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_end', models.PositiveIntegerField(blank=True, null=True)),
                ('quote_hash', models.CharField(max_length=64)),
                ('source_locator', models.JSONField(default=dict)),
                ('evidence_confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_evidence', to='org_memory.memorychunk')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='org_memory.memoryclaim')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_evidence', to='org_memory.memorysource')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_evidence', to='org_memory.memorysourceversion')),
            ],
            options={
                'ordering': ('claim', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='MemoryEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('team', 'Team'), ('committee', 'Committee'), ('project', 'Project'), ('event', 'Event'), ('organization', 'Organization'), ('partner', 'Partner'), ('sponsor', 'Sponsor'), ('customer', 'Customer'), ('tool', 'Tool'), ('repository', 'Repository'), ('channel', 'Channel'), ('document', 'Document'), ('policy', 'Policy'), ('task', 'Task'), ('metric', 'Metric'), ('venue', 'Venue'), ('skill', 'Skill')], db_index=True, max_length=32)),
                ('canonical_name', models.CharField(max_length=512)),
                ('normalized_name', models.CharField(db_index=True, max_length=512)),
                ('resolved_key', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('external_refs', models.JSONField(blank=True, default=dict)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('committee', 'Committee'), ('executive', 'Executive'), ('finance', 'Finance'), ('people_sensitive', 'People sensitive'), ('no_agent', 'No agent')], db_index=True, default='internal', max_length=32)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entities', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization', 'entity_type', 'normalized_name'),
            },
        ),
        migrations.CreateModel(
            name='MemoryClaimStateEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('active', 'Active'), ('stale', 'Stale'), ('superseded', 'Superseded'), ('contradicted', 'Contradicted'), ('retracted', 'Retracted'), ('archived', 'Archived')], default='', max_length=16)),
                ('to_status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('stale', 'Stale'), ('superseded', 'Superseded'), ('contradicted', 'Contradicted'), ('retracted', 'Retracted'), ('archived', 'Archived')], max_length=16)),
                ('reason', models.CharField(max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_claim_state_events', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='org_memory.memoryclaim')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_state_events', to='org_memory.memoryreviewitem')),
            ],
            options={
                'ordering': ('claim', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='MemoryClaimLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('duplicate_of', 'Duplicate of'), ('supports', 'Supports'), ('refines', 'Refines'), ('supersedes', 'Supersedes'), ('contradicts', 'Contradicts'), ('derived_from', 'Derived from')], max_length=24)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='org_memory.memoryclaim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_claim_links', to='organizations.organization')),
                ('to_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='org_memory.memoryclaim')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='extraction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='org_memory.memoryextractionrun'),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='object_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_claims', to='org_memory.memoryentity'),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_claims', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_memory_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='subject_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_claims', to='org_memory.memoryentity'),
        ),
        migrations.AddIndex(
            model_name='memoryextractionrun',
            index=models.Index(fields=['organization', 'status', 'completed_at'], name='orgmem_extract_org_status'),
        ),
        migrations.AddIndex(
            model_name='memoryextractionrun',
            index=models.Index(fields=['source_version', 'extractor_version'], name='orgmem_extract_version'),
        ),
        migrations.AddConstraint(
            model_name='memoryevidence',
            constraint=models.UniqueConstraint(fields=('claim', 'chunk', 'evidence_role', 'quote_hash'), name='orgmem_evidence_quote_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memoryevidence',
            constraint=models.CheckConstraint(check=models.Q(('evidence_confidence__gte', 0), ('evidence_confidence__lte', 1)), name='orgmem_evidence_conf_range'),
        ),
        migrations.AddConstraint(
            model_name='memoryevidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('quote_end__isnull', True), ('quote_start__isnull', True)), models.Q(('quote_end__gt', models.F('quote_start')), ('quote_start__isnull', False)), _connector='OR'), name='orgmem_evidence_offsets'),
        ),
        migrations.AddIndex(
            model_name='memoryentity',
            index=models.Index(fields=['organization', 'entity_type', 'normalized_name'], name='orgmem_entity_name'),
        ),
        migrations.AddConstraint(
            model_name='memoryentity',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_key', ''), _negated=True), fields=('organization', 'resolved_key'), name='orgmem_entity_resolved_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='memoryclaimstateevent',
            index=models.Index(fields=['claim', 'created_at'], name='orgmem_claim_state_time'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaimlink',
            constraint=models.UniqueConstraint(fields=('from_claim', 'to_claim', 'relation_type'), name='orgmem_claim_link_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaimlink',
            constraint=models.CheckConstraint(check=models.Q(('from_claim', models.F('to_claim')), _negated=True), name='orgmem_claim_link_not_self'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaimlink',
            constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='orgmem_claim_link_conf_range'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['organization', 'status', 'kind', 'recorded_at'], name='orgmem_claim_org_state'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['organization', 'normalized_key', 'status'], name='orgmem_claim_normalized'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.UniqueConstraint(fields=('extraction_run', 'candidate_key'), name='orgmem_claim_candidate_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='orgmem_claim_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.CheckConstraint(check=models.Q(('importance__gte', 0), ('importance__lte', 1)), name='orgmem_claim_importance_range'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.CheckConstraint(check=models.Q(('source_authority__gte', 0), ('source_authority__lte', 1)), name='orgmem_claim_authority_range'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='orgmem_claim_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.CheckConstraint(check=models.Q(('event_end_at__isnull', True), ('event_start_at__isnull', True), ('event_end_at__gte', models.F('event_start_at')), _connector='OR'), name='orgmem_claim_event_interval'),
        ),
    ]
