# Generated by Django 4.2.16 on 2026-07-21 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_memory', '0010_memoryclaim_memoryextractionrun_memoryevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryentity',
            name='merged_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryentity',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_entities', to='org_memory.memoryentity'),
        ),
        migrations.CreateModel(
            name='MemoryCorrectionProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correction_text', models.TextField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_correction_proposals', to='organizations.organization')),
                ('original_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_proposals', to='org_memory.memoryclaim')),
                ('replacement_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for_corrections', to='org_memory.memoryclaim')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_corrections_requested', to=settings.AUTH_USER_MODEL)),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_proposals', to='org_memory.memoryreviewitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_corrections_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryConsolidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('operation', models.CharField(choices=[('new', 'New'), ('duplicate', 'Duplicate'), ('supports', 'Supports'), ('refines', 'Refines'), ('supersedes', 'Supersedes'), ('contradicts', 'Contradicts'), ('ignore', 'Ignore')], max_length=16)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('review_required', 'Review required'), ('ignored', 'Ignored'), ('quarantined', 'Quarantined')], db_index=True, max_length=24)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('reason', models.CharField(max_length=1000)),
                ('deterministic', models.BooleanField(default=False)),
                ('consolidator_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('prompt_input_hash', models.CharField(max_length=64)),
                ('output_hash', models.CharField(max_length=64)),
                ('provider_response_id', models.CharField(blank=True, default='', max_length=255)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_runs', to='org_memory.memoryclaim')),
                ('matched_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_consolidation_runs', to='org_memory.memoryclaim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_consolidation_runs', to='organizations.organization')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidation_runs', to='org_memory.memoryreviewitem')),
            ],
            options={
                'ordering': ('-completed_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryEntityResolutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('merge', 'Merge'), ('split', 'Split')], max_length=16)),
                ('reason', models.CharField(max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_entity_resolution_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entity_resolution_events', to='organizations.organization')),
                ('primary_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_resolution_events', to='org_memory.memoryentity')),
                ('review_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_resolution_events', to='org_memory.memoryreviewitem')),
                ('secondary_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_resolution_events', to='org_memory.memoryentity')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'operation', 'created_at'], name='orgmem_entity_resolution')],
            },
        ),
        migrations.CreateModel(
            name='MemoryCurrentState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(max_length=255)),
                ('state_key', models.CharField(max_length=320)),
                ('state_value', models.JSONField(default=dict)),
                ('valid_as_of', models.DateTimeField(db_index=True)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('has_conflict', models.BooleanField(db_index=True, default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('distinct_source_count', models.PositiveIntegerField(default=1)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_state_rows', to='org_memory.memoryclaim')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_current_states', to='organizations.organization')),
                ('scope_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_states', to='org_memory.memoryentity')),
            ],
            options={
                'ordering': ('organization', 'scope_key', 'state_key'),
                'indexes': [models.Index(fields=['organization', 'is_stale', 'has_conflict'], name='orgmem_current_warnings')],
            },
        ),
        migrations.AddConstraint(
            model_name='memorycurrentstate',
            constraint=models.UniqueConstraint(fields=('organization', 'scope_key', 'state_key'), name='orgmem_current_state_uniq'),
        ),
        migrations.AddIndex(
            model_name='memorycorrectionproposal',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='orgmem_correction_queue'),
        ),
        migrations.AddIndex(
            model_name='memoryconsolidationrun',
            index=models.Index(fields=['organization', 'status', 'completed_at'], name='orgmem_consol_org_status'),
        ),
        migrations.AddIndex(
            model_name='memoryconsolidationrun',
            index=models.Index(fields=['candidate_claim', 'consolidator_version'], name='orgmem_consol_claim_ver'),
        ),
    ]
