# Generated by Django 4.2.16 on 2026-07-21 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_company_linkedin_url'),
        ('org_memory', '0011_memoryentity_merged_at_memoryentity_merged_into_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(default='committee', max_length=32)),
                ('requester_slack_id', models.CharField(blank=True, default='', max_length=32)),
                ('channel_id', models.CharField(blank=True, default='', max_length=32)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('query', models.TextField()),
                ('query_hash', models.CharField(max_length=64)),
                ('query_plan', models.JSONField(default=dict)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('candidate_trace', models.JSONField(blank=True, default=list)),
                ('selected_claim_ids', models.JSONField(blank=True, default=list)),
                ('selected_chunk_ids', models.JSONField(blank=True, default=list)),
                ('answer', models.TextField(blank=True, default='')),
                ('citation_data', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('abstained', 'Abstained'), ('search_only', 'Search only'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('evidence_sufficiency', models.CharField(choices=[('sufficient', 'Sufficient'), ('partial', 'Partial'), ('insufficient', 'Insufficient')], db_index=True, max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('selector_version', models.CharField(max_length=64)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_version', models.CharField(blank=True, default='', max_length=128)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('answerer_version', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('schema_version', models.CharField(blank=True, default='', max_length=64)),
                ('provider_response_id', models.CharField(blank=True, default='', max_length=255)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_query_logs', to='organizations.organization')),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('relevant', 'Relevant'), ('irrelevant', 'Irrelevant'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('stale', 'Stale'), ('missing', 'Missing'), ('harmful', 'Harmful')], max_length=16)),
                ('correction_text', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='org_memory.memoryclaim')),
                ('correction_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='org_memory.memorycorrectionproposal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_feedback', to='organizations.organization')),
                ('query_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='org_memory.memoryquerylog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='memoryquerylog',
            index=models.Index(fields=['organization', 'created_at'], name='orgmem_query_org_created'),
        ),
        migrations.AddIndex(
            model_name='memoryquerylog',
            index=models.Index(fields=['organization', 'requester_user', 'created_at'], name='orgmem_query_user_created'),
        ),
        migrations.AddIndex(
            model_name='memoryfeedback',
            index=models.Index(fields=['organization', 'feedback_type', 'created_at'], name='orgmem_feedback_queue'),
        ),
    ]
