# Generated by Django 4.2.16 on 2026-07-22 01:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org_memory', '0012_memoryquerylog_memoryfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryProviderEventReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive'), ('slack', 'Slack'), ('linear', 'Linear'), ('notion', 'Notion'), ('gmail', 'Gmail'), ('stripe', 'Stripe'), ('xero', 'Xero'), ('luma', 'Luma')], db_index=True, max_length=32)),
                ('receipt_key', models.CharField(max_length=64)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=512)),
                ('external_scope_id', models.CharField(blank=True, default='', max_length=512)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('scheduled_configuration_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['provider', 'received_at'], name='orgmem_event_provider_received')],
            },
        ),
        migrations.AddConstraint(
            model_name='memoryprovidereventreceipt',
            constraint=models.UniqueConstraint(fields=('provider', 'receipt_key'), name='orgmem_provider_event_receipt_uniq'),
        ),
    ]
