# Generated by Django 4.2.16 on 2026-07-22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("org_memory", "0013_provider_event_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionPageArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notion_page_id", models.CharField(max_length=128)),
                ("selected_root_ids", models.JSONField(default=list)),
                ("ancestor_page_ids", models.JSONField(blank=True, default=list)),
                ("parent_type", models.CharField(blank=True, default="", max_length=32)),
                ("parent_external_id", models.CharField(blank=True, default="", max_length=128)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("canonical_url", models.URLField(blank=True, default="", max_length=2048)),
                ("property_text", models.TextField(blank=True, default="")),
                ("cleaned_text", models.TextField(blank=True, default="")),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("lifecycle_state", models.CharField(choices=[("active", "Active"), ("trashed", "Trashed"), ("access_lost", "Access lost")], db_index=True, default="active", max_length=24)),
                ("in_trash", models.BooleanField(db_index=True, default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("provider_revision", models.CharField(blank=True, default="", max_length=128)),
                ("content_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("scan_generation", models.UUIDField(blank=True, db_index=True, null=True)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("configuration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notion_page_artifacts", to="org_memory.memoryconnectionconfiguration")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notion_page_artifacts", to="organizations.organization")),
                ("source_scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notion_page_artifacts", to="org_memory.memorysourcescope")),
            ],
            options={
                "ordering": ("configuration", "title", "notion_page_id"),
                "indexes": [models.Index(fields=["configuration", "lifecycle_state", "source_updated_at"], name="orgmem_notion_cfg_state")],
            },
        ),
        migrations.CreateModel(
            name="NotionBlockArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notion_block_id", models.CharField(max_length=128)),
                ("parent_block_id", models.CharField(blank=True, default="", max_length=128)),
                ("block_type", models.CharField(max_length=64)),
                ("ordinal", models.PositiveIntegerField()),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("heading_path", models.JSONField(blank=True, default=list)),
                ("plain_text", models.TextField(blank=True, default="")),
                ("has_children", models.BooleanField(default=False)),
                ("in_trash", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocks", to="org_memory.notionpageartifact")),
            ],
            options={
                "ordering": ("page", "ordinal", "notion_block_id"),
                "indexes": [models.Index(fields=["page", "ordinal"], name="orgmem_notion_block_order")],
            },
        ),
        migrations.AddConstraint(
            model_name="notionpageartifact",
            constraint=models.UniqueConstraint(fields=("configuration", "notion_page_id"), name="orgmem_notion_page_uniq"),
        ),
        migrations.AddConstraint(
            model_name="notionblockartifact",
            constraint=models.UniqueConstraint(fields=("page", "notion_block_id"), name="orgmem_notion_block_uniq"),
        ),
    ]
