# Generated by Django 4.2.16 on 2026-07-22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("startup_updates", "0013_luma_event_selection"),
        ("org_memory", "0014_notion_artifacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailMailboxWatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email_address", models.EmailField(max_length=254)),
                ("topic_name", models.CharField(max_length=512)),
                ("label_ids", models.JSONField(default=list)),
                ("history_id", models.CharField(blank=True, default="", max_length=255)),
                ("expiration_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("expired", "Expired"), ("error", "Error"), ("stopped", "Stopped")], db_index=True, default="active", max_length=16)),
                ("last_renewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_notification_at", models.DateTimeField(blank=True, null=True)),
                ("last_notification_history_id", models.CharField(blank=True, default="", max_length=255)),
                ("last_pubsub_message_id", models.CharField(blank=True, default="", max_length=255)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("configuration", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="gmail_mailbox_watch", to="org_memory.memoryconnectionconfiguration")),
            ],
            options={
                "ordering": ("expiration_at", "configuration"),
                "indexes": [models.Index(fields=["status", "expiration_at"], name="orgmem_gmail_watch_expiry")],
            },
        ),
        migrations.CreateModel(
            name="GmailScopedMessageArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("gmail_message_id", models.CharField(max_length=255)),
                ("gmail_thread_id", models.CharField(db_index=True, max_length=255)),
                ("selected_label_ids", models.JSONField(default=list)),
                ("lifecycle_state", models.CharField(choices=[("active", "Active"), ("label_removed", "Label removed"), ("deleted", "Deleted"), ("access_lost", "Access lost")], db_index=True, default="active", max_length=24)),
                ("history_id", models.CharField(blank=True, default="", max_length=255)),
                ("internal_date", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("scan_generation", models.UUIDField(blank=True, db_index=True, null=True)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("removed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("configuration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gmail_scoped_message_artifacts", to="org_memory.memoryconnectionconfiguration")),
                ("message_artifact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="memory_scope_artifacts", to="startup_updates.gmailmessageartifact")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gmail_scoped_message_artifacts", to="organizations.organization")),
                ("source_scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="gmail_scoped_message_artifacts", to="org_memory.memorysourcescope")),
            ],
            options={
                "ordering": ("configuration", "gmail_thread_id", "internal_date", "gmail_message_id"),
                "indexes": [models.Index(fields=["configuration", "lifecycle_state", "gmail_thread_id"], name="orgmem_gmail_cfg_thread")],
            },
        ),
        migrations.AddConstraint(
            model_name="gmailscopedmessageartifact",
            constraint=models.UniqueConstraint(fields=("configuration", "gmail_message_id"), name="orgmem_gmail_scoped_msg_uniq"),
        ),
    ]
