# Generated by Django 4.2.16 on 2026-07-22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("org_memory", "0015_gmail_scoped_artifacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuredAggregateArtifact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("google_drive", "Google Drive"), ("slack", "Slack"), ("linear", "Linear"), ("notion", "Notion"), ("gmail", "Gmail"), ("stripe", "Stripe"), ("xero", "Xero"), ("luma", "Luma")], db_index=True, max_length=32)),
                ("source_type", models.CharField(max_length=64)),
                ("external_id", models.CharField(max_length=512)),
                ("metric_key", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("period_start", models.DateField(blank=True, db_index=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("value_number", models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ("value_text", models.CharField(blank=True, default="", max_length=255)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("source_revision", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("volatile_until", models.DateTimeField(blank=True, null=True)),
                ("stale_after", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("lifecycle_state", models.CharField(choices=[("active", "Active"), ("removed", "Removed"), ("access_lost", "Access lost")], db_index=True, default="active", max_length=24)),
                ("scan_generation", models.UUIDField(blank=True, db_index=True, null=True)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("configuration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="structured_aggregate_artifacts", to="org_memory.memoryconnectionconfiguration")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="structured_memory_aggregates", to="organizations.organization")),
                ("source_scope", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="structured_aggregate_artifacts", to="org_memory.memorysourcescope")),
            ],
            options={
                "ordering": ("configuration", "source_type", "period_start", "external_id"),
                "indexes": [
                    models.Index(fields=["configuration", "lifecycle_state", "period_start"], name="orgmem_struct_agg_cfg_state"),
                    models.Index(fields=["provider", "metric_key", "period_start"], name="orgmem_struct_agg_metric"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="structuredaggregateartifact",
            constraint=models.UniqueConstraint(fields=("configuration", "source_type", "external_id"), name="orgmem_struct_agg_identity_uniq"),
        ),
    ]
