# Generated by Django 4.2.16 on 2026-07-23 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_company_linkedin_url"),
        ("org_memory", "0016_structured_aggregate_artifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryDailyReconciliationReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("report_date", models.DateField(db_index=True)),
                ("time_zone", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("running", "Running"), ("completed", "Completed"), ("degraded", "Degraded"), ("failed", "Failed")], db_index=True, default="running", max_length=16)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memory_daily_reconciliation_reports", to="organizations.organization")),
            ],
            options={"ordering": ("-report_date", "organization")},
        ),
        migrations.CreateModel(
            name="MemoryDailyCostLedger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("budget_date", models.DateField(db_index=True)),
                ("currency", models.CharField(default="AUD", max_length=3)),
                ("ceiling_aud", models.DecimalField(decimal_places=6, max_digits=12)),
                ("reserved_aud", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("consumed_aud", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memory_daily_cost_ledgers", to="organizations.organization")),
            ],
            options={"ordering": ("-budget_date", "organization")},
        ),
        migrations.CreateModel(
            name="MemoryCostReservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task_type", models.CharField(choices=[("ingest", "Ingest"), ("chunk", "Chunk"), ("embed", "Embed"), ("extract", "Extract"), ("consolidate", "Consolidate"), ("summarize", "Summarize"), ("public_candidate", "Public candidate"), ("reconcile", "Reconcile"), ("refresh_permissions", "Refresh permissions"), ("delete", "Delete")], max_length=32)),
                ("estimated_tokens", models.PositiveIntegerField(default=0)),
                ("estimated_cost_aud", models.DecimalField(decimal_places=6, max_digits=12)),
                ("actual_cost_aud", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("status", models.CharField(choices=[("reserved", "Reserved"), ("consumed", "Consumed"), ("released", "Released")], db_index=True, default="reserved", max_length=16)),
                ("reserved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ledger", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="org_memory.memorydailycostledger")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memory_cost_reservations", to="organizations.organization")),
                ("work_item", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="cost_reservation", to="org_memory.memoryworkitem")),
            ],
            options={"ordering": ("-reserved_at",)},
        ),
        migrations.CreateModel(
            name="MemoryConnectionHealthSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("google_drive", "Google Drive"), ("slack", "Slack"), ("linear", "Linear"), ("notion", "Notion"), ("gmail", "Gmail"), ("stripe", "Stripe"), ("xero", "Xero"), ("luma", "Luma")], db_index=True, max_length=32)),
                ("health_status", models.CharField(choices=[("healthy", "Healthy"), ("syncing", "Syncing"), ("stale", "Stale"), ("error", "Error")], db_index=True, default="syncing", max_length=16)),
                ("schedule_status", models.CharField(db_index=True, default="waiting", max_length=24)),
                ("credential_status", models.CharField(blank=True, default="unknown", max_length=32)),
                ("freshness_status", models.CharField(blank=True, default="unknown", max_length=16)),
                ("watch_status", models.CharField(blank=True, default="not_applicable", max_length=24)),
                ("provider_interval_seconds", models.PositiveIntegerField(default=86400)),
                ("freshness_slo_seconds", models.PositiveIntegerField(default=86400)),
                ("source_lag_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("catch_up", models.BooleanField(db_index=True, default=False)),
                ("last_attempted_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_sync_at", models.DateTimeField(blank=True, null=True)),
                ("operator_action", models.CharField(blank=True, default="", max_length=512)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="daily_health_snapshots", to="org_memory.memorysourceactionrequest")),
                ("configuration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_health_snapshots", to="org_memory.memoryconnectionconfiguration")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memory_connection_health_snapshots", to="organizations.organization")),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="connection_snapshots", to="org_memory.memorydailyreconciliationreport")),
            ],
            options={"ordering": ("provider", "configuration")},
        ),
        migrations.AddIndex(
            model_name="memorydailyreconciliationreport",
            index=models.Index(fields=["organization", "status", "report_date"], name="orgmem_daily_report_org_state"),
        ),
        migrations.AddConstraint(
            model_name="memorydailyreconciliationreport",
            constraint=models.UniqueConstraint(fields=("organization", "report_date"), name="orgmem_daily_report_org_date_uniq"),
        ),
        migrations.AddConstraint(
            model_name="memorydailycostledger",
            constraint=models.UniqueConstraint(fields=("organization", "budget_date"), name="orgmem_cost_ledger_org_date_uniq"),
        ),
        migrations.AddConstraint(
            model_name="memorydailycostledger",
            constraint=models.CheckConstraint(check=models.Q(("ceiling_aud__gte", 0), ("reserved_aud__gte", 0), ("consumed_aud__gte", 0)), name="orgmem_cost_ledger_nonnegative"),
        ),
        migrations.AddIndex(
            model_name="memorycostreservation",
            index=models.Index(fields=["organization", "status", "reserved_at"], name="orgmem_cost_res_org_state"),
        ),
        migrations.AddIndex(
            model_name="memoryconnectionhealthsnapshot",
            index=models.Index(fields=["organization", "health_status", "updated_at"], name="orgmem_health_org_state"),
        ),
        migrations.AddConstraint(
            model_name="memoryconnectionhealthsnapshot",
            constraint=models.UniqueConstraint(fields=("report", "configuration"), name="orgmem_health_report_config_uniq"),
        ),
    ]
