# Generated by Django 4.2.16 on 2026-07-23 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('org_memory', '0017_memorydailyreconciliationreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest_type', models.CharField(choices=[('daily_open_loops', 'Daily open loops'), ('weekly_committee', 'Weekly committee')], db_index=True, max_length=32)),
                ('digest_date', models.DateField(db_index=True)),
                ('time_zone', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('empty', 'Empty'), ('blocked', 'Blocked'), ('stale', 'Stale')], db_index=True, default='ready', max_length=16)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('required_classifications', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_digests', to='organizations.organization')),
                ('source_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='org_memory.memorydailyreconciliationreport')),
            ],
            options={
                'ordering': ('-digest_date', 'digest_type'),
            },
        ),
        migrations.CreateModel(
            name='MemoryDigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_items', to='org_memory.memoryclaim')),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='org_memory.memorydigest')),
            ],
            options={
                'ordering': ('digest', 'ordinal'),
            },
        ),
        migrations.CreateModel(
            name='MemorySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('thread', 'Thread'), ('day', 'Day'), ('week', 'Week'), ('project', 'Project')], db_index=True, max_length=16)),
                ('subject_key', models.CharField(db_index=True, max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('required_classifications', models.JSONField(blank=True, default=list)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('generation_key', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('empty', 'Empty'), ('blocked', 'Blocked'), ('stale', 'Stale')], db_index=True, default='ready', max_length=16)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('invalidated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_summaries', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='org_memory.memorysummary')),
                ('source_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='org_memory.memorydailyreconciliationreport')),
            ],
            options={
                'ordering': ('-window_end', 'summary_type', 'subject_key'),
            },
        ),
        migrations.CreateModel(
            name='MemorySummaryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_links', to='org_memory.memoryevidence')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='org_memory.memorysummary')),
            ],
            options={
                'ordering': ('summary', 'evidence'),
            },
        ),
        migrations.CreateModel(
            name='MemorySummaryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_links', to='org_memory.memoryclaim')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_links', to='org_memory.memorysummary')),
            ],
            options={
                'ordering': ('summary', 'ordinal'),
            },
        ),
        migrations.CreateModel(
            name='MemoryDigestItemEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_item_links', to='org_memory.memoryevidence')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='org_memory.memorydigestitem')),
            ],
            options={
                'ordering': ('item', 'evidence'),
            },
        ),
        migrations.AddField(
            model_name='memorydigestitem',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='org_memory.memorysummary'),
        ),
        migrations.AddConstraint(
            model_name='memorysummaryevidence',
            constraint=models.UniqueConstraint(fields=('summary', 'evidence'), name='orgmem_summary_evidence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorysummaryclaim',
            constraint=models.UniqueConstraint(fields=('summary', 'claim'), name='orgmem_summary_claim_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorysummaryclaim',
            constraint=models.UniqueConstraint(fields=('summary', 'ordinal'), name='orgmem_summary_claim_ord_uniq'),
        ),
        migrations.AddIndex(
            model_name='memorysummary',
            index=models.Index(fields=['organization', 'summary_type', 'is_current', 'window_end'], name='orgmem_summary_org_type_cur'),
        ),
        migrations.AddConstraint(
            model_name='memorysummary',
            constraint=models.UniqueConstraint(fields=('organization', 'generation_key'), name='orgmem_summary_generation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorysummary',
            constraint=models.CheckConstraint(check=models.Q(('window_end__gt', models.F('window_start'))), name='orgmem_summary_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='memorydigestitemevidence',
            constraint=models.UniqueConstraint(fields=('item', 'evidence'), name='orgmem_digest_item_ev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorydigestitem',
            constraint=models.UniqueConstraint(fields=('digest', 'claim'), name='orgmem_digest_claim_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorydigestitem',
            constraint=models.UniqueConstraint(fields=('digest', 'ordinal'), name='orgmem_digest_item_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='memorydigest',
            index=models.Index(fields=['organization', 'digest_type', 'status', 'digest_date'], name='orgmem_digest_org_type_state'),
        ),
        migrations.AddConstraint(
            model_name='memorydigest',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='orgmem_digest_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorydigest',
            constraint=models.UniqueConstraint(fields=('organization', 'digest_type', 'digest_date'), name='orgmem_digest_org_type_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorydigest',
            constraint=models.CheckConstraint(check=models.Q(('window_end__gt', models.F('window_start'))), name='orgmem_digest_window_valid'),
        ),
    ]
