# Generated by Django 4.2.16 on 2026-07-23 03:54

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid


def create_public_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    model = apps.get_model('org_memory', 'PublicKnowledgeItem')
    schema_editor.add_index(
        model,
        pgvector.django.indexes.HnswIndex(
            ef_construction=64,
            fields=['embedding'],
            m=16,
            name='orgmem_public_vector_hnsw',
            opclasses=('vector_cosine_ops',),
        ),
    )


def drop_public_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    model = apps.get_model('org_memory', 'PublicKnowledgeItem')
    schema_editor.remove_index(
        model,
        pgvector.django.indexes.HnswIndex(
            fields=['embedding'],
            name='orgmem_public_vector_hnsw',
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_organization_company_linkedin_url'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('org_memory', '0018_review_summaries_digests'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.CharField(max_length=64)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('public_key', models.SlugField(max_length=160)),
                ('proposed_title', models.CharField(max_length=300)),
                ('proposed_body', models.TextField()),
                ('proposed_tags', models.JSONField(blank=True, default=list)),
                ('proposal_hash', models.CharField(db_index=True, max_length=64)),
                ('sensitivity_findings', models.JSONField(blank=True, default=list)),
                ('redaction_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('invalidated', 'Invalidated')], db_index=True, default='draft', max_length=24)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('creation_request_hash', models.CharField(max_length=64)),
                ('redaction_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=512)),
                ('revocation_idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memory_publications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_publications', to='organizations.organization')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_memory_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PublicKnowledgeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.SlugField(max_length=160)),
                ('revision', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=16)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('embedding_version', models.CharField(blank=True, default='', max_length=64)),
                ('embedding_hash', models.CharField(blank=True, default='', max_length=64)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('superseded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_knowledge_items', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization', 'public_key', '-revision'),
            },
        ),
        migrations.CreateModel(
            name='MemoryPublicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('candidate_created', 'Candidate created'), ('candidate_edited', 'Candidate edited'), ('submitted', 'Submitted'), ('published', 'Published'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('invalidated', 'Invalidated')], db_index=True, max_length=32)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_publication_events', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='org_memory.memorypublication')),
            ],
            options={
                'ordering': ('publication', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='memorypublication',
            name='published_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org_memory.publicknowledgeitem'),
        ),
        migrations.AddField(
            model_name='memorypublication',
            name='redaction_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redaction_confirmed_memory_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memorypublication',
            name='review_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication', to='org_memory.memoryreviewitem'),
        ),
        migrations.AddField(
            model_name='memorypublication',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_memory_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memorypublication',
            name='source_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_memory_publication_sources', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='publicknowledgeitem',
            index=models.Index(fields=['organization', 'status', 'published_at'], name='orgmem_public_item_active'),
        ),
        migrations.AddIndex(
            model_name='publicknowledgeitem',
            index=models.Index(fields=['organization', 'public_key', 'revision'], name='orgmem_public_item_key_rev'),
        ),
        migrations.AddIndex(
            model_name='publicknowledgeitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='orgmem_public_search_gin'),
        ),
        migrations.AddConstraint(
            model_name='publicknowledgeitem',
            constraint=models.UniqueConstraint(fields=('organization', 'public_key', 'revision'), name='orgmem_public_item_revision_uniq'),
        ),
        migrations.AddConstraint(
            model_name='publicknowledgeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('organization', 'public_key'), name='orgmem_public_item_one_active'),
        ),
        migrations.AddConstraint(
            model_name='publicknowledgeitem',
            constraint=models.CheckConstraint(check=models.Q(('revision__gte', 1)), name='orgmem_public_item_revision_pos'),
        ),
        migrations.AddConstraint(
            model_name='publicknowledgeitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('revoked_at__isnull', True), ('status', 'active'), ('superseded_at__isnull', True)), models.Q(('status', 'superseded'), ('superseded_at__isnull', False)), models.Q(('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='orgmem_public_item_state_time'),
        ),
        migrations.AddIndex(
            model_name='memorypublicationevent',
            index=models.Index(fields=['publication', 'created_at'], name='orgmem_publication_event_time'),
        ),
        migrations.AddIndex(
            model_name='memorypublication',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='orgmem_publication_queue'),
        ),
        migrations.AddIndex(
            model_name='memorypublication',
            index=models.Index(fields=['organization', 'public_key', 'created_at'], name='orgmem_publication_key'),
        ),
        migrations.AddIndex(
            model_name='memorypublication',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='orgmem_publication_source'),
        ),
        migrations.AddConstraint(
            model_name='memorypublication',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='orgmem_publication_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorypublication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'pending_review'), _negated=True), models.Q(('redaction_confirmed_at__isnull', False), ('review_item__isnull', False)), _connector='OR'), name='orgmem_publication_review_ready'),
        ),
        migrations.AddConstraint(
            model_name='memorypublication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(('approved_at__isnull', False), ('published_item__isnull', False)), _connector='OR'), name='orgmem_publication_published'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_public_hnsw_index,
                    drop_public_hnsw_index,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='publicknowledgeitem',
                    index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='orgmem_public_vector_hnsw', opclasses=('vector_cosine_ops',)),
                ),
            ],
        ),
    ]
