# Generated by Django 4.2.16 on 2026-07-23 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_memory', '0019_memorypublication_publicknowledgeitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActionProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by_slack_id', models.CharField(blank=True, default='', max_length=32)),
                ('action_type', models.CharField(choices=[('draft_gmail', 'Draft Gmail message'), ('draft_slack_post', 'Draft Slack post'), ('draft_notion_update', 'Draft Notion update'), ('create_linear_issue', 'Create Linear issue'), ('update_linear_issue', 'Update Linear issue')], db_index=True, max_length=32)),
                ('target_system', models.CharField(db_index=True, max_length=32)),
                ('input_payload', models.JSONField(default=dict)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('evidence_claim_ids', models.JSONField(blank=True, default=list)),
                ('evidence_source_ids', models.JSONField(blank=True, default=list)),
                ('precondition_snapshot', models.JSONField(blank=True, default=dict)),
                ('precondition_hash', models.CharField(blank=True, default='', max_length=64)),
                ('preconditions_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=16)),
                ('requires_approval', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('stale', 'Stale'), ('reversing', 'Reversing'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], db_index=True, default='proposed', max_length=32)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('creation_request_hash', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=512)),
                ('execution_idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('execution_attempts', models.PositiveIntegerField(default=0)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True, default='')),
                ('reversal_supported', models.BooleanField(default=False)),
                ('reversal_payload', models.JSONField(blank=True, default=dict)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agent_actions', to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_action_proposals', to='org_memory.memoryconnectionconfiguration')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_agent_actions', to=settings.AUTH_USER_MODEL)),
                ('ingestion_action_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_action_results', to='org_memory.memorysourceactionrequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action_proposals', to='organizations.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_agent_actions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_agent_actions', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_agent_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentActionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('proposed', 'Proposed'), ('preconditions_refreshed', 'Preconditions refreshed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('execution_started', 'Execution started'), ('execution_completed', 'Execution completed'), ('execution_failed', 'Execution failed'), ('approval_invalidated', 'Approval invalidated'), ('ingestion_enqueued', 'Ingestion enqueued'), ('reversal_started', 'Reversal started'), ('reversed', 'Reversed'), ('reversal_failed', 'Reversal failed'), ('cancelled', 'Cancelled')], db_index=True, max_length=32)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_action_events', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='org_memory.agentactionproposal')),
            ],
            options={
                'ordering': ('proposal', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='agentactionproposal',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='orgmem_agent_action_queue'),
        ),
        migrations.AddIndex(
            model_name='agentactionproposal',
            index=models.Index(fields=['organization', 'action_type', 'created_at'], name='orgmem_agent_action_type'),
        ),
        migrations.AddConstraint(
            model_name='agentactionproposal',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='orgmem_agent_action_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='agentactionproposal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'approved'), _negated=True), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='orgmem_agent_action_approved'),
        ),
        migrations.AddConstraint(
            model_name='agentactionproposal',
            constraint=models.CheckConstraint(check=models.Q(('requires_approval', False), models.Q(('status__in', ('approved', 'executing', 'completed', 'reversing', 'reversed')), _negated=True), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='orgmem_agent_action_write_approved'),
        ),
        migrations.AddConstraint(
            model_name='agentactionproposal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'completed'), _negated=True), ('executed_at__isnull', False), _connector='OR'), name='orgmem_agent_action_completed'),
        ),
        migrations.AddConstraint(
            model_name='agentactionproposal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'reversed'), _negated=True), models.Q(('reversed_at__isnull', False), ('reversed_by__isnull', False)), _connector='OR'), name='orgmem_agent_action_reversed'),
        ),
        migrations.AddIndex(
            model_name='agentactionevent',
            index=models.Index(fields=['proposal', 'created_at'], name='orgmem_agent_event_time'),
        ),
    ]
