# Generated by Django 4.2.16 on 2026-07-23 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_company_linkedin_url'),
        ('org_memory', '0020_agentactionproposal_agentactionevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySelectorShadowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('baseline_selector_version', models.CharField(max_length=64)),
                ('learned_selector_version', models.CharField(max_length=128)),
                ('feature_schema_version', models.CharField(max_length=64)),
                ('dataset_hash', models.CharField(db_index=True, max_length=64)),
                ('model_artifact_hash', models.CharField(max_length=64)),
                ('minimum_required_traces', models.PositiveIntegerField(default=3000)),
                ('eligible_trace_count', models.PositiveIntegerField(default=0)),
                ('labeled_trace_count', models.PositiveIntegerField(default=0)),
                ('evaluated_trace_count', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_selector_shadow_runs', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MemorySelectorShadowResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_ref', models.CharField(max_length=64)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('labeled_candidate_count', models.PositiveIntegerField(default=0)),
                ('baseline_order_hash', models.CharField(max_length=64)),
                ('shadow_order_hash', models.CharField(max_length=64)),
                ('top_k_overlap', models.FloatField(default=0)),
                ('baseline_ndcg', models.FloatField(blank=True, null=True)),
                ('shadow_ndcg', models.FloatField(blank=True, null=True)),
                ('baseline_pairwise_accuracy', models.FloatField(blank=True, null=True)),
                ('shadow_pairwise_accuracy', models.FloatField(blank=True, null=True)),
                ('disagreement', models.BooleanField(db_index=True, default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selector_shadow_results', to='org_memory.memoryquerylog')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='org_memory.memoryselectorshadowrun')),
            ],
            options={
                'ordering': ('run', 'query_ref'),
            },
        ),
        migrations.AddIndex(
            model_name='memoryselectorshadowrun',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='orgmem_selector_shadow_status'),
        ),
        migrations.AddConstraint(
            model_name='memoryselectorshadowrun',
            constraint=models.UniqueConstraint(fields=('organization', 'dataset_hash', 'model_artifact_hash', 'learned_selector_version'), name='orgmem_selector_shadow_run_uniq'),
        ),
        migrations.AddIndex(
            model_name='memoryselectorshadowresult',
            index=models.Index(fields=['run', 'disagreement'], name='orgmem_selector_disagree'),
        ),
        migrations.AddConstraint(
            model_name='memoryselectorshadowresult',
            constraint=models.UniqueConstraint(fields=('run', 'query_log'), name='orgmem_selector_shadow_result_uniq'),
        ),
    ]
